// Code generated by ent, DO NOT EDIT.

package rechargeorder

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.RechargeOrder {
	return predicate.RechargeOrder(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.RechargeOrder {
	return predicate.RechargeOrder(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.RechargeOrder {
	return predicate.RechargeOrder(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.RechargeOrder {
	return predicate.RechargeOrder(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.RechargeOrder {
	return predicate.RechargeOrder(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.RechargeOrder {
	return predicate.RechargeOrder(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.RechargeOrder {
	return predicate.RechargeOrder(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.RechargeOrder {
	return predicate.RechargeOrder(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.RechargeOrder {
	return predicate.RechargeOrder(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.RechargeOrder {
	return predicate.RechargeOrder(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.RechargeOrder {
	return predicate.RechargeOrder(sql.FieldEQ(FieldUpdatedAt, v))
}

// OrderNo applies equality check predicate on the "order_no" field. It's identical to OrderNoEQ.
func OrderNo(v string) predicate.RechargeOrder {
	return predicate.RechargeOrder(sql.FieldEQ(FieldOrderNo, v))
}

// UserID applies equality check predicate on the "user_id" field. It's identical to UserIDEQ.
func UserID(v int64) predicate.RechargeOrder {
	return predicate.RechargeOrder(sql.FieldEQ(FieldUserID, v))
}

// Amount applies equality check predicate on the "amount" field. It's identical to AmountEQ.
func Amount(v float64) predicate.RechargeOrder {
	return predicate.RechargeOrder(sql.FieldEQ(FieldAmount, v))
}

// PaymentMethod applies equality check predicate on the "payment_method" field. It's identical to PaymentMethodEQ.
func PaymentMethod(v string) predicate.RechargeOrder {
	return predicate.RechargeOrder(sql.FieldEQ(FieldPaymentMethod, v))
}

// PaymentChannel applies equality check predicate on the "payment_channel" field. It's identical to PaymentChannelEQ.
func PaymentChannel(v string) predicate.RechargeOrder {
	return predicate.RechargeOrder(sql.FieldEQ(FieldPaymentChannel, v))
}

// Status applies equality check predicate on the "status" field. It's identical to StatusEQ.
func Status(v string) predicate.RechargeOrder {
	return predicate.RechargeOrder(sql.FieldEQ(FieldStatus, v))
}

// WechatTransactionID applies equality check predicate on the "wechat_transaction_id" field. It's identical to WechatTransactionIDEQ.
func WechatTransactionID(v string) predicate.RechargeOrder {
	return predicate.RechargeOrder(sql.FieldEQ(FieldWechatTransactionID, v))
}

// QrcodeURL applies equality check predicate on the "qrcode_url" field. It's identical to QrcodeURLEQ.
func QrcodeURL(v string) predicate.RechargeOrder {
	return predicate.RechargeOrder(sql.FieldEQ(FieldQrcodeURL, v))
}

// PrepayID applies equality check predicate on the "prepay_id" field. It's identical to PrepayIDEQ.
func PrepayID(v string) predicate.RechargeOrder {
	return predicate.RechargeOrder(sql.FieldEQ(FieldPrepayID, v))
}

// ExpireAt applies equality check predicate on the "expire_at" field. It's identical to ExpireAtEQ.
func ExpireAt(v time.Time) predicate.RechargeOrder {
	return predicate.RechargeOrder(sql.FieldEQ(FieldExpireAt, v))
}

// PaidAt applies equality check predicate on the "paid_at" field. It's identical to PaidAtEQ.
func PaidAt(v time.Time) predicate.RechargeOrder {
	return predicate.RechargeOrder(sql.FieldEQ(FieldPaidAt, v))
}

// Notes applies equality check predicate on the "notes" field. It's identical to NotesEQ.
func Notes(v string) predicate.RechargeOrder {
	return predicate.RechargeOrder(sql.FieldEQ(FieldNotes, v))
}

// RefundNo applies equality check predicate on the "refund_no" field. It's identical to RefundNoEQ.
func RefundNo(v string) predicate.RechargeOrder {
	return predicate.RechargeOrder(sql.FieldEQ(FieldRefundNo, v))
}

// RefundStatus applies equality check predicate on the "refund_status" field. It's identical to RefundStatusEQ.
func RefundStatus(v string) predicate.RechargeOrder {
	return predicate.RechargeOrder(sql.FieldEQ(FieldRefundStatus, v))
}

// RefundedAt applies equality check predicate on the "refunded_at" field. It's identical to RefundedAtEQ.
func RefundedAt(v time.Time) predicate.RechargeOrder {
	return predicate.RechargeOrder(sql.FieldEQ(FieldRefundedAt, v))
}

// RefundReason applies equality check predicate on the "refund_reason" field. It's identical to RefundReasonEQ.
func RefundReason(v string) predicate.RechargeOrder {
	return predicate.RechargeOrder(sql.FieldEQ(FieldRefundReason, v))
}

// RefundAdminID applies equality check predicate on the "refund_admin_id" field. It's identical to RefundAdminIDEQ.
func RefundAdminID(v int64) predicate.RechargeOrder {
	return predicate.RechargeOrder(sql.FieldEQ(FieldRefundAdminID, v))
}

// WechatRefundID applies equality check predicate on the "wechat_refund_id" field. It's identical to WechatRefundIDEQ.
func WechatRefundID(v string) predicate.RechargeOrder {
	return predicate.RechargeOrder(sql.FieldEQ(FieldWechatRefundID, v))
}

// CreditedAmount applies equality check predicate on the "credited_amount" field. It's identical to CreditedAmountEQ.
func CreditedAmount(v float64) predicate.RechargeOrder {
	return predicate.RechargeOrder(sql.FieldEQ(FieldCreditedAmount, v))
}

// ExchangeRateUsed applies equality check predicate on the "exchange_rate_used" field. It's identical to ExchangeRateUsedEQ.
func ExchangeRateUsed(v float64) predicate.RechargeOrder {
	return predicate.RechargeOrder(sql.FieldEQ(FieldExchangeRateUsed, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.RechargeOrder {
	return predicate.RechargeOrder(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.RechargeOrder {
	return predicate.RechargeOrder(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.RechargeOrder {
	return predicate.RechargeOrder(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.RechargeOrder {
	return predicate.RechargeOrder(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.RechargeOrder {
	return predicate.RechargeOrder(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.RechargeOrder {
	return predicate.RechargeOrder(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.RechargeOrder {
	return predicate.RechargeOrder(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.RechargeOrder {
	return predicate.RechargeOrder(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.RechargeOrder {
	return predicate.RechargeOrder(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.RechargeOrder {
	return predicate.RechargeOrder(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.RechargeOrder {
	return predicate.RechargeOrder(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.RechargeOrder {
	return predicate.RechargeOrder(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.RechargeOrder {
	return predicate.RechargeOrder(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.RechargeOrder {
	return predicate.RechargeOrder(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.RechargeOrder {
	return predicate.RechargeOrder(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.RechargeOrder {
	return predicate.RechargeOrder(sql.FieldLTE(FieldUpdatedAt, v))
}

// OrderNoEQ applies the EQ predicate on the "order_no" field.
func OrderNoEQ(v string) predicate.RechargeOrder {
	return predicate.RechargeOrder(sql.FieldEQ(FieldOrderNo, v))
}

// OrderNoNEQ applies the NEQ predicate on the "order_no" field.
func OrderNoNEQ(v string) predicate.RechargeOrder {
	return predicate.RechargeOrder(sql.FieldNEQ(FieldOrderNo, v))
}

// OrderNoIn applies the In predicate on the "order_no" field.
func OrderNoIn(vs ...string) predicate.RechargeOrder {
	return predicate.RechargeOrder(sql.FieldIn(FieldOrderNo, vs...))
}

// OrderNoNotIn applies the NotIn predicate on the "order_no" field.
func OrderNoNotIn(vs ...string) predicate.RechargeOrder {
	return predicate.RechargeOrder(sql.FieldNotIn(FieldOrderNo, vs...))
}

// OrderNoGT applies the GT predicate on the "order_no" field.
func OrderNoGT(v string) predicate.RechargeOrder {
	return predicate.RechargeOrder(sql.FieldGT(FieldOrderNo, v))
}

// OrderNoGTE applies the GTE predicate on the "order_no" field.
func OrderNoGTE(v string) predicate.RechargeOrder {
	return predicate.RechargeOrder(sql.FieldGTE(FieldOrderNo, v))
}

// OrderNoLT applies the LT predicate on the "order_no" field.
func OrderNoLT(v string) predicate.RechargeOrder {
	return predicate.RechargeOrder(sql.FieldLT(FieldOrderNo, v))
}

// OrderNoLTE applies the LTE predicate on the "order_no" field.
func OrderNoLTE(v string) predicate.RechargeOrder {
	return predicate.RechargeOrder(sql.FieldLTE(FieldOrderNo, v))
}

// OrderNoContains applies the Contains predicate on the "order_no" field.
func OrderNoContains(v string) predicate.RechargeOrder {
	return predicate.RechargeOrder(sql.FieldContains(FieldOrderNo, v))
}

// OrderNoHasPrefix applies the HasPrefix predicate on the "order_no" field.
func OrderNoHasPrefix(v string) predicate.RechargeOrder {
	return predicate.RechargeOrder(sql.FieldHasPrefix(FieldOrderNo, v))
}

// OrderNoHasSuffix applies the HasSuffix predicate on the "order_no" field.
func OrderNoHasSuffix(v string) predicate.RechargeOrder {
	return predicate.RechargeOrder(sql.FieldHasSuffix(FieldOrderNo, v))
}

// OrderNoEqualFold applies the EqualFold predicate on the "order_no" field.
func OrderNoEqualFold(v string) predicate.RechargeOrder {
	return predicate.RechargeOrder(sql.FieldEqualFold(FieldOrderNo, v))
}

// OrderNoContainsFold applies the ContainsFold predicate on the "order_no" field.
func OrderNoContainsFold(v string) predicate.RechargeOrder {
	return predicate.RechargeOrder(sql.FieldContainsFold(FieldOrderNo, v))
}

// UserIDEQ applies the EQ predicate on the "user_id" field.
func UserIDEQ(v int64) predicate.RechargeOrder {
	return predicate.RechargeOrder(sql.FieldEQ(FieldUserID, v))
}

// UserIDNEQ applies the NEQ predicate on the "user_id" field.
func UserIDNEQ(v int64) predicate.RechargeOrder {
	return predicate.RechargeOrder(sql.FieldNEQ(FieldUserID, v))
}

// UserIDIn applies the In predicate on the "user_id" field.
func UserIDIn(vs ...int64) predicate.RechargeOrder {
	return predicate.RechargeOrder(sql.FieldIn(FieldUserID, vs...))
}

// UserIDNotIn applies the NotIn predicate on the "user_id" field.
func UserIDNotIn(vs ...int64) predicate.RechargeOrder {
	return predicate.RechargeOrder(sql.FieldNotIn(FieldUserID, vs...))
}

// AmountEQ applies the EQ predicate on the "amount" field.
func AmountEQ(v float64) predicate.RechargeOrder {
	return predicate.RechargeOrder(sql.FieldEQ(FieldAmount, v))
}

// AmountNEQ applies the NEQ predicate on the "amount" field.
func AmountNEQ(v float64) predicate.RechargeOrder {
	return predicate.RechargeOrder(sql.FieldNEQ(FieldAmount, v))
}

// AmountIn applies the In predicate on the "amount" field.
func AmountIn(vs ...float64) predicate.RechargeOrder {
	return predicate.RechargeOrder(sql.FieldIn(FieldAmount, vs...))
}

// AmountNotIn applies the NotIn predicate on the "amount" field.
func AmountNotIn(vs ...float64) predicate.RechargeOrder {
	return predicate.RechargeOrder(sql.FieldNotIn(FieldAmount, vs...))
}

// AmountGT applies the GT predicate on the "amount" field.
func AmountGT(v float64) predicate.RechargeOrder {
	return predicate.RechargeOrder(sql.FieldGT(FieldAmount, v))
}

// AmountGTE applies the GTE predicate on the "amount" field.
func AmountGTE(v float64) predicate.RechargeOrder {
	return predicate.RechargeOrder(sql.FieldGTE(FieldAmount, v))
}

// AmountLT applies the LT predicate on the "amount" field.
func AmountLT(v float64) predicate.RechargeOrder {
	return predicate.RechargeOrder(sql.FieldLT(FieldAmount, v))
}

// AmountLTE applies the LTE predicate on the "amount" field.
func AmountLTE(v float64) predicate.RechargeOrder {
	return predicate.RechargeOrder(sql.FieldLTE(FieldAmount, v))
}

// PaymentMethodEQ applies the EQ predicate on the "payment_method" field.
func PaymentMethodEQ(v string) predicate.RechargeOrder {
	return predicate.RechargeOrder(sql.FieldEQ(FieldPaymentMethod, v))
}

// PaymentMethodNEQ applies the NEQ predicate on the "payment_method" field.
func PaymentMethodNEQ(v string) predicate.RechargeOrder {
	return predicate.RechargeOrder(sql.FieldNEQ(FieldPaymentMethod, v))
}

// PaymentMethodIn applies the In predicate on the "payment_method" field.
func PaymentMethodIn(vs ...string) predicate.RechargeOrder {
	return predicate.RechargeOrder(sql.FieldIn(FieldPaymentMethod, vs...))
}

// PaymentMethodNotIn applies the NotIn predicate on the "payment_method" field.
func PaymentMethodNotIn(vs ...string) predicate.RechargeOrder {
	return predicate.RechargeOrder(sql.FieldNotIn(FieldPaymentMethod, vs...))
}

// PaymentMethodGT applies the GT predicate on the "payment_method" field.
func PaymentMethodGT(v string) predicate.RechargeOrder {
	return predicate.RechargeOrder(sql.FieldGT(FieldPaymentMethod, v))
}

// PaymentMethodGTE applies the GTE predicate on the "payment_method" field.
func PaymentMethodGTE(v string) predicate.RechargeOrder {
	return predicate.RechargeOrder(sql.FieldGTE(FieldPaymentMethod, v))
}

// PaymentMethodLT applies the LT predicate on the "payment_method" field.
func PaymentMethodLT(v string) predicate.RechargeOrder {
	return predicate.RechargeOrder(sql.FieldLT(FieldPaymentMethod, v))
}

// PaymentMethodLTE applies the LTE predicate on the "payment_method" field.
func PaymentMethodLTE(v string) predicate.RechargeOrder {
	return predicate.RechargeOrder(sql.FieldLTE(FieldPaymentMethod, v))
}

// PaymentMethodContains applies the Contains predicate on the "payment_method" field.
func PaymentMethodContains(v string) predicate.RechargeOrder {
	return predicate.RechargeOrder(sql.FieldContains(FieldPaymentMethod, v))
}

// PaymentMethodHasPrefix applies the HasPrefix predicate on the "payment_method" field.
func PaymentMethodHasPrefix(v string) predicate.RechargeOrder {
	return predicate.RechargeOrder(sql.FieldHasPrefix(FieldPaymentMethod, v))
}

// PaymentMethodHasSuffix applies the HasSuffix predicate on the "payment_method" field.
func PaymentMethodHasSuffix(v string) predicate.RechargeOrder {
	return predicate.RechargeOrder(sql.FieldHasSuffix(FieldPaymentMethod, v))
}

// PaymentMethodEqualFold applies the EqualFold predicate on the "payment_method" field.
func PaymentMethodEqualFold(v string) predicate.RechargeOrder {
	return predicate.RechargeOrder(sql.FieldEqualFold(FieldPaymentMethod, v))
}

// PaymentMethodContainsFold applies the ContainsFold predicate on the "payment_method" field.
func PaymentMethodContainsFold(v string) predicate.RechargeOrder {
	return predicate.RechargeOrder(sql.FieldContainsFold(FieldPaymentMethod, v))
}

// PaymentChannelEQ applies the EQ predicate on the "payment_channel" field.
func PaymentChannelEQ(v string) predicate.RechargeOrder {
	return predicate.RechargeOrder(sql.FieldEQ(FieldPaymentChannel, v))
}

// PaymentChannelNEQ applies the NEQ predicate on the "payment_channel" field.
func PaymentChannelNEQ(v string) predicate.RechargeOrder {
	return predicate.RechargeOrder(sql.FieldNEQ(FieldPaymentChannel, v))
}

// PaymentChannelIn applies the In predicate on the "payment_channel" field.
func PaymentChannelIn(vs ...string) predicate.RechargeOrder {
	return predicate.RechargeOrder(sql.FieldIn(FieldPaymentChannel, vs...))
}

// PaymentChannelNotIn applies the NotIn predicate on the "payment_channel" field.
func PaymentChannelNotIn(vs ...string) predicate.RechargeOrder {
	return predicate.RechargeOrder(sql.FieldNotIn(FieldPaymentChannel, vs...))
}

// PaymentChannelGT applies the GT predicate on the "payment_channel" field.
func PaymentChannelGT(v string) predicate.RechargeOrder {
	return predicate.RechargeOrder(sql.FieldGT(FieldPaymentChannel, v))
}

// PaymentChannelGTE applies the GTE predicate on the "payment_channel" field.
func PaymentChannelGTE(v string) predicate.RechargeOrder {
	return predicate.RechargeOrder(sql.FieldGTE(FieldPaymentChannel, v))
}

// PaymentChannelLT applies the LT predicate on the "payment_channel" field.
func PaymentChannelLT(v string) predicate.RechargeOrder {
	return predicate.RechargeOrder(sql.FieldLT(FieldPaymentChannel, v))
}

// PaymentChannelLTE applies the LTE predicate on the "payment_channel" field.
func PaymentChannelLTE(v string) predicate.RechargeOrder {
	return predicate.RechargeOrder(sql.FieldLTE(FieldPaymentChannel, v))
}

// PaymentChannelContains applies the Contains predicate on the "payment_channel" field.
func PaymentChannelContains(v string) predicate.RechargeOrder {
	return predicate.RechargeOrder(sql.FieldContains(FieldPaymentChannel, v))
}

// PaymentChannelHasPrefix applies the HasPrefix predicate on the "payment_channel" field.
func PaymentChannelHasPrefix(v string) predicate.RechargeOrder {
	return predicate.RechargeOrder(sql.FieldHasPrefix(FieldPaymentChannel, v))
}

// PaymentChannelHasSuffix applies the HasSuffix predicate on the "payment_channel" field.
func PaymentChannelHasSuffix(v string) predicate.RechargeOrder {
	return predicate.RechargeOrder(sql.FieldHasSuffix(FieldPaymentChannel, v))
}

// PaymentChannelEqualFold applies the EqualFold predicate on the "payment_channel" field.
func PaymentChannelEqualFold(v string) predicate.RechargeOrder {
	return predicate.RechargeOrder(sql.FieldEqualFold(FieldPaymentChannel, v))
}

// PaymentChannelContainsFold applies the ContainsFold predicate on the "payment_channel" field.
func PaymentChannelContainsFold(v string) predicate.RechargeOrder {
	return predicate.RechargeOrder(sql.FieldContainsFold(FieldPaymentChannel, v))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v string) predicate.RechargeOrder {
	return predicate.RechargeOrder(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v string) predicate.RechargeOrder {
	return predicate.RechargeOrder(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...string) predicate.RechargeOrder {
	return predicate.RechargeOrder(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...string) predicate.RechargeOrder {
	return predicate.RechargeOrder(sql.FieldNotIn(FieldStatus, vs...))
}

// StatusGT applies the GT predicate on the "status" field.
func StatusGT(v string) predicate.RechargeOrder {
	return predicate.RechargeOrder(sql.FieldGT(FieldStatus, v))
}

// StatusGTE applies the GTE predicate on the "status" field.
func StatusGTE(v string) predicate.RechargeOrder {
	return predicate.RechargeOrder(sql.FieldGTE(FieldStatus, v))
}

// StatusLT applies the LT predicate on the "status" field.
func StatusLT(v string) predicate.RechargeOrder {
	return predicate.RechargeOrder(sql.FieldLT(FieldStatus, v))
}

// StatusLTE applies the LTE predicate on the "status" field.
func StatusLTE(v string) predicate.RechargeOrder {
	return predicate.RechargeOrder(sql.FieldLTE(FieldStatus, v))
}

// StatusContains applies the Contains predicate on the "status" field.
func StatusContains(v string) predicate.RechargeOrder {
	return predicate.RechargeOrder(sql.FieldContains(FieldStatus, v))
}

// StatusHasPrefix applies the HasPrefix predicate on the "status" field.
func StatusHasPrefix(v string) predicate.RechargeOrder {
	return predicate.RechargeOrder(sql.FieldHasPrefix(FieldStatus, v))
}

// StatusHasSuffix applies the HasSuffix predicate on the "status" field.
func StatusHasSuffix(v string) predicate.RechargeOrder {
	return predicate.RechargeOrder(sql.FieldHasSuffix(FieldStatus, v))
}

// StatusEqualFold applies the EqualFold predicate on the "status" field.
func StatusEqualFold(v string) predicate.RechargeOrder {
	return predicate.RechargeOrder(sql.FieldEqualFold(FieldStatus, v))
}

// StatusContainsFold applies the ContainsFold predicate on the "status" field.
func StatusContainsFold(v string) predicate.RechargeOrder {
	return predicate.RechargeOrder(sql.FieldContainsFold(FieldStatus, v))
}

// WechatTransactionIDEQ applies the EQ predicate on the "wechat_transaction_id" field.
func WechatTransactionIDEQ(v string) predicate.RechargeOrder {
	return predicate.RechargeOrder(sql.FieldEQ(FieldWechatTransactionID, v))
}

// WechatTransactionIDNEQ applies the NEQ predicate on the "wechat_transaction_id" field.
func WechatTransactionIDNEQ(v string) predicate.RechargeOrder {
	return predicate.RechargeOrder(sql.FieldNEQ(FieldWechatTransactionID, v))
}

// WechatTransactionIDIn applies the In predicate on the "wechat_transaction_id" field.
func WechatTransactionIDIn(vs ...string) predicate.RechargeOrder {
	return predicate.RechargeOrder(sql.FieldIn(FieldWechatTransactionID, vs...))
}

// WechatTransactionIDNotIn applies the NotIn predicate on the "wechat_transaction_id" field.
func WechatTransactionIDNotIn(vs ...string) predicate.RechargeOrder {
	return predicate.RechargeOrder(sql.FieldNotIn(FieldWechatTransactionID, vs...))
}

// WechatTransactionIDGT applies the GT predicate on the "wechat_transaction_id" field.
func WechatTransactionIDGT(v string) predicate.RechargeOrder {
	return predicate.RechargeOrder(sql.FieldGT(FieldWechatTransactionID, v))
}

// WechatTransactionIDGTE applies the GTE predicate on the "wechat_transaction_id" field.
func WechatTransactionIDGTE(v string) predicate.RechargeOrder {
	return predicate.RechargeOrder(sql.FieldGTE(FieldWechatTransactionID, v))
}

// WechatTransactionIDLT applies the LT predicate on the "wechat_transaction_id" field.
func WechatTransactionIDLT(v string) predicate.RechargeOrder {
	return predicate.RechargeOrder(sql.FieldLT(FieldWechatTransactionID, v))
}

// WechatTransactionIDLTE applies the LTE predicate on the "wechat_transaction_id" field.
func WechatTransactionIDLTE(v string) predicate.RechargeOrder {
	return predicate.RechargeOrder(sql.FieldLTE(FieldWechatTransactionID, v))
}

// WechatTransactionIDContains applies the Contains predicate on the "wechat_transaction_id" field.
func WechatTransactionIDContains(v string) predicate.RechargeOrder {
	return predicate.RechargeOrder(sql.FieldContains(FieldWechatTransactionID, v))
}

// WechatTransactionIDHasPrefix applies the HasPrefix predicate on the "wechat_transaction_id" field.
func WechatTransactionIDHasPrefix(v string) predicate.RechargeOrder {
	return predicate.RechargeOrder(sql.FieldHasPrefix(FieldWechatTransactionID, v))
}

// WechatTransactionIDHasSuffix applies the HasSuffix predicate on the "wechat_transaction_id" field.
func WechatTransactionIDHasSuffix(v string) predicate.RechargeOrder {
	return predicate.RechargeOrder(sql.FieldHasSuffix(FieldWechatTransactionID, v))
}

// WechatTransactionIDIsNil applies the IsNil predicate on the "wechat_transaction_id" field.
func WechatTransactionIDIsNil() predicate.RechargeOrder {
	return predicate.RechargeOrder(sql.FieldIsNull(FieldWechatTransactionID))
}

// WechatTransactionIDNotNil applies the NotNil predicate on the "wechat_transaction_id" field.
func WechatTransactionIDNotNil() predicate.RechargeOrder {
	return predicate.RechargeOrder(sql.FieldNotNull(FieldWechatTransactionID))
}

// WechatTransactionIDEqualFold applies the EqualFold predicate on the "wechat_transaction_id" field.
func WechatTransactionIDEqualFold(v string) predicate.RechargeOrder {
	return predicate.RechargeOrder(sql.FieldEqualFold(FieldWechatTransactionID, v))
}

// WechatTransactionIDContainsFold applies the ContainsFold predicate on the "wechat_transaction_id" field.
func WechatTransactionIDContainsFold(v string) predicate.RechargeOrder {
	return predicate.RechargeOrder(sql.FieldContainsFold(FieldWechatTransactionID, v))
}

// QrcodeURLEQ applies the EQ predicate on the "qrcode_url" field.
func QrcodeURLEQ(v string) predicate.RechargeOrder {
	return predicate.RechargeOrder(sql.FieldEQ(FieldQrcodeURL, v))
}

// QrcodeURLNEQ applies the NEQ predicate on the "qrcode_url" field.
func QrcodeURLNEQ(v string) predicate.RechargeOrder {
	return predicate.RechargeOrder(sql.FieldNEQ(FieldQrcodeURL, v))
}

// QrcodeURLIn applies the In predicate on the "qrcode_url" field.
func QrcodeURLIn(vs ...string) predicate.RechargeOrder {
	return predicate.RechargeOrder(sql.FieldIn(FieldQrcodeURL, vs...))
}

// QrcodeURLNotIn applies the NotIn predicate on the "qrcode_url" field.
func QrcodeURLNotIn(vs ...string) predicate.RechargeOrder {
	return predicate.RechargeOrder(sql.FieldNotIn(FieldQrcodeURL, vs...))
}

// QrcodeURLGT applies the GT predicate on the "qrcode_url" field.
func QrcodeURLGT(v string) predicate.RechargeOrder {
	return predicate.RechargeOrder(sql.FieldGT(FieldQrcodeURL, v))
}

// QrcodeURLGTE applies the GTE predicate on the "qrcode_url" field.
func QrcodeURLGTE(v string) predicate.RechargeOrder {
	return predicate.RechargeOrder(sql.FieldGTE(FieldQrcodeURL, v))
}

// QrcodeURLLT applies the LT predicate on the "qrcode_url" field.
func QrcodeURLLT(v string) predicate.RechargeOrder {
	return predicate.RechargeOrder(sql.FieldLT(FieldQrcodeURL, v))
}

// QrcodeURLLTE applies the LTE predicate on the "qrcode_url" field.
func QrcodeURLLTE(v string) predicate.RechargeOrder {
	return predicate.RechargeOrder(sql.FieldLTE(FieldQrcodeURL, v))
}

// QrcodeURLContains applies the Contains predicate on the "qrcode_url" field.
func QrcodeURLContains(v string) predicate.RechargeOrder {
	return predicate.RechargeOrder(sql.FieldContains(FieldQrcodeURL, v))
}

// QrcodeURLHasPrefix applies the HasPrefix predicate on the "qrcode_url" field.
func QrcodeURLHasPrefix(v string) predicate.RechargeOrder {
	return predicate.RechargeOrder(sql.FieldHasPrefix(FieldQrcodeURL, v))
}

// QrcodeURLHasSuffix applies the HasSuffix predicate on the "qrcode_url" field.
func QrcodeURLHasSuffix(v string) predicate.RechargeOrder {
	return predicate.RechargeOrder(sql.FieldHasSuffix(FieldQrcodeURL, v))
}

// QrcodeURLIsNil applies the IsNil predicate on the "qrcode_url" field.
func QrcodeURLIsNil() predicate.RechargeOrder {
	return predicate.RechargeOrder(sql.FieldIsNull(FieldQrcodeURL))
}

// QrcodeURLNotNil applies the NotNil predicate on the "qrcode_url" field.
func QrcodeURLNotNil() predicate.RechargeOrder {
	return predicate.RechargeOrder(sql.FieldNotNull(FieldQrcodeURL))
}

// QrcodeURLEqualFold applies the EqualFold predicate on the "qrcode_url" field.
func QrcodeURLEqualFold(v string) predicate.RechargeOrder {
	return predicate.RechargeOrder(sql.FieldEqualFold(FieldQrcodeURL, v))
}

// QrcodeURLContainsFold applies the ContainsFold predicate on the "qrcode_url" field.
func QrcodeURLContainsFold(v string) predicate.RechargeOrder {
	return predicate.RechargeOrder(sql.FieldContainsFold(FieldQrcodeURL, v))
}

// PrepayIDEQ applies the EQ predicate on the "prepay_id" field.
func PrepayIDEQ(v string) predicate.RechargeOrder {
	return predicate.RechargeOrder(sql.FieldEQ(FieldPrepayID, v))
}

// PrepayIDNEQ applies the NEQ predicate on the "prepay_id" field.
func PrepayIDNEQ(v string) predicate.RechargeOrder {
	return predicate.RechargeOrder(sql.FieldNEQ(FieldPrepayID, v))
}

// PrepayIDIn applies the In predicate on the "prepay_id" field.
func PrepayIDIn(vs ...string) predicate.RechargeOrder {
	return predicate.RechargeOrder(sql.FieldIn(FieldPrepayID, vs...))
}

// PrepayIDNotIn applies the NotIn predicate on the "prepay_id" field.
func PrepayIDNotIn(vs ...string) predicate.RechargeOrder {
	return predicate.RechargeOrder(sql.FieldNotIn(FieldPrepayID, vs...))
}

// PrepayIDGT applies the GT predicate on the "prepay_id" field.
func PrepayIDGT(v string) predicate.RechargeOrder {
	return predicate.RechargeOrder(sql.FieldGT(FieldPrepayID, v))
}

// PrepayIDGTE applies the GTE predicate on the "prepay_id" field.
func PrepayIDGTE(v string) predicate.RechargeOrder {
	return predicate.RechargeOrder(sql.FieldGTE(FieldPrepayID, v))
}

// PrepayIDLT applies the LT predicate on the "prepay_id" field.
func PrepayIDLT(v string) predicate.RechargeOrder {
	return predicate.RechargeOrder(sql.FieldLT(FieldPrepayID, v))
}

// PrepayIDLTE applies the LTE predicate on the "prepay_id" field.
func PrepayIDLTE(v string) predicate.RechargeOrder {
	return predicate.RechargeOrder(sql.FieldLTE(FieldPrepayID, v))
}

// PrepayIDContains applies the Contains predicate on the "prepay_id" field.
func PrepayIDContains(v string) predicate.RechargeOrder {
	return predicate.RechargeOrder(sql.FieldContains(FieldPrepayID, v))
}

// PrepayIDHasPrefix applies the HasPrefix predicate on the "prepay_id" field.
func PrepayIDHasPrefix(v string) predicate.RechargeOrder {
	return predicate.RechargeOrder(sql.FieldHasPrefix(FieldPrepayID, v))
}

// PrepayIDHasSuffix applies the HasSuffix predicate on the "prepay_id" field.
func PrepayIDHasSuffix(v string) predicate.RechargeOrder {
	return predicate.RechargeOrder(sql.FieldHasSuffix(FieldPrepayID, v))
}

// PrepayIDIsNil applies the IsNil predicate on the "prepay_id" field.
func PrepayIDIsNil() predicate.RechargeOrder {
	return predicate.RechargeOrder(sql.FieldIsNull(FieldPrepayID))
}

// PrepayIDNotNil applies the NotNil predicate on the "prepay_id" field.
func PrepayIDNotNil() predicate.RechargeOrder {
	return predicate.RechargeOrder(sql.FieldNotNull(FieldPrepayID))
}

// PrepayIDEqualFold applies the EqualFold predicate on the "prepay_id" field.
func PrepayIDEqualFold(v string) predicate.RechargeOrder {
	return predicate.RechargeOrder(sql.FieldEqualFold(FieldPrepayID, v))
}

// PrepayIDContainsFold applies the ContainsFold predicate on the "prepay_id" field.
func PrepayIDContainsFold(v string) predicate.RechargeOrder {
	return predicate.RechargeOrder(sql.FieldContainsFold(FieldPrepayID, v))
}

// ExpireAtEQ applies the EQ predicate on the "expire_at" field.
func ExpireAtEQ(v time.Time) predicate.RechargeOrder {
	return predicate.RechargeOrder(sql.FieldEQ(FieldExpireAt, v))
}

// ExpireAtNEQ applies the NEQ predicate on the "expire_at" field.
func ExpireAtNEQ(v time.Time) predicate.RechargeOrder {
	return predicate.RechargeOrder(sql.FieldNEQ(FieldExpireAt, v))
}

// ExpireAtIn applies the In predicate on the "expire_at" field.
func ExpireAtIn(vs ...time.Time) predicate.RechargeOrder {
	return predicate.RechargeOrder(sql.FieldIn(FieldExpireAt, vs...))
}

// ExpireAtNotIn applies the NotIn predicate on the "expire_at" field.
func ExpireAtNotIn(vs ...time.Time) predicate.RechargeOrder {
	return predicate.RechargeOrder(sql.FieldNotIn(FieldExpireAt, vs...))
}

// ExpireAtGT applies the GT predicate on the "expire_at" field.
func ExpireAtGT(v time.Time) predicate.RechargeOrder {
	return predicate.RechargeOrder(sql.FieldGT(FieldExpireAt, v))
}

// ExpireAtGTE applies the GTE predicate on the "expire_at" field.
func ExpireAtGTE(v time.Time) predicate.RechargeOrder {
	return predicate.RechargeOrder(sql.FieldGTE(FieldExpireAt, v))
}

// ExpireAtLT applies the LT predicate on the "expire_at" field.
func ExpireAtLT(v time.Time) predicate.RechargeOrder {
	return predicate.RechargeOrder(sql.FieldLT(FieldExpireAt, v))
}

// ExpireAtLTE applies the LTE predicate on the "expire_at" field.
func ExpireAtLTE(v time.Time) predicate.RechargeOrder {
	return predicate.RechargeOrder(sql.FieldLTE(FieldExpireAt, v))
}

// PaidAtEQ applies the EQ predicate on the "paid_at" field.
func PaidAtEQ(v time.Time) predicate.RechargeOrder {
	return predicate.RechargeOrder(sql.FieldEQ(FieldPaidAt, v))
}

// PaidAtNEQ applies the NEQ predicate on the "paid_at" field.
func PaidAtNEQ(v time.Time) predicate.RechargeOrder {
	return predicate.RechargeOrder(sql.FieldNEQ(FieldPaidAt, v))
}

// PaidAtIn applies the In predicate on the "paid_at" field.
func PaidAtIn(vs ...time.Time) predicate.RechargeOrder {
	return predicate.RechargeOrder(sql.FieldIn(FieldPaidAt, vs...))
}

// PaidAtNotIn applies the NotIn predicate on the "paid_at" field.
func PaidAtNotIn(vs ...time.Time) predicate.RechargeOrder {
	return predicate.RechargeOrder(sql.FieldNotIn(FieldPaidAt, vs...))
}

// PaidAtGT applies the GT predicate on the "paid_at" field.
func PaidAtGT(v time.Time) predicate.RechargeOrder {
	return predicate.RechargeOrder(sql.FieldGT(FieldPaidAt, v))
}

// PaidAtGTE applies the GTE predicate on the "paid_at" field.
func PaidAtGTE(v time.Time) predicate.RechargeOrder {
	return predicate.RechargeOrder(sql.FieldGTE(FieldPaidAt, v))
}

// PaidAtLT applies the LT predicate on the "paid_at" field.
func PaidAtLT(v time.Time) predicate.RechargeOrder {
	return predicate.RechargeOrder(sql.FieldLT(FieldPaidAt, v))
}

// PaidAtLTE applies the LTE predicate on the "paid_at" field.
func PaidAtLTE(v time.Time) predicate.RechargeOrder {
	return predicate.RechargeOrder(sql.FieldLTE(FieldPaidAt, v))
}

// PaidAtIsNil applies the IsNil predicate on the "paid_at" field.
func PaidAtIsNil() predicate.RechargeOrder {
	return predicate.RechargeOrder(sql.FieldIsNull(FieldPaidAt))
}

// PaidAtNotNil applies the NotNil predicate on the "paid_at" field.
func PaidAtNotNil() predicate.RechargeOrder {
	return predicate.RechargeOrder(sql.FieldNotNull(FieldPaidAt))
}

// NotesEQ applies the EQ predicate on the "notes" field.
func NotesEQ(v string) predicate.RechargeOrder {
	return predicate.RechargeOrder(sql.FieldEQ(FieldNotes, v))
}

// NotesNEQ applies the NEQ predicate on the "notes" field.
func NotesNEQ(v string) predicate.RechargeOrder {
	return predicate.RechargeOrder(sql.FieldNEQ(FieldNotes, v))
}

// NotesIn applies the In predicate on the "notes" field.
func NotesIn(vs ...string) predicate.RechargeOrder {
	return predicate.RechargeOrder(sql.FieldIn(FieldNotes, vs...))
}

// NotesNotIn applies the NotIn predicate on the "notes" field.
func NotesNotIn(vs ...string) predicate.RechargeOrder {
	return predicate.RechargeOrder(sql.FieldNotIn(FieldNotes, vs...))
}

// NotesGT applies the GT predicate on the "notes" field.
func NotesGT(v string) predicate.RechargeOrder {
	return predicate.RechargeOrder(sql.FieldGT(FieldNotes, v))
}

// NotesGTE applies the GTE predicate on the "notes" field.
func NotesGTE(v string) predicate.RechargeOrder {
	return predicate.RechargeOrder(sql.FieldGTE(FieldNotes, v))
}

// NotesLT applies the LT predicate on the "notes" field.
func NotesLT(v string) predicate.RechargeOrder {
	return predicate.RechargeOrder(sql.FieldLT(FieldNotes, v))
}

// NotesLTE applies the LTE predicate on the "notes" field.
func NotesLTE(v string) predicate.RechargeOrder {
	return predicate.RechargeOrder(sql.FieldLTE(FieldNotes, v))
}

// NotesContains applies the Contains predicate on the "notes" field.
func NotesContains(v string) predicate.RechargeOrder {
	return predicate.RechargeOrder(sql.FieldContains(FieldNotes, v))
}

// NotesHasPrefix applies the HasPrefix predicate on the "notes" field.
func NotesHasPrefix(v string) predicate.RechargeOrder {
	return predicate.RechargeOrder(sql.FieldHasPrefix(FieldNotes, v))
}

// NotesHasSuffix applies the HasSuffix predicate on the "notes" field.
func NotesHasSuffix(v string) predicate.RechargeOrder {
	return predicate.RechargeOrder(sql.FieldHasSuffix(FieldNotes, v))
}

// NotesEqualFold applies the EqualFold predicate on the "notes" field.
func NotesEqualFold(v string) predicate.RechargeOrder {
	return predicate.RechargeOrder(sql.FieldEqualFold(FieldNotes, v))
}

// NotesContainsFold applies the ContainsFold predicate on the "notes" field.
func NotesContainsFold(v string) predicate.RechargeOrder {
	return predicate.RechargeOrder(sql.FieldContainsFold(FieldNotes, v))
}

// RefundNoEQ applies the EQ predicate on the "refund_no" field.
func RefundNoEQ(v string) predicate.RechargeOrder {
	return predicate.RechargeOrder(sql.FieldEQ(FieldRefundNo, v))
}

// RefundNoNEQ applies the NEQ predicate on the "refund_no" field.
func RefundNoNEQ(v string) predicate.RechargeOrder {
	return predicate.RechargeOrder(sql.FieldNEQ(FieldRefundNo, v))
}

// RefundNoIn applies the In predicate on the "refund_no" field.
func RefundNoIn(vs ...string) predicate.RechargeOrder {
	return predicate.RechargeOrder(sql.FieldIn(FieldRefundNo, vs...))
}

// RefundNoNotIn applies the NotIn predicate on the "refund_no" field.
func RefundNoNotIn(vs ...string) predicate.RechargeOrder {
	return predicate.RechargeOrder(sql.FieldNotIn(FieldRefundNo, vs...))
}

// RefundNoGT applies the GT predicate on the "refund_no" field.
func RefundNoGT(v string) predicate.RechargeOrder {
	return predicate.RechargeOrder(sql.FieldGT(FieldRefundNo, v))
}

// RefundNoGTE applies the GTE predicate on the "refund_no" field.
func RefundNoGTE(v string) predicate.RechargeOrder {
	return predicate.RechargeOrder(sql.FieldGTE(FieldRefundNo, v))
}

// RefundNoLT applies the LT predicate on the "refund_no" field.
func RefundNoLT(v string) predicate.RechargeOrder {
	return predicate.RechargeOrder(sql.FieldLT(FieldRefundNo, v))
}

// RefundNoLTE applies the LTE predicate on the "refund_no" field.
func RefundNoLTE(v string) predicate.RechargeOrder {
	return predicate.RechargeOrder(sql.FieldLTE(FieldRefundNo, v))
}

// RefundNoContains applies the Contains predicate on the "refund_no" field.
func RefundNoContains(v string) predicate.RechargeOrder {
	return predicate.RechargeOrder(sql.FieldContains(FieldRefundNo, v))
}

// RefundNoHasPrefix applies the HasPrefix predicate on the "refund_no" field.
func RefundNoHasPrefix(v string) predicate.RechargeOrder {
	return predicate.RechargeOrder(sql.FieldHasPrefix(FieldRefundNo, v))
}

// RefundNoHasSuffix applies the HasSuffix predicate on the "refund_no" field.
func RefundNoHasSuffix(v string) predicate.RechargeOrder {
	return predicate.RechargeOrder(sql.FieldHasSuffix(FieldRefundNo, v))
}

// RefundNoIsNil applies the IsNil predicate on the "refund_no" field.
func RefundNoIsNil() predicate.RechargeOrder {
	return predicate.RechargeOrder(sql.FieldIsNull(FieldRefundNo))
}

// RefundNoNotNil applies the NotNil predicate on the "refund_no" field.
func RefundNoNotNil() predicate.RechargeOrder {
	return predicate.RechargeOrder(sql.FieldNotNull(FieldRefundNo))
}

// RefundNoEqualFold applies the EqualFold predicate on the "refund_no" field.
func RefundNoEqualFold(v string) predicate.RechargeOrder {
	return predicate.RechargeOrder(sql.FieldEqualFold(FieldRefundNo, v))
}

// RefundNoContainsFold applies the ContainsFold predicate on the "refund_no" field.
func RefundNoContainsFold(v string) predicate.RechargeOrder {
	return predicate.RechargeOrder(sql.FieldContainsFold(FieldRefundNo, v))
}

// RefundStatusEQ applies the EQ predicate on the "refund_status" field.
func RefundStatusEQ(v string) predicate.RechargeOrder {
	return predicate.RechargeOrder(sql.FieldEQ(FieldRefundStatus, v))
}

// RefundStatusNEQ applies the NEQ predicate on the "refund_status" field.
func RefundStatusNEQ(v string) predicate.RechargeOrder {
	return predicate.RechargeOrder(sql.FieldNEQ(FieldRefundStatus, v))
}

// RefundStatusIn applies the In predicate on the "refund_status" field.
func RefundStatusIn(vs ...string) predicate.RechargeOrder {
	return predicate.RechargeOrder(sql.FieldIn(FieldRefundStatus, vs...))
}

// RefundStatusNotIn applies the NotIn predicate on the "refund_status" field.
func RefundStatusNotIn(vs ...string) predicate.RechargeOrder {
	return predicate.RechargeOrder(sql.FieldNotIn(FieldRefundStatus, vs...))
}

// RefundStatusGT applies the GT predicate on the "refund_status" field.
func RefundStatusGT(v string) predicate.RechargeOrder {
	return predicate.RechargeOrder(sql.FieldGT(FieldRefundStatus, v))
}

// RefundStatusGTE applies the GTE predicate on the "refund_status" field.
func RefundStatusGTE(v string) predicate.RechargeOrder {
	return predicate.RechargeOrder(sql.FieldGTE(FieldRefundStatus, v))
}

// RefundStatusLT applies the LT predicate on the "refund_status" field.
func RefundStatusLT(v string) predicate.RechargeOrder {
	return predicate.RechargeOrder(sql.FieldLT(FieldRefundStatus, v))
}

// RefundStatusLTE applies the LTE predicate on the "refund_status" field.
func RefundStatusLTE(v string) predicate.RechargeOrder {
	return predicate.RechargeOrder(sql.FieldLTE(FieldRefundStatus, v))
}

// RefundStatusContains applies the Contains predicate on the "refund_status" field.
func RefundStatusContains(v string) predicate.RechargeOrder {
	return predicate.RechargeOrder(sql.FieldContains(FieldRefundStatus, v))
}

// RefundStatusHasPrefix applies the HasPrefix predicate on the "refund_status" field.
func RefundStatusHasPrefix(v string) predicate.RechargeOrder {
	return predicate.RechargeOrder(sql.FieldHasPrefix(FieldRefundStatus, v))
}

// RefundStatusHasSuffix applies the HasSuffix predicate on the "refund_status" field.
func RefundStatusHasSuffix(v string) predicate.RechargeOrder {
	return predicate.RechargeOrder(sql.FieldHasSuffix(FieldRefundStatus, v))
}

// RefundStatusIsNil applies the IsNil predicate on the "refund_status" field.
func RefundStatusIsNil() predicate.RechargeOrder {
	return predicate.RechargeOrder(sql.FieldIsNull(FieldRefundStatus))
}

// RefundStatusNotNil applies the NotNil predicate on the "refund_status" field.
func RefundStatusNotNil() predicate.RechargeOrder {
	return predicate.RechargeOrder(sql.FieldNotNull(FieldRefundStatus))
}

// RefundStatusEqualFold applies the EqualFold predicate on the "refund_status" field.
func RefundStatusEqualFold(v string) predicate.RechargeOrder {
	return predicate.RechargeOrder(sql.FieldEqualFold(FieldRefundStatus, v))
}

// RefundStatusContainsFold applies the ContainsFold predicate on the "refund_status" field.
func RefundStatusContainsFold(v string) predicate.RechargeOrder {
	return predicate.RechargeOrder(sql.FieldContainsFold(FieldRefundStatus, v))
}

// RefundedAtEQ applies the EQ predicate on the "refunded_at" field.
func RefundedAtEQ(v time.Time) predicate.RechargeOrder {
	return predicate.RechargeOrder(sql.FieldEQ(FieldRefundedAt, v))
}

// RefundedAtNEQ applies the NEQ predicate on the "refunded_at" field.
func RefundedAtNEQ(v time.Time) predicate.RechargeOrder {
	return predicate.RechargeOrder(sql.FieldNEQ(FieldRefundedAt, v))
}

// RefundedAtIn applies the In predicate on the "refunded_at" field.
func RefundedAtIn(vs ...time.Time) predicate.RechargeOrder {
	return predicate.RechargeOrder(sql.FieldIn(FieldRefundedAt, vs...))
}

// RefundedAtNotIn applies the NotIn predicate on the "refunded_at" field.
func RefundedAtNotIn(vs ...time.Time) predicate.RechargeOrder {
	return predicate.RechargeOrder(sql.FieldNotIn(FieldRefundedAt, vs...))
}

// RefundedAtGT applies the GT predicate on the "refunded_at" field.
func RefundedAtGT(v time.Time) predicate.RechargeOrder {
	return predicate.RechargeOrder(sql.FieldGT(FieldRefundedAt, v))
}

// RefundedAtGTE applies the GTE predicate on the "refunded_at" field.
func RefundedAtGTE(v time.Time) predicate.RechargeOrder {
	return predicate.RechargeOrder(sql.FieldGTE(FieldRefundedAt, v))
}

// RefundedAtLT applies the LT predicate on the "refunded_at" field.
func RefundedAtLT(v time.Time) predicate.RechargeOrder {
	return predicate.RechargeOrder(sql.FieldLT(FieldRefundedAt, v))
}

// RefundedAtLTE applies the LTE predicate on the "refunded_at" field.
func RefundedAtLTE(v time.Time) predicate.RechargeOrder {
	return predicate.RechargeOrder(sql.FieldLTE(FieldRefundedAt, v))
}

// RefundedAtIsNil applies the IsNil predicate on the "refunded_at" field.
func RefundedAtIsNil() predicate.RechargeOrder {
	return predicate.RechargeOrder(sql.FieldIsNull(FieldRefundedAt))
}

// RefundedAtNotNil applies the NotNil predicate on the "refunded_at" field.
func RefundedAtNotNil() predicate.RechargeOrder {
	return predicate.RechargeOrder(sql.FieldNotNull(FieldRefundedAt))
}

// RefundReasonEQ applies the EQ predicate on the "refund_reason" field.
func RefundReasonEQ(v string) predicate.RechargeOrder {
	return predicate.RechargeOrder(sql.FieldEQ(FieldRefundReason, v))
}

// RefundReasonNEQ applies the NEQ predicate on the "refund_reason" field.
func RefundReasonNEQ(v string) predicate.RechargeOrder {
	return predicate.RechargeOrder(sql.FieldNEQ(FieldRefundReason, v))
}

// RefundReasonIn applies the In predicate on the "refund_reason" field.
func RefundReasonIn(vs ...string) predicate.RechargeOrder {
	return predicate.RechargeOrder(sql.FieldIn(FieldRefundReason, vs...))
}

// RefundReasonNotIn applies the NotIn predicate on the "refund_reason" field.
func RefundReasonNotIn(vs ...string) predicate.RechargeOrder {
	return predicate.RechargeOrder(sql.FieldNotIn(FieldRefundReason, vs...))
}

// RefundReasonGT applies the GT predicate on the "refund_reason" field.
func RefundReasonGT(v string) predicate.RechargeOrder {
	return predicate.RechargeOrder(sql.FieldGT(FieldRefundReason, v))
}

// RefundReasonGTE applies the GTE predicate on the "refund_reason" field.
func RefundReasonGTE(v string) predicate.RechargeOrder {
	return predicate.RechargeOrder(sql.FieldGTE(FieldRefundReason, v))
}

// RefundReasonLT applies the LT predicate on the "refund_reason" field.
func RefundReasonLT(v string) predicate.RechargeOrder {
	return predicate.RechargeOrder(sql.FieldLT(FieldRefundReason, v))
}

// RefundReasonLTE applies the LTE predicate on the "refund_reason" field.
func RefundReasonLTE(v string) predicate.RechargeOrder {
	return predicate.RechargeOrder(sql.FieldLTE(FieldRefundReason, v))
}

// RefundReasonContains applies the Contains predicate on the "refund_reason" field.
func RefundReasonContains(v string) predicate.RechargeOrder {
	return predicate.RechargeOrder(sql.FieldContains(FieldRefundReason, v))
}

// RefundReasonHasPrefix applies the HasPrefix predicate on the "refund_reason" field.
func RefundReasonHasPrefix(v string) predicate.RechargeOrder {
	return predicate.RechargeOrder(sql.FieldHasPrefix(FieldRefundReason, v))
}

// RefundReasonHasSuffix applies the HasSuffix predicate on the "refund_reason" field.
func RefundReasonHasSuffix(v string) predicate.RechargeOrder {
	return predicate.RechargeOrder(sql.FieldHasSuffix(FieldRefundReason, v))
}

// RefundReasonIsNil applies the IsNil predicate on the "refund_reason" field.
func RefundReasonIsNil() predicate.RechargeOrder {
	return predicate.RechargeOrder(sql.FieldIsNull(FieldRefundReason))
}

// RefundReasonNotNil applies the NotNil predicate on the "refund_reason" field.
func RefundReasonNotNil() predicate.RechargeOrder {
	return predicate.RechargeOrder(sql.FieldNotNull(FieldRefundReason))
}

// RefundReasonEqualFold applies the EqualFold predicate on the "refund_reason" field.
func RefundReasonEqualFold(v string) predicate.RechargeOrder {
	return predicate.RechargeOrder(sql.FieldEqualFold(FieldRefundReason, v))
}

// RefundReasonContainsFold applies the ContainsFold predicate on the "refund_reason" field.
func RefundReasonContainsFold(v string) predicate.RechargeOrder {
	return predicate.RechargeOrder(sql.FieldContainsFold(FieldRefundReason, v))
}

// RefundAdminIDEQ applies the EQ predicate on the "refund_admin_id" field.
func RefundAdminIDEQ(v int64) predicate.RechargeOrder {
	return predicate.RechargeOrder(sql.FieldEQ(FieldRefundAdminID, v))
}

// RefundAdminIDNEQ applies the NEQ predicate on the "refund_admin_id" field.
func RefundAdminIDNEQ(v int64) predicate.RechargeOrder {
	return predicate.RechargeOrder(sql.FieldNEQ(FieldRefundAdminID, v))
}

// RefundAdminIDIn applies the In predicate on the "refund_admin_id" field.
func RefundAdminIDIn(vs ...int64) predicate.RechargeOrder {
	return predicate.RechargeOrder(sql.FieldIn(FieldRefundAdminID, vs...))
}

// RefundAdminIDNotIn applies the NotIn predicate on the "refund_admin_id" field.
func RefundAdminIDNotIn(vs ...int64) predicate.RechargeOrder {
	return predicate.RechargeOrder(sql.FieldNotIn(FieldRefundAdminID, vs...))
}

// RefundAdminIDGT applies the GT predicate on the "refund_admin_id" field.
func RefundAdminIDGT(v int64) predicate.RechargeOrder {
	return predicate.RechargeOrder(sql.FieldGT(FieldRefundAdminID, v))
}

// RefundAdminIDGTE applies the GTE predicate on the "refund_admin_id" field.
func RefundAdminIDGTE(v int64) predicate.RechargeOrder {
	return predicate.RechargeOrder(sql.FieldGTE(FieldRefundAdminID, v))
}

// RefundAdminIDLT applies the LT predicate on the "refund_admin_id" field.
func RefundAdminIDLT(v int64) predicate.RechargeOrder {
	return predicate.RechargeOrder(sql.FieldLT(FieldRefundAdminID, v))
}

// RefundAdminIDLTE applies the LTE predicate on the "refund_admin_id" field.
func RefundAdminIDLTE(v int64) predicate.RechargeOrder {
	return predicate.RechargeOrder(sql.FieldLTE(FieldRefundAdminID, v))
}

// RefundAdminIDIsNil applies the IsNil predicate on the "refund_admin_id" field.
func RefundAdminIDIsNil() predicate.RechargeOrder {
	return predicate.RechargeOrder(sql.FieldIsNull(FieldRefundAdminID))
}

// RefundAdminIDNotNil applies the NotNil predicate on the "refund_admin_id" field.
func RefundAdminIDNotNil() predicate.RechargeOrder {
	return predicate.RechargeOrder(sql.FieldNotNull(FieldRefundAdminID))
}

// WechatRefundIDEQ applies the EQ predicate on the "wechat_refund_id" field.
func WechatRefundIDEQ(v string) predicate.RechargeOrder {
	return predicate.RechargeOrder(sql.FieldEQ(FieldWechatRefundID, v))
}

// WechatRefundIDNEQ applies the NEQ predicate on the "wechat_refund_id" field.
func WechatRefundIDNEQ(v string) predicate.RechargeOrder {
	return predicate.RechargeOrder(sql.FieldNEQ(FieldWechatRefundID, v))
}

// WechatRefundIDIn applies the In predicate on the "wechat_refund_id" field.
func WechatRefundIDIn(vs ...string) predicate.RechargeOrder {
	return predicate.RechargeOrder(sql.FieldIn(FieldWechatRefundID, vs...))
}

// WechatRefundIDNotIn applies the NotIn predicate on the "wechat_refund_id" field.
func WechatRefundIDNotIn(vs ...string) predicate.RechargeOrder {
	return predicate.RechargeOrder(sql.FieldNotIn(FieldWechatRefundID, vs...))
}

// WechatRefundIDGT applies the GT predicate on the "wechat_refund_id" field.
func WechatRefundIDGT(v string) predicate.RechargeOrder {
	return predicate.RechargeOrder(sql.FieldGT(FieldWechatRefundID, v))
}

// WechatRefundIDGTE applies the GTE predicate on the "wechat_refund_id" field.
func WechatRefundIDGTE(v string) predicate.RechargeOrder {
	return predicate.RechargeOrder(sql.FieldGTE(FieldWechatRefundID, v))
}

// WechatRefundIDLT applies the LT predicate on the "wechat_refund_id" field.
func WechatRefundIDLT(v string) predicate.RechargeOrder {
	return predicate.RechargeOrder(sql.FieldLT(FieldWechatRefundID, v))
}

// WechatRefundIDLTE applies the LTE predicate on the "wechat_refund_id" field.
func WechatRefundIDLTE(v string) predicate.RechargeOrder {
	return predicate.RechargeOrder(sql.FieldLTE(FieldWechatRefundID, v))
}

// WechatRefundIDContains applies the Contains predicate on the "wechat_refund_id" field.
func WechatRefundIDContains(v string) predicate.RechargeOrder {
	return predicate.RechargeOrder(sql.FieldContains(FieldWechatRefundID, v))
}

// WechatRefundIDHasPrefix applies the HasPrefix predicate on the "wechat_refund_id" field.
func WechatRefundIDHasPrefix(v string) predicate.RechargeOrder {
	return predicate.RechargeOrder(sql.FieldHasPrefix(FieldWechatRefundID, v))
}

// WechatRefundIDHasSuffix applies the HasSuffix predicate on the "wechat_refund_id" field.
func WechatRefundIDHasSuffix(v string) predicate.RechargeOrder {
	return predicate.RechargeOrder(sql.FieldHasSuffix(FieldWechatRefundID, v))
}

// WechatRefundIDIsNil applies the IsNil predicate on the "wechat_refund_id" field.
func WechatRefundIDIsNil() predicate.RechargeOrder {
	return predicate.RechargeOrder(sql.FieldIsNull(FieldWechatRefundID))
}

// WechatRefundIDNotNil applies the NotNil predicate on the "wechat_refund_id" field.
func WechatRefundIDNotNil() predicate.RechargeOrder {
	return predicate.RechargeOrder(sql.FieldNotNull(FieldWechatRefundID))
}

// WechatRefundIDEqualFold applies the EqualFold predicate on the "wechat_refund_id" field.
func WechatRefundIDEqualFold(v string) predicate.RechargeOrder {
	return predicate.RechargeOrder(sql.FieldEqualFold(FieldWechatRefundID, v))
}

// WechatRefundIDContainsFold applies the ContainsFold predicate on the "wechat_refund_id" field.
func WechatRefundIDContainsFold(v string) predicate.RechargeOrder {
	return predicate.RechargeOrder(sql.FieldContainsFold(FieldWechatRefundID, v))
}

// CreditedAmountEQ applies the EQ predicate on the "credited_amount" field.
func CreditedAmountEQ(v float64) predicate.RechargeOrder {
	return predicate.RechargeOrder(sql.FieldEQ(FieldCreditedAmount, v))
}

// CreditedAmountNEQ applies the NEQ predicate on the "credited_amount" field.
func CreditedAmountNEQ(v float64) predicate.RechargeOrder {
	return predicate.RechargeOrder(sql.FieldNEQ(FieldCreditedAmount, v))
}

// CreditedAmountIn applies the In predicate on the "credited_amount" field.
func CreditedAmountIn(vs ...float64) predicate.RechargeOrder {
	return predicate.RechargeOrder(sql.FieldIn(FieldCreditedAmount, vs...))
}

// CreditedAmountNotIn applies the NotIn predicate on the "credited_amount" field.
func CreditedAmountNotIn(vs ...float64) predicate.RechargeOrder {
	return predicate.RechargeOrder(sql.FieldNotIn(FieldCreditedAmount, vs...))
}

// CreditedAmountGT applies the GT predicate on the "credited_amount" field.
func CreditedAmountGT(v float64) predicate.RechargeOrder {
	return predicate.RechargeOrder(sql.FieldGT(FieldCreditedAmount, v))
}

// CreditedAmountGTE applies the GTE predicate on the "credited_amount" field.
func CreditedAmountGTE(v float64) predicate.RechargeOrder {
	return predicate.RechargeOrder(sql.FieldGTE(FieldCreditedAmount, v))
}

// CreditedAmountLT applies the LT predicate on the "credited_amount" field.
func CreditedAmountLT(v float64) predicate.RechargeOrder {
	return predicate.RechargeOrder(sql.FieldLT(FieldCreditedAmount, v))
}

// CreditedAmountLTE applies the LTE predicate on the "credited_amount" field.
func CreditedAmountLTE(v float64) predicate.RechargeOrder {
	return predicate.RechargeOrder(sql.FieldLTE(FieldCreditedAmount, v))
}

// CreditedAmountIsNil applies the IsNil predicate on the "credited_amount" field.
func CreditedAmountIsNil() predicate.RechargeOrder {
	return predicate.RechargeOrder(sql.FieldIsNull(FieldCreditedAmount))
}

// CreditedAmountNotNil applies the NotNil predicate on the "credited_amount" field.
func CreditedAmountNotNil() predicate.RechargeOrder {
	return predicate.RechargeOrder(sql.FieldNotNull(FieldCreditedAmount))
}

// ExchangeRateUsedEQ applies the EQ predicate on the "exchange_rate_used" field.
func ExchangeRateUsedEQ(v float64) predicate.RechargeOrder {
	return predicate.RechargeOrder(sql.FieldEQ(FieldExchangeRateUsed, v))
}

// ExchangeRateUsedNEQ applies the NEQ predicate on the "exchange_rate_used" field.
func ExchangeRateUsedNEQ(v float64) predicate.RechargeOrder {
	return predicate.RechargeOrder(sql.FieldNEQ(FieldExchangeRateUsed, v))
}

// ExchangeRateUsedIn applies the In predicate on the "exchange_rate_used" field.
func ExchangeRateUsedIn(vs ...float64) predicate.RechargeOrder {
	return predicate.RechargeOrder(sql.FieldIn(FieldExchangeRateUsed, vs...))
}

// ExchangeRateUsedNotIn applies the NotIn predicate on the "exchange_rate_used" field.
func ExchangeRateUsedNotIn(vs ...float64) predicate.RechargeOrder {
	return predicate.RechargeOrder(sql.FieldNotIn(FieldExchangeRateUsed, vs...))
}

// ExchangeRateUsedGT applies the GT predicate on the "exchange_rate_used" field.
func ExchangeRateUsedGT(v float64) predicate.RechargeOrder {
	return predicate.RechargeOrder(sql.FieldGT(FieldExchangeRateUsed, v))
}

// ExchangeRateUsedGTE applies the GTE predicate on the "exchange_rate_used" field.
func ExchangeRateUsedGTE(v float64) predicate.RechargeOrder {
	return predicate.RechargeOrder(sql.FieldGTE(FieldExchangeRateUsed, v))
}

// ExchangeRateUsedLT applies the LT predicate on the "exchange_rate_used" field.
func ExchangeRateUsedLT(v float64) predicate.RechargeOrder {
	return predicate.RechargeOrder(sql.FieldLT(FieldExchangeRateUsed, v))
}

// ExchangeRateUsedLTE applies the LTE predicate on the "exchange_rate_used" field.
func ExchangeRateUsedLTE(v float64) predicate.RechargeOrder {
	return predicate.RechargeOrder(sql.FieldLTE(FieldExchangeRateUsed, v))
}

// ExchangeRateUsedIsNil applies the IsNil predicate on the "exchange_rate_used" field.
func ExchangeRateUsedIsNil() predicate.RechargeOrder {
	return predicate.RechargeOrder(sql.FieldIsNull(FieldExchangeRateUsed))
}

// ExchangeRateUsedNotNil applies the NotNil predicate on the "exchange_rate_used" field.
func ExchangeRateUsedNotNil() predicate.RechargeOrder {
	return predicate.RechargeOrder(sql.FieldNotNull(FieldExchangeRateUsed))
}

// HasUser applies the HasEdge predicate on the "user" edge.
func HasUser() predicate.RechargeOrder {
	return predicate.RechargeOrder(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, UserTable, UserColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasUserWith applies the HasEdge predicate on the "user" edge with a given conditions (other predicates).
func HasUserWith(preds ...predicate.User) predicate.RechargeOrder {
	return predicate.RechargeOrder(func(s *sql.Selector) {
		step := newUserStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.RechargeOrder) predicate.RechargeOrder {
	return predicate.RechargeOrder(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.RechargeOrder) predicate.RechargeOrder {
	return predicate.RechargeOrder(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.RechargeOrder) predicate.RechargeOrder {
	return predicate.RechargeOrder(sql.NotPredicates(p))
}
