// Code generated by ent, DO NOT EDIT.

package usagescript

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.UsageScript {
	return predicate.UsageScript(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.UsageScript {
	return predicate.UsageScript(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.UsageScript {
	return predicate.UsageScript(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.UsageScript {
	return predicate.UsageScript(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.UsageScript {
	return predicate.UsageScript(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.UsageScript {
	return predicate.UsageScript(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.UsageScript {
	return predicate.UsageScript(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.UsageScript {
	return predicate.UsageScript(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.UsageScript {
	return predicate.UsageScript(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.UsageScript {
	return predicate.UsageScript(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.UsageScript {
	return predicate.UsageScript(sql.FieldEQ(FieldUpdatedAt, v))
}

// DeletedAt applies equality check predicate on the "deleted_at" field. It's identical to DeletedAtEQ.
func DeletedAt(v time.Time) predicate.UsageScript {
	return predicate.UsageScript(sql.FieldEQ(FieldDeletedAt, v))
}

// BaseURLHost applies equality check predicate on the "base_url_host" field. It's identical to BaseURLHostEQ.
func BaseURLHost(v string) predicate.UsageScript {
	return predicate.UsageScript(sql.FieldEQ(FieldBaseURLHost, v))
}

// AccountType applies equality check predicate on the "account_type" field. It's identical to AccountTypeEQ.
func AccountType(v string) predicate.UsageScript {
	return predicate.UsageScript(sql.FieldEQ(FieldAccountType, v))
}

// Script applies equality check predicate on the "script" field. It's identical to ScriptEQ.
func Script(v string) predicate.UsageScript {
	return predicate.UsageScript(sql.FieldEQ(FieldScript, v))
}

// Enabled applies equality check predicate on the "enabled" field. It's identical to EnabledEQ.
func Enabled(v bool) predicate.UsageScript {
	return predicate.UsageScript(sql.FieldEQ(FieldEnabled, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.UsageScript {
	return predicate.UsageScript(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.UsageScript {
	return predicate.UsageScript(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.UsageScript {
	return predicate.UsageScript(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.UsageScript {
	return predicate.UsageScript(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.UsageScript {
	return predicate.UsageScript(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.UsageScript {
	return predicate.UsageScript(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.UsageScript {
	return predicate.UsageScript(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.UsageScript {
	return predicate.UsageScript(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.UsageScript {
	return predicate.UsageScript(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.UsageScript {
	return predicate.UsageScript(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.UsageScript {
	return predicate.UsageScript(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.UsageScript {
	return predicate.UsageScript(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.UsageScript {
	return predicate.UsageScript(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.UsageScript {
	return predicate.UsageScript(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.UsageScript {
	return predicate.UsageScript(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.UsageScript {
	return predicate.UsageScript(sql.FieldLTE(FieldUpdatedAt, v))
}

// DeletedAtEQ applies the EQ predicate on the "deleted_at" field.
func DeletedAtEQ(v time.Time) predicate.UsageScript {
	return predicate.UsageScript(sql.FieldEQ(FieldDeletedAt, v))
}

// DeletedAtNEQ applies the NEQ predicate on the "deleted_at" field.
func DeletedAtNEQ(v time.Time) predicate.UsageScript {
	return predicate.UsageScript(sql.FieldNEQ(FieldDeletedAt, v))
}

// DeletedAtIn applies the In predicate on the "deleted_at" field.
func DeletedAtIn(vs ...time.Time) predicate.UsageScript {
	return predicate.UsageScript(sql.FieldIn(FieldDeletedAt, vs...))
}

// DeletedAtNotIn applies the NotIn predicate on the "deleted_at" field.
func DeletedAtNotIn(vs ...time.Time) predicate.UsageScript {
	return predicate.UsageScript(sql.FieldNotIn(FieldDeletedAt, vs...))
}

// DeletedAtGT applies the GT predicate on the "deleted_at" field.
func DeletedAtGT(v time.Time) predicate.UsageScript {
	return predicate.UsageScript(sql.FieldGT(FieldDeletedAt, v))
}

// DeletedAtGTE applies the GTE predicate on the "deleted_at" field.
func DeletedAtGTE(v time.Time) predicate.UsageScript {
	return predicate.UsageScript(sql.FieldGTE(FieldDeletedAt, v))
}

// DeletedAtLT applies the LT predicate on the "deleted_at" field.
func DeletedAtLT(v time.Time) predicate.UsageScript {
	return predicate.UsageScript(sql.FieldLT(FieldDeletedAt, v))
}

// DeletedAtLTE applies the LTE predicate on the "deleted_at" field.
func DeletedAtLTE(v time.Time) predicate.UsageScript {
	return predicate.UsageScript(sql.FieldLTE(FieldDeletedAt, v))
}

// DeletedAtIsNil applies the IsNil predicate on the "deleted_at" field.
func DeletedAtIsNil() predicate.UsageScript {
	return predicate.UsageScript(sql.FieldIsNull(FieldDeletedAt))
}

// DeletedAtNotNil applies the NotNil predicate on the "deleted_at" field.
func DeletedAtNotNil() predicate.UsageScript {
	return predicate.UsageScript(sql.FieldNotNull(FieldDeletedAt))
}

// BaseURLHostEQ applies the EQ predicate on the "base_url_host" field.
func BaseURLHostEQ(v string) predicate.UsageScript {
	return predicate.UsageScript(sql.FieldEQ(FieldBaseURLHost, v))
}

// BaseURLHostNEQ applies the NEQ predicate on the "base_url_host" field.
func BaseURLHostNEQ(v string) predicate.UsageScript {
	return predicate.UsageScript(sql.FieldNEQ(FieldBaseURLHost, v))
}

// BaseURLHostIn applies the In predicate on the "base_url_host" field.
func BaseURLHostIn(vs ...string) predicate.UsageScript {
	return predicate.UsageScript(sql.FieldIn(FieldBaseURLHost, vs...))
}

// BaseURLHostNotIn applies the NotIn predicate on the "base_url_host" field.
func BaseURLHostNotIn(vs ...string) predicate.UsageScript {
	return predicate.UsageScript(sql.FieldNotIn(FieldBaseURLHost, vs...))
}

// BaseURLHostGT applies the GT predicate on the "base_url_host" field.
func BaseURLHostGT(v string) predicate.UsageScript {
	return predicate.UsageScript(sql.FieldGT(FieldBaseURLHost, v))
}

// BaseURLHostGTE applies the GTE predicate on the "base_url_host" field.
func BaseURLHostGTE(v string) predicate.UsageScript {
	return predicate.UsageScript(sql.FieldGTE(FieldBaseURLHost, v))
}

// BaseURLHostLT applies the LT predicate on the "base_url_host" field.
func BaseURLHostLT(v string) predicate.UsageScript {
	return predicate.UsageScript(sql.FieldLT(FieldBaseURLHost, v))
}

// BaseURLHostLTE applies the LTE predicate on the "base_url_host" field.
func BaseURLHostLTE(v string) predicate.UsageScript {
	return predicate.UsageScript(sql.FieldLTE(FieldBaseURLHost, v))
}

// BaseURLHostContains applies the Contains predicate on the "base_url_host" field.
func BaseURLHostContains(v string) predicate.UsageScript {
	return predicate.UsageScript(sql.FieldContains(FieldBaseURLHost, v))
}

// BaseURLHostHasPrefix applies the HasPrefix predicate on the "base_url_host" field.
func BaseURLHostHasPrefix(v string) predicate.UsageScript {
	return predicate.UsageScript(sql.FieldHasPrefix(FieldBaseURLHost, v))
}

// BaseURLHostHasSuffix applies the HasSuffix predicate on the "base_url_host" field.
func BaseURLHostHasSuffix(v string) predicate.UsageScript {
	return predicate.UsageScript(sql.FieldHasSuffix(FieldBaseURLHost, v))
}

// BaseURLHostEqualFold applies the EqualFold predicate on the "base_url_host" field.
func BaseURLHostEqualFold(v string) predicate.UsageScript {
	return predicate.UsageScript(sql.FieldEqualFold(FieldBaseURLHost, v))
}

// BaseURLHostContainsFold applies the ContainsFold predicate on the "base_url_host" field.
func BaseURLHostContainsFold(v string) predicate.UsageScript {
	return predicate.UsageScript(sql.FieldContainsFold(FieldBaseURLHost, v))
}

// AccountTypeEQ applies the EQ predicate on the "account_type" field.
func AccountTypeEQ(v string) predicate.UsageScript {
	return predicate.UsageScript(sql.FieldEQ(FieldAccountType, v))
}

// AccountTypeNEQ applies the NEQ predicate on the "account_type" field.
func AccountTypeNEQ(v string) predicate.UsageScript {
	return predicate.UsageScript(sql.FieldNEQ(FieldAccountType, v))
}

// AccountTypeIn applies the In predicate on the "account_type" field.
func AccountTypeIn(vs ...string) predicate.UsageScript {
	return predicate.UsageScript(sql.FieldIn(FieldAccountType, vs...))
}

// AccountTypeNotIn applies the NotIn predicate on the "account_type" field.
func AccountTypeNotIn(vs ...string) predicate.UsageScript {
	return predicate.UsageScript(sql.FieldNotIn(FieldAccountType, vs...))
}

// AccountTypeGT applies the GT predicate on the "account_type" field.
func AccountTypeGT(v string) predicate.UsageScript {
	return predicate.UsageScript(sql.FieldGT(FieldAccountType, v))
}

// AccountTypeGTE applies the GTE predicate on the "account_type" field.
func AccountTypeGTE(v string) predicate.UsageScript {
	return predicate.UsageScript(sql.FieldGTE(FieldAccountType, v))
}

// AccountTypeLT applies the LT predicate on the "account_type" field.
func AccountTypeLT(v string) predicate.UsageScript {
	return predicate.UsageScript(sql.FieldLT(FieldAccountType, v))
}

// AccountTypeLTE applies the LTE predicate on the "account_type" field.
func AccountTypeLTE(v string) predicate.UsageScript {
	return predicate.UsageScript(sql.FieldLTE(FieldAccountType, v))
}

// AccountTypeContains applies the Contains predicate on the "account_type" field.
func AccountTypeContains(v string) predicate.UsageScript {
	return predicate.UsageScript(sql.FieldContains(FieldAccountType, v))
}

// AccountTypeHasPrefix applies the HasPrefix predicate on the "account_type" field.
func AccountTypeHasPrefix(v string) predicate.UsageScript {
	return predicate.UsageScript(sql.FieldHasPrefix(FieldAccountType, v))
}

// AccountTypeHasSuffix applies the HasSuffix predicate on the "account_type" field.
func AccountTypeHasSuffix(v string) predicate.UsageScript {
	return predicate.UsageScript(sql.FieldHasSuffix(FieldAccountType, v))
}

// AccountTypeEqualFold applies the EqualFold predicate on the "account_type" field.
func AccountTypeEqualFold(v string) predicate.UsageScript {
	return predicate.UsageScript(sql.FieldEqualFold(FieldAccountType, v))
}

// AccountTypeContainsFold applies the ContainsFold predicate on the "account_type" field.
func AccountTypeContainsFold(v string) predicate.UsageScript {
	return predicate.UsageScript(sql.FieldContainsFold(FieldAccountType, v))
}

// ScriptEQ applies the EQ predicate on the "script" field.
func ScriptEQ(v string) predicate.UsageScript {
	return predicate.UsageScript(sql.FieldEQ(FieldScript, v))
}

// ScriptNEQ applies the NEQ predicate on the "script" field.
func ScriptNEQ(v string) predicate.UsageScript {
	return predicate.UsageScript(sql.FieldNEQ(FieldScript, v))
}

// ScriptIn applies the In predicate on the "script" field.
func ScriptIn(vs ...string) predicate.UsageScript {
	return predicate.UsageScript(sql.FieldIn(FieldScript, vs...))
}

// ScriptNotIn applies the NotIn predicate on the "script" field.
func ScriptNotIn(vs ...string) predicate.UsageScript {
	return predicate.UsageScript(sql.FieldNotIn(FieldScript, vs...))
}

// ScriptGT applies the GT predicate on the "script" field.
func ScriptGT(v string) predicate.UsageScript {
	return predicate.UsageScript(sql.FieldGT(FieldScript, v))
}

// ScriptGTE applies the GTE predicate on the "script" field.
func ScriptGTE(v string) predicate.UsageScript {
	return predicate.UsageScript(sql.FieldGTE(FieldScript, v))
}

// ScriptLT applies the LT predicate on the "script" field.
func ScriptLT(v string) predicate.UsageScript {
	return predicate.UsageScript(sql.FieldLT(FieldScript, v))
}

// ScriptLTE applies the LTE predicate on the "script" field.
func ScriptLTE(v string) predicate.UsageScript {
	return predicate.UsageScript(sql.FieldLTE(FieldScript, v))
}

// ScriptContains applies the Contains predicate on the "script" field.
func ScriptContains(v string) predicate.UsageScript {
	return predicate.UsageScript(sql.FieldContains(FieldScript, v))
}

// ScriptHasPrefix applies the HasPrefix predicate on the "script" field.
func ScriptHasPrefix(v string) predicate.UsageScript {
	return predicate.UsageScript(sql.FieldHasPrefix(FieldScript, v))
}

// ScriptHasSuffix applies the HasSuffix predicate on the "script" field.
func ScriptHasSuffix(v string) predicate.UsageScript {
	return predicate.UsageScript(sql.FieldHasSuffix(FieldScript, v))
}

// ScriptEqualFold applies the EqualFold predicate on the "script" field.
func ScriptEqualFold(v string) predicate.UsageScript {
	return predicate.UsageScript(sql.FieldEqualFold(FieldScript, v))
}

// ScriptContainsFold applies the ContainsFold predicate on the "script" field.
func ScriptContainsFold(v string) predicate.UsageScript {
	return predicate.UsageScript(sql.FieldContainsFold(FieldScript, v))
}

// EnabledEQ applies the EQ predicate on the "enabled" field.
func EnabledEQ(v bool) predicate.UsageScript {
	return predicate.UsageScript(sql.FieldEQ(FieldEnabled, v))
}

// EnabledNEQ applies the NEQ predicate on the "enabled" field.
func EnabledNEQ(v bool) predicate.UsageScript {
	return predicate.UsageScript(sql.FieldNEQ(FieldEnabled, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.UsageScript) predicate.UsageScript {
	return predicate.UsageScript(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.UsageScript) predicate.UsageScript {
	return predicate.UsageScript(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.UsageScript) predicate.UsageScript {
	return predicate.UsageScript(sql.NotPredicates(p))
}
