// Code generated by ent, DO NOT EDIT.

package passkeycredential

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the passkeycredential type in the database.
	Label = "passkey_credential"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldUserID holds the string denoting the user_id field in the database.
	FieldUserID = "user_id"
	// FieldCredentialID holds the string denoting the credential_id field in the database.
	FieldCredentialID = "credential_id"
	// FieldPublicKey holds the string denoting the public_key field in the database.
	FieldPublicKey = "public_key"
	// FieldSignCount holds the string denoting the sign_count field in the database.
	FieldSignCount = "sign_count"
	// FieldTransports holds the string denoting the transports field in the database.
	FieldTransports = "transports"
	// FieldAaguid holds the string denoting the aaguid field in the database.
	FieldAaguid = "aaguid"
	// FieldBackupEligible holds the string denoting the backup_eligible field in the database.
	FieldBackupEligible = "backup_eligible"
	// FieldBackupState holds the string denoting the backup_state field in the database.
	FieldBackupState = "backup_state"
	// FieldFriendlyName holds the string denoting the friendly_name field in the database.
	FieldFriendlyName = "friendly_name"
	// FieldLastUsedAt holds the string denoting the last_used_at field in the database.
	FieldLastUsedAt = "last_used_at"
	// FieldRevokedAt holds the string denoting the revoked_at field in the database.
	FieldRevokedAt = "revoked_at"
	// EdgeUser holds the string denoting the user edge name in mutations.
	EdgeUser = "user"
	// Table holds the table name of the passkeycredential in the database.
	Table = "passkey_credentials"
	// UserTable is the table that holds the user relation/edge.
	UserTable = "passkey_credentials"
	// UserInverseTable is the table name for the User entity.
	// It exists in this package in order to avoid circular dependency with the "user" package.
	UserInverseTable = "users"
	// UserColumn is the table column denoting the user relation/edge.
	UserColumn = "user_id"
)

// Columns holds all SQL columns for passkeycredential fields.
var Columns = []string{
	FieldID,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldUserID,
	FieldCredentialID,
	FieldPublicKey,
	FieldSignCount,
	FieldTransports,
	FieldAaguid,
	FieldBackupEligible,
	FieldBackupState,
	FieldFriendlyName,
	FieldLastUsedAt,
	FieldRevokedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// CredentialIDValidator is a validator for the "credential_id" field. It is called by the builders before save.
	CredentialIDValidator func(string) error
	// PublicKeyValidator is a validator for the "public_key" field. It is called by the builders before save.
	PublicKeyValidator func(string) error
	// DefaultSignCount holds the default value on creation for the "sign_count" field.
	DefaultSignCount int64
	// DefaultAaguid holds the default value on creation for the "aaguid" field.
	DefaultAaguid string
	// AaguidValidator is a validator for the "aaguid" field. It is called by the builders before save.
	AaguidValidator func(string) error
	// DefaultBackupEligible holds the default value on creation for the "backup_eligible" field.
	DefaultBackupEligible bool
	// DefaultBackupState holds the default value on creation for the "backup_state" field.
	DefaultBackupState bool
	// DefaultFriendlyName holds the default value on creation for the "friendly_name" field.
	DefaultFriendlyName string
	// FriendlyNameValidator is a validator for the "friendly_name" field. It is called by the builders before save.
	FriendlyNameValidator func(string) error
)

// OrderOption defines the ordering options for the PasskeyCredential queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByUserID orders the results by the user_id field.
func ByUserID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUserID, opts...).ToFunc()
}

// ByCredentialID orders the results by the credential_id field.
func ByCredentialID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCredentialID, opts...).ToFunc()
}

// ByPublicKey orders the results by the public_key field.
func ByPublicKey(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPublicKey, opts...).ToFunc()
}

// BySignCount orders the results by the sign_count field.
func BySignCount(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSignCount, opts...).ToFunc()
}

// ByAaguid orders the results by the aaguid field.
func ByAaguid(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAaguid, opts...).ToFunc()
}

// ByBackupEligible orders the results by the backup_eligible field.
func ByBackupEligible(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldBackupEligible, opts...).ToFunc()
}

// ByBackupState orders the results by the backup_state field.
func ByBackupState(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldBackupState, opts...).ToFunc()
}

// ByFriendlyName orders the results by the friendly_name field.
func ByFriendlyName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldFriendlyName, opts...).ToFunc()
}

// ByLastUsedAt orders the results by the last_used_at field.
func ByLastUsedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLastUsedAt, opts...).ToFunc()
}

// ByRevokedAt orders the results by the revoked_at field.
func ByRevokedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRevokedAt, opts...).ToFunc()
}

// ByUserField orders the results by user field.
func ByUserField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newUserStep(), sql.OrderByField(field, opts...))
	}
}
func newUserStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(UserInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, UserTable, UserColumn),
	)
}
