// Code generated by ent, DO NOT EDIT.

package copilotbudgetalert

import (
	"time"

	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the copilotbudgetalert type in the database.
	Label = "copilot_budget_alert"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldAccountID holds the string denoting the account_id field in the database.
	FieldAccountID = "account_id"
	// FieldMonthlyBudget holds the string denoting the monthly_budget field in the database.
	FieldMonthlyBudget = "monthly_budget"
	// FieldAlertThreshold holds the string denoting the alert_threshold field in the database.
	FieldAlertThreshold = "alert_threshold"
	// FieldEnabled holds the string denoting the enabled field in the database.
	FieldEnabled = "enabled"
	// FieldLastAlertedAt holds the string denoting the last_alerted_at field in the database.
	FieldLastAlertedAt = "last_alerted_at"
	// Table holds the table name of the copilotbudgetalert in the database.
	Table = "copilot_budget_alerts"
)

// Columns holds all SQL columns for copilotbudgetalert fields.
var Columns = []string{
	FieldID,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldAccountID,
	FieldMonthlyBudget,
	FieldAlertThreshold,
	FieldEnabled,
	FieldLastAlertedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// DefaultMonthlyBudget holds the default value on creation for the "monthly_budget" field.
	DefaultMonthlyBudget float64
	// DefaultAlertThreshold holds the default value on creation for the "alert_threshold" field.
	DefaultAlertThreshold int
	// DefaultEnabled holds the default value on creation for the "enabled" field.
	DefaultEnabled bool
)

// OrderOption defines the ordering options for the CopilotBudgetAlert queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByAccountID orders the results by the account_id field.
func ByAccountID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAccountID, opts...).ToFunc()
}

// ByMonthlyBudget orders the results by the monthly_budget field.
func ByMonthlyBudget(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldMonthlyBudget, opts...).ToFunc()
}

// ByAlertThreshold orders the results by the alert_threshold field.
func ByAlertThreshold(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAlertThreshold, opts...).ToFunc()
}

// ByEnabled orders the results by the enabled field.
func ByEnabled(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldEnabled, opts...).ToFunc()
}

// ByLastAlertedAt orders the results by the last_alerted_at field.
func ByLastAlertedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLastAlertedAt, opts...).ToFunc()
}
