// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/balancelog"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
	"github.com/Wei-Shaw/sub2api/ent/user"
)

// BalanceLogUpdate is the builder for updating BalanceLog entities.
type BalanceLogUpdate struct {
	config
	hooks    []Hook
	mutation *BalanceLogMutation
}

// Where appends a list predicates to the BalanceLogUpdate builder.
func (_u *BalanceLogUpdate) Where(ps ...predicate.BalanceLog) *BalanceLogUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *BalanceLogUpdate) SetUpdatedAt(v time.Time) *BalanceLogUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *BalanceLogUpdate) SetUserID(v int64) *BalanceLogUpdate {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *BalanceLogUpdate) SetNillableUserID(v *int64) *BalanceLogUpdate {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetChangeType sets the "change_type" field.
func (_u *BalanceLogUpdate) SetChangeType(v string) *BalanceLogUpdate {
	_u.mutation.SetChangeType(v)
	return _u
}

// SetNillableChangeType sets the "change_type" field if the given value is not nil.
func (_u *BalanceLogUpdate) SetNillableChangeType(v *string) *BalanceLogUpdate {
	if v != nil {
		_u.SetChangeType(*v)
	}
	return _u
}

// SetAmount sets the "amount" field.
func (_u *BalanceLogUpdate) SetAmount(v float64) *BalanceLogUpdate {
	_u.mutation.ResetAmount()
	_u.mutation.SetAmount(v)
	return _u
}

// SetNillableAmount sets the "amount" field if the given value is not nil.
func (_u *BalanceLogUpdate) SetNillableAmount(v *float64) *BalanceLogUpdate {
	if v != nil {
		_u.SetAmount(*v)
	}
	return _u
}

// AddAmount adds value to the "amount" field.
func (_u *BalanceLogUpdate) AddAmount(v float64) *BalanceLogUpdate {
	_u.mutation.AddAmount(v)
	return _u
}

// SetBalanceBefore sets the "balance_before" field.
func (_u *BalanceLogUpdate) SetBalanceBefore(v float64) *BalanceLogUpdate {
	_u.mutation.ResetBalanceBefore()
	_u.mutation.SetBalanceBefore(v)
	return _u
}

// SetNillableBalanceBefore sets the "balance_before" field if the given value is not nil.
func (_u *BalanceLogUpdate) SetNillableBalanceBefore(v *float64) *BalanceLogUpdate {
	if v != nil {
		_u.SetBalanceBefore(*v)
	}
	return _u
}

// AddBalanceBefore adds value to the "balance_before" field.
func (_u *BalanceLogUpdate) AddBalanceBefore(v float64) *BalanceLogUpdate {
	_u.mutation.AddBalanceBefore(v)
	return _u
}

// SetBalanceAfter sets the "balance_after" field.
func (_u *BalanceLogUpdate) SetBalanceAfter(v float64) *BalanceLogUpdate {
	_u.mutation.ResetBalanceAfter()
	_u.mutation.SetBalanceAfter(v)
	return _u
}

// SetNillableBalanceAfter sets the "balance_after" field if the given value is not nil.
func (_u *BalanceLogUpdate) SetNillableBalanceAfter(v *float64) *BalanceLogUpdate {
	if v != nil {
		_u.SetBalanceAfter(*v)
	}
	return _u
}

// AddBalanceAfter adds value to the "balance_after" field.
func (_u *BalanceLogUpdate) AddBalanceAfter(v float64) *BalanceLogUpdate {
	_u.mutation.AddBalanceAfter(v)
	return _u
}

// SetRelatedOrderNo sets the "related_order_no" field.
func (_u *BalanceLogUpdate) SetRelatedOrderNo(v string) *BalanceLogUpdate {
	_u.mutation.SetRelatedOrderNo(v)
	return _u
}

// SetNillableRelatedOrderNo sets the "related_order_no" field if the given value is not nil.
func (_u *BalanceLogUpdate) SetNillableRelatedOrderNo(v *string) *BalanceLogUpdate {
	if v != nil {
		_u.SetRelatedOrderNo(*v)
	}
	return _u
}

// ClearRelatedOrderNo clears the value of the "related_order_no" field.
func (_u *BalanceLogUpdate) ClearRelatedOrderNo() *BalanceLogUpdate {
	_u.mutation.ClearRelatedOrderNo()
	return _u
}

// SetDescription sets the "description" field.
func (_u *BalanceLogUpdate) SetDescription(v string) *BalanceLogUpdate {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *BalanceLogUpdate) SetNillableDescription(v *string) *BalanceLogUpdate {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// SetOperatorID sets the "operator_id" field.
func (_u *BalanceLogUpdate) SetOperatorID(v int64) *BalanceLogUpdate {
	_u.mutation.ResetOperatorID()
	_u.mutation.SetOperatorID(v)
	return _u
}

// SetNillableOperatorID sets the "operator_id" field if the given value is not nil.
func (_u *BalanceLogUpdate) SetNillableOperatorID(v *int64) *BalanceLogUpdate {
	if v != nil {
		_u.SetOperatorID(*v)
	}
	return _u
}

// AddOperatorID adds value to the "operator_id" field.
func (_u *BalanceLogUpdate) AddOperatorID(v int64) *BalanceLogUpdate {
	_u.mutation.AddOperatorID(v)
	return _u
}

// SetOperatorType sets the "operator_type" field.
func (_u *BalanceLogUpdate) SetOperatorType(v string) *BalanceLogUpdate {
	_u.mutation.SetOperatorType(v)
	return _u
}

// SetNillableOperatorType sets the "operator_type" field if the given value is not nil.
func (_u *BalanceLogUpdate) SetNillableOperatorType(v *string) *BalanceLogUpdate {
	if v != nil {
		_u.SetOperatorType(*v)
	}
	return _u
}

// SetUser sets the "user" edge to the User entity.
func (_u *BalanceLogUpdate) SetUser(v *User) *BalanceLogUpdate {
	return _u.SetUserID(v.ID)
}

// Mutation returns the BalanceLogMutation object of the builder.
func (_u *BalanceLogUpdate) Mutation() *BalanceLogMutation {
	return _u.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (_u *BalanceLogUpdate) ClearUser() *BalanceLogUpdate {
	_u.mutation.ClearUser()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *BalanceLogUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *BalanceLogUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *BalanceLogUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *BalanceLogUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *BalanceLogUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := balancelog.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *BalanceLogUpdate) check() error {
	if v, ok := _u.mutation.UserID(); ok {
		if err := balancelog.UserIDValidator(v); err != nil {
			return &ValidationError{Name: "user_id", err: fmt.Errorf(`ent: validator failed for field "BalanceLog.user_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ChangeType(); ok {
		if err := balancelog.ChangeTypeValidator(v); err != nil {
			return &ValidationError{Name: "change_type", err: fmt.Errorf(`ent: validator failed for field "BalanceLog.change_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.RelatedOrderNo(); ok {
		if err := balancelog.RelatedOrderNoValidator(v); err != nil {
			return &ValidationError{Name: "related_order_no", err: fmt.Errorf(`ent: validator failed for field "BalanceLog.related_order_no": %w`, err)}
		}
	}
	if v, ok := _u.mutation.OperatorType(); ok {
		if err := balancelog.OperatorTypeValidator(v); err != nil {
			return &ValidationError{Name: "operator_type", err: fmt.Errorf(`ent: validator failed for field "BalanceLog.operator_type": %w`, err)}
		}
	}
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "BalanceLog.user"`)
	}
	return nil
}

func (_u *BalanceLogUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(balancelog.Table, balancelog.Columns, sqlgraph.NewFieldSpec(balancelog.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(balancelog.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.ChangeType(); ok {
		_spec.SetField(balancelog.FieldChangeType, field.TypeString, value)
	}
	if value, ok := _u.mutation.Amount(); ok {
		_spec.SetField(balancelog.FieldAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedAmount(); ok {
		_spec.AddField(balancelog.FieldAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.BalanceBefore(); ok {
		_spec.SetField(balancelog.FieldBalanceBefore, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedBalanceBefore(); ok {
		_spec.AddField(balancelog.FieldBalanceBefore, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.BalanceAfter(); ok {
		_spec.SetField(balancelog.FieldBalanceAfter, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedBalanceAfter(); ok {
		_spec.AddField(balancelog.FieldBalanceAfter, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.RelatedOrderNo(); ok {
		_spec.SetField(balancelog.FieldRelatedOrderNo, field.TypeString, value)
	}
	if _u.mutation.RelatedOrderNoCleared() {
		_spec.ClearField(balancelog.FieldRelatedOrderNo, field.TypeString)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(balancelog.FieldDescription, field.TypeString, value)
	}
	if value, ok := _u.mutation.OperatorID(); ok {
		_spec.SetField(balancelog.FieldOperatorID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedOperatorID(); ok {
		_spec.AddField(balancelog.FieldOperatorID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.OperatorType(); ok {
		_spec.SetField(balancelog.FieldOperatorType, field.TypeString, value)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   balancelog.UserTable,
			Columns: []string{balancelog.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   balancelog.UserTable,
			Columns: []string{balancelog.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{balancelog.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// BalanceLogUpdateOne is the builder for updating a single BalanceLog entity.
type BalanceLogUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *BalanceLogMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *BalanceLogUpdateOne) SetUpdatedAt(v time.Time) *BalanceLogUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *BalanceLogUpdateOne) SetUserID(v int64) *BalanceLogUpdateOne {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *BalanceLogUpdateOne) SetNillableUserID(v *int64) *BalanceLogUpdateOne {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetChangeType sets the "change_type" field.
func (_u *BalanceLogUpdateOne) SetChangeType(v string) *BalanceLogUpdateOne {
	_u.mutation.SetChangeType(v)
	return _u
}

// SetNillableChangeType sets the "change_type" field if the given value is not nil.
func (_u *BalanceLogUpdateOne) SetNillableChangeType(v *string) *BalanceLogUpdateOne {
	if v != nil {
		_u.SetChangeType(*v)
	}
	return _u
}

// SetAmount sets the "amount" field.
func (_u *BalanceLogUpdateOne) SetAmount(v float64) *BalanceLogUpdateOne {
	_u.mutation.ResetAmount()
	_u.mutation.SetAmount(v)
	return _u
}

// SetNillableAmount sets the "amount" field if the given value is not nil.
func (_u *BalanceLogUpdateOne) SetNillableAmount(v *float64) *BalanceLogUpdateOne {
	if v != nil {
		_u.SetAmount(*v)
	}
	return _u
}

// AddAmount adds value to the "amount" field.
func (_u *BalanceLogUpdateOne) AddAmount(v float64) *BalanceLogUpdateOne {
	_u.mutation.AddAmount(v)
	return _u
}

// SetBalanceBefore sets the "balance_before" field.
func (_u *BalanceLogUpdateOne) SetBalanceBefore(v float64) *BalanceLogUpdateOne {
	_u.mutation.ResetBalanceBefore()
	_u.mutation.SetBalanceBefore(v)
	return _u
}

// SetNillableBalanceBefore sets the "balance_before" field if the given value is not nil.
func (_u *BalanceLogUpdateOne) SetNillableBalanceBefore(v *float64) *BalanceLogUpdateOne {
	if v != nil {
		_u.SetBalanceBefore(*v)
	}
	return _u
}

// AddBalanceBefore adds value to the "balance_before" field.
func (_u *BalanceLogUpdateOne) AddBalanceBefore(v float64) *BalanceLogUpdateOne {
	_u.mutation.AddBalanceBefore(v)
	return _u
}

// SetBalanceAfter sets the "balance_after" field.
func (_u *BalanceLogUpdateOne) SetBalanceAfter(v float64) *BalanceLogUpdateOne {
	_u.mutation.ResetBalanceAfter()
	_u.mutation.SetBalanceAfter(v)
	return _u
}

// SetNillableBalanceAfter sets the "balance_after" field if the given value is not nil.
func (_u *BalanceLogUpdateOne) SetNillableBalanceAfter(v *float64) *BalanceLogUpdateOne {
	if v != nil {
		_u.SetBalanceAfter(*v)
	}
	return _u
}

// AddBalanceAfter adds value to the "balance_after" field.
func (_u *BalanceLogUpdateOne) AddBalanceAfter(v float64) *BalanceLogUpdateOne {
	_u.mutation.AddBalanceAfter(v)
	return _u
}

// SetRelatedOrderNo sets the "related_order_no" field.
func (_u *BalanceLogUpdateOne) SetRelatedOrderNo(v string) *BalanceLogUpdateOne {
	_u.mutation.SetRelatedOrderNo(v)
	return _u
}

// SetNillableRelatedOrderNo sets the "related_order_no" field if the given value is not nil.
func (_u *BalanceLogUpdateOne) SetNillableRelatedOrderNo(v *string) *BalanceLogUpdateOne {
	if v != nil {
		_u.SetRelatedOrderNo(*v)
	}
	return _u
}

// ClearRelatedOrderNo clears the value of the "related_order_no" field.
func (_u *BalanceLogUpdateOne) ClearRelatedOrderNo() *BalanceLogUpdateOne {
	_u.mutation.ClearRelatedOrderNo()
	return _u
}

// SetDescription sets the "description" field.
func (_u *BalanceLogUpdateOne) SetDescription(v string) *BalanceLogUpdateOne {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *BalanceLogUpdateOne) SetNillableDescription(v *string) *BalanceLogUpdateOne {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// SetOperatorID sets the "operator_id" field.
func (_u *BalanceLogUpdateOne) SetOperatorID(v int64) *BalanceLogUpdateOne {
	_u.mutation.ResetOperatorID()
	_u.mutation.SetOperatorID(v)
	return _u
}

// SetNillableOperatorID sets the "operator_id" field if the given value is not nil.
func (_u *BalanceLogUpdateOne) SetNillableOperatorID(v *int64) *BalanceLogUpdateOne {
	if v != nil {
		_u.SetOperatorID(*v)
	}
	return _u
}

// AddOperatorID adds value to the "operator_id" field.
func (_u *BalanceLogUpdateOne) AddOperatorID(v int64) *BalanceLogUpdateOne {
	_u.mutation.AddOperatorID(v)
	return _u
}

// SetOperatorType sets the "operator_type" field.
func (_u *BalanceLogUpdateOne) SetOperatorType(v string) *BalanceLogUpdateOne {
	_u.mutation.SetOperatorType(v)
	return _u
}

// SetNillableOperatorType sets the "operator_type" field if the given value is not nil.
func (_u *BalanceLogUpdateOne) SetNillableOperatorType(v *string) *BalanceLogUpdateOne {
	if v != nil {
		_u.SetOperatorType(*v)
	}
	return _u
}

// SetUser sets the "user" edge to the User entity.
func (_u *BalanceLogUpdateOne) SetUser(v *User) *BalanceLogUpdateOne {
	return _u.SetUserID(v.ID)
}

// Mutation returns the BalanceLogMutation object of the builder.
func (_u *BalanceLogUpdateOne) Mutation() *BalanceLogMutation {
	return _u.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (_u *BalanceLogUpdateOne) ClearUser() *BalanceLogUpdateOne {
	_u.mutation.ClearUser()
	return _u
}

// Where appends a list predicates to the BalanceLogUpdate builder.
func (_u *BalanceLogUpdateOne) Where(ps ...predicate.BalanceLog) *BalanceLogUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *BalanceLogUpdateOne) Select(field string, fields ...string) *BalanceLogUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated BalanceLog entity.
func (_u *BalanceLogUpdateOne) Save(ctx context.Context) (*BalanceLog, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *BalanceLogUpdateOne) SaveX(ctx context.Context) *BalanceLog {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *BalanceLogUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *BalanceLogUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *BalanceLogUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := balancelog.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *BalanceLogUpdateOne) check() error {
	if v, ok := _u.mutation.UserID(); ok {
		if err := balancelog.UserIDValidator(v); err != nil {
			return &ValidationError{Name: "user_id", err: fmt.Errorf(`ent: validator failed for field "BalanceLog.user_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ChangeType(); ok {
		if err := balancelog.ChangeTypeValidator(v); err != nil {
			return &ValidationError{Name: "change_type", err: fmt.Errorf(`ent: validator failed for field "BalanceLog.change_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.RelatedOrderNo(); ok {
		if err := balancelog.RelatedOrderNoValidator(v); err != nil {
			return &ValidationError{Name: "related_order_no", err: fmt.Errorf(`ent: validator failed for field "BalanceLog.related_order_no": %w`, err)}
		}
	}
	if v, ok := _u.mutation.OperatorType(); ok {
		if err := balancelog.OperatorTypeValidator(v); err != nil {
			return &ValidationError{Name: "operator_type", err: fmt.Errorf(`ent: validator failed for field "BalanceLog.operator_type": %w`, err)}
		}
	}
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "BalanceLog.user"`)
	}
	return nil
}

func (_u *BalanceLogUpdateOne) sqlSave(ctx context.Context) (_node *BalanceLog, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(balancelog.Table, balancelog.Columns, sqlgraph.NewFieldSpec(balancelog.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "BalanceLog.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, balancelog.FieldID)
		for _, f := range fields {
			if !balancelog.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != balancelog.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(balancelog.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.ChangeType(); ok {
		_spec.SetField(balancelog.FieldChangeType, field.TypeString, value)
	}
	if value, ok := _u.mutation.Amount(); ok {
		_spec.SetField(balancelog.FieldAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedAmount(); ok {
		_spec.AddField(balancelog.FieldAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.BalanceBefore(); ok {
		_spec.SetField(balancelog.FieldBalanceBefore, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedBalanceBefore(); ok {
		_spec.AddField(balancelog.FieldBalanceBefore, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.BalanceAfter(); ok {
		_spec.SetField(balancelog.FieldBalanceAfter, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedBalanceAfter(); ok {
		_spec.AddField(balancelog.FieldBalanceAfter, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.RelatedOrderNo(); ok {
		_spec.SetField(balancelog.FieldRelatedOrderNo, field.TypeString, value)
	}
	if _u.mutation.RelatedOrderNoCleared() {
		_spec.ClearField(balancelog.FieldRelatedOrderNo, field.TypeString)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(balancelog.FieldDescription, field.TypeString, value)
	}
	if value, ok := _u.mutation.OperatorID(); ok {
		_spec.SetField(balancelog.FieldOperatorID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedOperatorID(); ok {
		_spec.AddField(balancelog.FieldOperatorID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.OperatorType(); ok {
		_spec.SetField(balancelog.FieldOperatorType, field.TypeString, value)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   balancelog.UserTable,
			Columns: []string{balancelog.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   balancelog.UserTable,
			Columns: []string{balancelog.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &BalanceLog{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{balancelog.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
