// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/copilotquotasnapshot"
)

// CopilotQuotaSnapshot is the model entity for the CopilotQuotaSnapshot schema.
type CopilotQuotaSnapshot struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// AccountID holds the value of the "account_id" field.
	AccountID int64 `json:"account_id,omitempty"`
	// SnapshotDate holds the value of the "snapshot_date" field.
	SnapshotDate time.Time `json:"snapshot_date,omitempty"`
	// PlanType holds the value of the "plan_type" field.
	PlanType *string `json:"plan_type,omitempty"`
	// PremiumEntitlement holds the value of the "premium_entitlement" field.
	PremiumEntitlement int `json:"premium_entitlement,omitempty"`
	// PremiumRemaining holds the value of the "premium_remaining" field.
	PremiumRemaining int `json:"premium_remaining,omitempty"`
	// PremiumUsed holds the value of the "premium_used" field.
	PremiumUsed int `json:"premium_used,omitempty"`
	// PremiumOverage holds the value of the "premium_overage" field.
	PremiumOverage int `json:"premium_overage,omitempty"`
	// Unlimited holds the value of the "unlimited" field.
	Unlimited bool `json:"unlimited,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt    time.Time `json:"created_at,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*CopilotQuotaSnapshot) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case copilotquotasnapshot.FieldUnlimited:
			values[i] = new(sql.NullBool)
		case copilotquotasnapshot.FieldID, copilotquotasnapshot.FieldAccountID, copilotquotasnapshot.FieldPremiumEntitlement, copilotquotasnapshot.FieldPremiumRemaining, copilotquotasnapshot.FieldPremiumUsed, copilotquotasnapshot.FieldPremiumOverage:
			values[i] = new(sql.NullInt64)
		case copilotquotasnapshot.FieldPlanType:
			values[i] = new(sql.NullString)
		case copilotquotasnapshot.FieldSnapshotDate, copilotquotasnapshot.FieldCreatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the CopilotQuotaSnapshot fields.
func (_m *CopilotQuotaSnapshot) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case copilotquotasnapshot.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case copilotquotasnapshot.FieldAccountID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field account_id", values[i])
			} else if value.Valid {
				_m.AccountID = value.Int64
			}
		case copilotquotasnapshot.FieldSnapshotDate:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field snapshot_date", values[i])
			} else if value.Valid {
				_m.SnapshotDate = value.Time
			}
		case copilotquotasnapshot.FieldPlanType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field plan_type", values[i])
			} else if value.Valid {
				_m.PlanType = new(string)
				*_m.PlanType = value.String
			}
		case copilotquotasnapshot.FieldPremiumEntitlement:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field premium_entitlement", values[i])
			} else if value.Valid {
				_m.PremiumEntitlement = int(value.Int64)
			}
		case copilotquotasnapshot.FieldPremiumRemaining:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field premium_remaining", values[i])
			} else if value.Valid {
				_m.PremiumRemaining = int(value.Int64)
			}
		case copilotquotasnapshot.FieldPremiumUsed:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field premium_used", values[i])
			} else if value.Valid {
				_m.PremiumUsed = int(value.Int64)
			}
		case copilotquotasnapshot.FieldPremiumOverage:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field premium_overage", values[i])
			} else if value.Valid {
				_m.PremiumOverage = int(value.Int64)
			}
		case copilotquotasnapshot.FieldUnlimited:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field unlimited", values[i])
			} else if value.Valid {
				_m.Unlimited = value.Bool
			}
		case copilotquotasnapshot.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the CopilotQuotaSnapshot.
// This includes values selected through modifiers, order, etc.
func (_m *CopilotQuotaSnapshot) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this CopilotQuotaSnapshot.
// Note that you need to call CopilotQuotaSnapshot.Unwrap() before calling this method if this CopilotQuotaSnapshot
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *CopilotQuotaSnapshot) Update() *CopilotQuotaSnapshotUpdateOne {
	return NewCopilotQuotaSnapshotClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the CopilotQuotaSnapshot entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *CopilotQuotaSnapshot) Unwrap() *CopilotQuotaSnapshot {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: CopilotQuotaSnapshot is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *CopilotQuotaSnapshot) String() string {
	var builder strings.Builder
	builder.WriteString("CopilotQuotaSnapshot(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("account_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.AccountID))
	builder.WriteString(", ")
	builder.WriteString("snapshot_date=")
	builder.WriteString(_m.SnapshotDate.Format(time.ANSIC))
	builder.WriteString(", ")
	if v := _m.PlanType; v != nil {
		builder.WriteString("plan_type=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("premium_entitlement=")
	builder.WriteString(fmt.Sprintf("%v", _m.PremiumEntitlement))
	builder.WriteString(", ")
	builder.WriteString("premium_remaining=")
	builder.WriteString(fmt.Sprintf("%v", _m.PremiumRemaining))
	builder.WriteString(", ")
	builder.WriteString("premium_used=")
	builder.WriteString(fmt.Sprintf("%v", _m.PremiumUsed))
	builder.WriteString(", ")
	builder.WriteString("premium_overage=")
	builder.WriteString(fmt.Sprintf("%v", _m.PremiumOverage))
	builder.WriteString(", ")
	builder.WriteString("unlimited=")
	builder.WriteString(fmt.Sprintf("%v", _m.Unlimited))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// CopilotQuotaSnapshots is a parsable slice of CopilotQuotaSnapshot.
type CopilotQuotaSnapshots []*CopilotQuotaSnapshot
