// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/copilotquotasnapshot"
)

// CopilotQuotaSnapshotCreate is the builder for creating a CopilotQuotaSnapshot entity.
type CopilotQuotaSnapshotCreate struct {
	config
	mutation *CopilotQuotaSnapshotMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetAccountID sets the "account_id" field.
func (_c *CopilotQuotaSnapshotCreate) SetAccountID(v int64) *CopilotQuotaSnapshotCreate {
	_c.mutation.SetAccountID(v)
	return _c
}

// SetSnapshotDate sets the "snapshot_date" field.
func (_c *CopilotQuotaSnapshotCreate) SetSnapshotDate(v time.Time) *CopilotQuotaSnapshotCreate {
	_c.mutation.SetSnapshotDate(v)
	return _c
}

// SetPlanType sets the "plan_type" field.
func (_c *CopilotQuotaSnapshotCreate) SetPlanType(v string) *CopilotQuotaSnapshotCreate {
	_c.mutation.SetPlanType(v)
	return _c
}

// SetNillablePlanType sets the "plan_type" field if the given value is not nil.
func (_c *CopilotQuotaSnapshotCreate) SetNillablePlanType(v *string) *CopilotQuotaSnapshotCreate {
	if v != nil {
		_c.SetPlanType(*v)
	}
	return _c
}

// SetPremiumEntitlement sets the "premium_entitlement" field.
func (_c *CopilotQuotaSnapshotCreate) SetPremiumEntitlement(v int) *CopilotQuotaSnapshotCreate {
	_c.mutation.SetPremiumEntitlement(v)
	return _c
}

// SetNillablePremiumEntitlement sets the "premium_entitlement" field if the given value is not nil.
func (_c *CopilotQuotaSnapshotCreate) SetNillablePremiumEntitlement(v *int) *CopilotQuotaSnapshotCreate {
	if v != nil {
		_c.SetPremiumEntitlement(*v)
	}
	return _c
}

// SetPremiumRemaining sets the "premium_remaining" field.
func (_c *CopilotQuotaSnapshotCreate) SetPremiumRemaining(v int) *CopilotQuotaSnapshotCreate {
	_c.mutation.SetPremiumRemaining(v)
	return _c
}

// SetNillablePremiumRemaining sets the "premium_remaining" field if the given value is not nil.
func (_c *CopilotQuotaSnapshotCreate) SetNillablePremiumRemaining(v *int) *CopilotQuotaSnapshotCreate {
	if v != nil {
		_c.SetPremiumRemaining(*v)
	}
	return _c
}

// SetPremiumUsed sets the "premium_used" field.
func (_c *CopilotQuotaSnapshotCreate) SetPremiumUsed(v int) *CopilotQuotaSnapshotCreate {
	_c.mutation.SetPremiumUsed(v)
	return _c
}

// SetNillablePremiumUsed sets the "premium_used" field if the given value is not nil.
func (_c *CopilotQuotaSnapshotCreate) SetNillablePremiumUsed(v *int) *CopilotQuotaSnapshotCreate {
	if v != nil {
		_c.SetPremiumUsed(*v)
	}
	return _c
}

// SetPremiumOverage sets the "premium_overage" field.
func (_c *CopilotQuotaSnapshotCreate) SetPremiumOverage(v int) *CopilotQuotaSnapshotCreate {
	_c.mutation.SetPremiumOverage(v)
	return _c
}

// SetNillablePremiumOverage sets the "premium_overage" field if the given value is not nil.
func (_c *CopilotQuotaSnapshotCreate) SetNillablePremiumOverage(v *int) *CopilotQuotaSnapshotCreate {
	if v != nil {
		_c.SetPremiumOverage(*v)
	}
	return _c
}

// SetUnlimited sets the "unlimited" field.
func (_c *CopilotQuotaSnapshotCreate) SetUnlimited(v bool) *CopilotQuotaSnapshotCreate {
	_c.mutation.SetUnlimited(v)
	return _c
}

// SetNillableUnlimited sets the "unlimited" field if the given value is not nil.
func (_c *CopilotQuotaSnapshotCreate) SetNillableUnlimited(v *bool) *CopilotQuotaSnapshotCreate {
	if v != nil {
		_c.SetUnlimited(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *CopilotQuotaSnapshotCreate) SetCreatedAt(v time.Time) *CopilotQuotaSnapshotCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *CopilotQuotaSnapshotCreate) SetNillableCreatedAt(v *time.Time) *CopilotQuotaSnapshotCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// Mutation returns the CopilotQuotaSnapshotMutation object of the builder.
func (_c *CopilotQuotaSnapshotCreate) Mutation() *CopilotQuotaSnapshotMutation {
	return _c.mutation
}

// Save creates the CopilotQuotaSnapshot in the database.
func (_c *CopilotQuotaSnapshotCreate) Save(ctx context.Context) (*CopilotQuotaSnapshot, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *CopilotQuotaSnapshotCreate) SaveX(ctx context.Context) *CopilotQuotaSnapshot {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *CopilotQuotaSnapshotCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *CopilotQuotaSnapshotCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *CopilotQuotaSnapshotCreate) defaults() {
	if _, ok := _c.mutation.PremiumEntitlement(); !ok {
		v := copilotquotasnapshot.DefaultPremiumEntitlement
		_c.mutation.SetPremiumEntitlement(v)
	}
	if _, ok := _c.mutation.PremiumRemaining(); !ok {
		v := copilotquotasnapshot.DefaultPremiumRemaining
		_c.mutation.SetPremiumRemaining(v)
	}
	if _, ok := _c.mutation.PremiumUsed(); !ok {
		v := copilotquotasnapshot.DefaultPremiumUsed
		_c.mutation.SetPremiumUsed(v)
	}
	if _, ok := _c.mutation.PremiumOverage(); !ok {
		v := copilotquotasnapshot.DefaultPremiumOverage
		_c.mutation.SetPremiumOverage(v)
	}
	if _, ok := _c.mutation.Unlimited(); !ok {
		v := copilotquotasnapshot.DefaultUnlimited
		_c.mutation.SetUnlimited(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := copilotquotasnapshot.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *CopilotQuotaSnapshotCreate) check() error {
	if _, ok := _c.mutation.AccountID(); !ok {
		return &ValidationError{Name: "account_id", err: errors.New(`ent: missing required field "CopilotQuotaSnapshot.account_id"`)}
	}
	if _, ok := _c.mutation.SnapshotDate(); !ok {
		return &ValidationError{Name: "snapshot_date", err: errors.New(`ent: missing required field "CopilotQuotaSnapshot.snapshot_date"`)}
	}
	if v, ok := _c.mutation.PlanType(); ok {
		if err := copilotquotasnapshot.PlanTypeValidator(v); err != nil {
			return &ValidationError{Name: "plan_type", err: fmt.Errorf(`ent: validator failed for field "CopilotQuotaSnapshot.plan_type": %w`, err)}
		}
	}
	if _, ok := _c.mutation.PremiumEntitlement(); !ok {
		return &ValidationError{Name: "premium_entitlement", err: errors.New(`ent: missing required field "CopilotQuotaSnapshot.premium_entitlement"`)}
	}
	if _, ok := _c.mutation.PremiumRemaining(); !ok {
		return &ValidationError{Name: "premium_remaining", err: errors.New(`ent: missing required field "CopilotQuotaSnapshot.premium_remaining"`)}
	}
	if _, ok := _c.mutation.PremiumUsed(); !ok {
		return &ValidationError{Name: "premium_used", err: errors.New(`ent: missing required field "CopilotQuotaSnapshot.premium_used"`)}
	}
	if _, ok := _c.mutation.PremiumOverage(); !ok {
		return &ValidationError{Name: "premium_overage", err: errors.New(`ent: missing required field "CopilotQuotaSnapshot.premium_overage"`)}
	}
	if _, ok := _c.mutation.Unlimited(); !ok {
		return &ValidationError{Name: "unlimited", err: errors.New(`ent: missing required field "CopilotQuotaSnapshot.unlimited"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "CopilotQuotaSnapshot.created_at"`)}
	}
	return nil
}

func (_c *CopilotQuotaSnapshotCreate) sqlSave(ctx context.Context) (*CopilotQuotaSnapshot, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *CopilotQuotaSnapshotCreate) createSpec() (*CopilotQuotaSnapshot, *sqlgraph.CreateSpec) {
	var (
		_node = &CopilotQuotaSnapshot{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(copilotquotasnapshot.Table, sqlgraph.NewFieldSpec(copilotquotasnapshot.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.AccountID(); ok {
		_spec.SetField(copilotquotasnapshot.FieldAccountID, field.TypeInt64, value)
		_node.AccountID = value
	}
	if value, ok := _c.mutation.SnapshotDate(); ok {
		_spec.SetField(copilotquotasnapshot.FieldSnapshotDate, field.TypeTime, value)
		_node.SnapshotDate = value
	}
	if value, ok := _c.mutation.PlanType(); ok {
		_spec.SetField(copilotquotasnapshot.FieldPlanType, field.TypeString, value)
		_node.PlanType = &value
	}
	if value, ok := _c.mutation.PremiumEntitlement(); ok {
		_spec.SetField(copilotquotasnapshot.FieldPremiumEntitlement, field.TypeInt, value)
		_node.PremiumEntitlement = value
	}
	if value, ok := _c.mutation.PremiumRemaining(); ok {
		_spec.SetField(copilotquotasnapshot.FieldPremiumRemaining, field.TypeInt, value)
		_node.PremiumRemaining = value
	}
	if value, ok := _c.mutation.PremiumUsed(); ok {
		_spec.SetField(copilotquotasnapshot.FieldPremiumUsed, field.TypeInt, value)
		_node.PremiumUsed = value
	}
	if value, ok := _c.mutation.PremiumOverage(); ok {
		_spec.SetField(copilotquotasnapshot.FieldPremiumOverage, field.TypeInt, value)
		_node.PremiumOverage = value
	}
	if value, ok := _c.mutation.Unlimited(); ok {
		_spec.SetField(copilotquotasnapshot.FieldUnlimited, field.TypeBool, value)
		_node.Unlimited = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(copilotquotasnapshot.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.CopilotQuotaSnapshot.Create().
//		SetAccountID(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.CopilotQuotaSnapshotUpsert) {
//			SetAccountID(v+v).
//		}).
//		Exec(ctx)
func (_c *CopilotQuotaSnapshotCreate) OnConflict(opts ...sql.ConflictOption) *CopilotQuotaSnapshotUpsertOne {
	_c.conflict = opts
	return &CopilotQuotaSnapshotUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.CopilotQuotaSnapshot.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *CopilotQuotaSnapshotCreate) OnConflictColumns(columns ...string) *CopilotQuotaSnapshotUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &CopilotQuotaSnapshotUpsertOne{
		create: _c,
	}
}

type (
	// CopilotQuotaSnapshotUpsertOne is the builder for "upsert"-ing
	//  one CopilotQuotaSnapshot node.
	CopilotQuotaSnapshotUpsertOne struct {
		create *CopilotQuotaSnapshotCreate
	}

	// CopilotQuotaSnapshotUpsert is the "OnConflict" setter.
	CopilotQuotaSnapshotUpsert struct {
		*sql.UpdateSet
	}
)

// SetAccountID sets the "account_id" field.
func (u *CopilotQuotaSnapshotUpsert) SetAccountID(v int64) *CopilotQuotaSnapshotUpsert {
	u.Set(copilotquotasnapshot.FieldAccountID, v)
	return u
}

// UpdateAccountID sets the "account_id" field to the value that was provided on create.
func (u *CopilotQuotaSnapshotUpsert) UpdateAccountID() *CopilotQuotaSnapshotUpsert {
	u.SetExcluded(copilotquotasnapshot.FieldAccountID)
	return u
}

// AddAccountID adds v to the "account_id" field.
func (u *CopilotQuotaSnapshotUpsert) AddAccountID(v int64) *CopilotQuotaSnapshotUpsert {
	u.Add(copilotquotasnapshot.FieldAccountID, v)
	return u
}

// SetSnapshotDate sets the "snapshot_date" field.
func (u *CopilotQuotaSnapshotUpsert) SetSnapshotDate(v time.Time) *CopilotQuotaSnapshotUpsert {
	u.Set(copilotquotasnapshot.FieldSnapshotDate, v)
	return u
}

// UpdateSnapshotDate sets the "snapshot_date" field to the value that was provided on create.
func (u *CopilotQuotaSnapshotUpsert) UpdateSnapshotDate() *CopilotQuotaSnapshotUpsert {
	u.SetExcluded(copilotquotasnapshot.FieldSnapshotDate)
	return u
}

// SetPlanType sets the "plan_type" field.
func (u *CopilotQuotaSnapshotUpsert) SetPlanType(v string) *CopilotQuotaSnapshotUpsert {
	u.Set(copilotquotasnapshot.FieldPlanType, v)
	return u
}

// UpdatePlanType sets the "plan_type" field to the value that was provided on create.
func (u *CopilotQuotaSnapshotUpsert) UpdatePlanType() *CopilotQuotaSnapshotUpsert {
	u.SetExcluded(copilotquotasnapshot.FieldPlanType)
	return u
}

// ClearPlanType clears the value of the "plan_type" field.
func (u *CopilotQuotaSnapshotUpsert) ClearPlanType() *CopilotQuotaSnapshotUpsert {
	u.SetNull(copilotquotasnapshot.FieldPlanType)
	return u
}

// SetPremiumEntitlement sets the "premium_entitlement" field.
func (u *CopilotQuotaSnapshotUpsert) SetPremiumEntitlement(v int) *CopilotQuotaSnapshotUpsert {
	u.Set(copilotquotasnapshot.FieldPremiumEntitlement, v)
	return u
}

// UpdatePremiumEntitlement sets the "premium_entitlement" field to the value that was provided on create.
func (u *CopilotQuotaSnapshotUpsert) UpdatePremiumEntitlement() *CopilotQuotaSnapshotUpsert {
	u.SetExcluded(copilotquotasnapshot.FieldPremiumEntitlement)
	return u
}

// AddPremiumEntitlement adds v to the "premium_entitlement" field.
func (u *CopilotQuotaSnapshotUpsert) AddPremiumEntitlement(v int) *CopilotQuotaSnapshotUpsert {
	u.Add(copilotquotasnapshot.FieldPremiumEntitlement, v)
	return u
}

// SetPremiumRemaining sets the "premium_remaining" field.
func (u *CopilotQuotaSnapshotUpsert) SetPremiumRemaining(v int) *CopilotQuotaSnapshotUpsert {
	u.Set(copilotquotasnapshot.FieldPremiumRemaining, v)
	return u
}

// UpdatePremiumRemaining sets the "premium_remaining" field to the value that was provided on create.
func (u *CopilotQuotaSnapshotUpsert) UpdatePremiumRemaining() *CopilotQuotaSnapshotUpsert {
	u.SetExcluded(copilotquotasnapshot.FieldPremiumRemaining)
	return u
}

// AddPremiumRemaining adds v to the "premium_remaining" field.
func (u *CopilotQuotaSnapshotUpsert) AddPremiumRemaining(v int) *CopilotQuotaSnapshotUpsert {
	u.Add(copilotquotasnapshot.FieldPremiumRemaining, v)
	return u
}

// SetPremiumUsed sets the "premium_used" field.
func (u *CopilotQuotaSnapshotUpsert) SetPremiumUsed(v int) *CopilotQuotaSnapshotUpsert {
	u.Set(copilotquotasnapshot.FieldPremiumUsed, v)
	return u
}

// UpdatePremiumUsed sets the "premium_used" field to the value that was provided on create.
func (u *CopilotQuotaSnapshotUpsert) UpdatePremiumUsed() *CopilotQuotaSnapshotUpsert {
	u.SetExcluded(copilotquotasnapshot.FieldPremiumUsed)
	return u
}

// AddPremiumUsed adds v to the "premium_used" field.
func (u *CopilotQuotaSnapshotUpsert) AddPremiumUsed(v int) *CopilotQuotaSnapshotUpsert {
	u.Add(copilotquotasnapshot.FieldPremiumUsed, v)
	return u
}

// SetPremiumOverage sets the "premium_overage" field.
func (u *CopilotQuotaSnapshotUpsert) SetPremiumOverage(v int) *CopilotQuotaSnapshotUpsert {
	u.Set(copilotquotasnapshot.FieldPremiumOverage, v)
	return u
}

// UpdatePremiumOverage sets the "premium_overage" field to the value that was provided on create.
func (u *CopilotQuotaSnapshotUpsert) UpdatePremiumOverage() *CopilotQuotaSnapshotUpsert {
	u.SetExcluded(copilotquotasnapshot.FieldPremiumOverage)
	return u
}

// AddPremiumOverage adds v to the "premium_overage" field.
func (u *CopilotQuotaSnapshotUpsert) AddPremiumOverage(v int) *CopilotQuotaSnapshotUpsert {
	u.Add(copilotquotasnapshot.FieldPremiumOverage, v)
	return u
}

// SetUnlimited sets the "unlimited" field.
func (u *CopilotQuotaSnapshotUpsert) SetUnlimited(v bool) *CopilotQuotaSnapshotUpsert {
	u.Set(copilotquotasnapshot.FieldUnlimited, v)
	return u
}

// UpdateUnlimited sets the "unlimited" field to the value that was provided on create.
func (u *CopilotQuotaSnapshotUpsert) UpdateUnlimited() *CopilotQuotaSnapshotUpsert {
	u.SetExcluded(copilotquotasnapshot.FieldUnlimited)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.CopilotQuotaSnapshot.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *CopilotQuotaSnapshotUpsertOne) UpdateNewValues() *CopilotQuotaSnapshotUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(copilotquotasnapshot.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.CopilotQuotaSnapshot.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *CopilotQuotaSnapshotUpsertOne) Ignore() *CopilotQuotaSnapshotUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *CopilotQuotaSnapshotUpsertOne) DoNothing() *CopilotQuotaSnapshotUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the CopilotQuotaSnapshotCreate.OnConflict
// documentation for more info.
func (u *CopilotQuotaSnapshotUpsertOne) Update(set func(*CopilotQuotaSnapshotUpsert)) *CopilotQuotaSnapshotUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&CopilotQuotaSnapshotUpsert{UpdateSet: update})
	}))
	return u
}

// SetAccountID sets the "account_id" field.
func (u *CopilotQuotaSnapshotUpsertOne) SetAccountID(v int64) *CopilotQuotaSnapshotUpsertOne {
	return u.Update(func(s *CopilotQuotaSnapshotUpsert) {
		s.SetAccountID(v)
	})
}

// AddAccountID adds v to the "account_id" field.
func (u *CopilotQuotaSnapshotUpsertOne) AddAccountID(v int64) *CopilotQuotaSnapshotUpsertOne {
	return u.Update(func(s *CopilotQuotaSnapshotUpsert) {
		s.AddAccountID(v)
	})
}

// UpdateAccountID sets the "account_id" field to the value that was provided on create.
func (u *CopilotQuotaSnapshotUpsertOne) UpdateAccountID() *CopilotQuotaSnapshotUpsertOne {
	return u.Update(func(s *CopilotQuotaSnapshotUpsert) {
		s.UpdateAccountID()
	})
}

// SetSnapshotDate sets the "snapshot_date" field.
func (u *CopilotQuotaSnapshotUpsertOne) SetSnapshotDate(v time.Time) *CopilotQuotaSnapshotUpsertOne {
	return u.Update(func(s *CopilotQuotaSnapshotUpsert) {
		s.SetSnapshotDate(v)
	})
}

// UpdateSnapshotDate sets the "snapshot_date" field to the value that was provided on create.
func (u *CopilotQuotaSnapshotUpsertOne) UpdateSnapshotDate() *CopilotQuotaSnapshotUpsertOne {
	return u.Update(func(s *CopilotQuotaSnapshotUpsert) {
		s.UpdateSnapshotDate()
	})
}

// SetPlanType sets the "plan_type" field.
func (u *CopilotQuotaSnapshotUpsertOne) SetPlanType(v string) *CopilotQuotaSnapshotUpsertOne {
	return u.Update(func(s *CopilotQuotaSnapshotUpsert) {
		s.SetPlanType(v)
	})
}

// UpdatePlanType sets the "plan_type" field to the value that was provided on create.
func (u *CopilotQuotaSnapshotUpsertOne) UpdatePlanType() *CopilotQuotaSnapshotUpsertOne {
	return u.Update(func(s *CopilotQuotaSnapshotUpsert) {
		s.UpdatePlanType()
	})
}

// ClearPlanType clears the value of the "plan_type" field.
func (u *CopilotQuotaSnapshotUpsertOne) ClearPlanType() *CopilotQuotaSnapshotUpsertOne {
	return u.Update(func(s *CopilotQuotaSnapshotUpsert) {
		s.ClearPlanType()
	})
}

// SetPremiumEntitlement sets the "premium_entitlement" field.
func (u *CopilotQuotaSnapshotUpsertOne) SetPremiumEntitlement(v int) *CopilotQuotaSnapshotUpsertOne {
	return u.Update(func(s *CopilotQuotaSnapshotUpsert) {
		s.SetPremiumEntitlement(v)
	})
}

// AddPremiumEntitlement adds v to the "premium_entitlement" field.
func (u *CopilotQuotaSnapshotUpsertOne) AddPremiumEntitlement(v int) *CopilotQuotaSnapshotUpsertOne {
	return u.Update(func(s *CopilotQuotaSnapshotUpsert) {
		s.AddPremiumEntitlement(v)
	})
}

// UpdatePremiumEntitlement sets the "premium_entitlement" field to the value that was provided on create.
func (u *CopilotQuotaSnapshotUpsertOne) UpdatePremiumEntitlement() *CopilotQuotaSnapshotUpsertOne {
	return u.Update(func(s *CopilotQuotaSnapshotUpsert) {
		s.UpdatePremiumEntitlement()
	})
}

// SetPremiumRemaining sets the "premium_remaining" field.
func (u *CopilotQuotaSnapshotUpsertOne) SetPremiumRemaining(v int) *CopilotQuotaSnapshotUpsertOne {
	return u.Update(func(s *CopilotQuotaSnapshotUpsert) {
		s.SetPremiumRemaining(v)
	})
}

// AddPremiumRemaining adds v to the "premium_remaining" field.
func (u *CopilotQuotaSnapshotUpsertOne) AddPremiumRemaining(v int) *CopilotQuotaSnapshotUpsertOne {
	return u.Update(func(s *CopilotQuotaSnapshotUpsert) {
		s.AddPremiumRemaining(v)
	})
}

// UpdatePremiumRemaining sets the "premium_remaining" field to the value that was provided on create.
func (u *CopilotQuotaSnapshotUpsertOne) UpdatePremiumRemaining() *CopilotQuotaSnapshotUpsertOne {
	return u.Update(func(s *CopilotQuotaSnapshotUpsert) {
		s.UpdatePremiumRemaining()
	})
}

// SetPremiumUsed sets the "premium_used" field.
func (u *CopilotQuotaSnapshotUpsertOne) SetPremiumUsed(v int) *CopilotQuotaSnapshotUpsertOne {
	return u.Update(func(s *CopilotQuotaSnapshotUpsert) {
		s.SetPremiumUsed(v)
	})
}

// AddPremiumUsed adds v to the "premium_used" field.
func (u *CopilotQuotaSnapshotUpsertOne) AddPremiumUsed(v int) *CopilotQuotaSnapshotUpsertOne {
	return u.Update(func(s *CopilotQuotaSnapshotUpsert) {
		s.AddPremiumUsed(v)
	})
}

// UpdatePremiumUsed sets the "premium_used" field to the value that was provided on create.
func (u *CopilotQuotaSnapshotUpsertOne) UpdatePremiumUsed() *CopilotQuotaSnapshotUpsertOne {
	return u.Update(func(s *CopilotQuotaSnapshotUpsert) {
		s.UpdatePremiumUsed()
	})
}

// SetPremiumOverage sets the "premium_overage" field.
func (u *CopilotQuotaSnapshotUpsertOne) SetPremiumOverage(v int) *CopilotQuotaSnapshotUpsertOne {
	return u.Update(func(s *CopilotQuotaSnapshotUpsert) {
		s.SetPremiumOverage(v)
	})
}

// AddPremiumOverage adds v to the "premium_overage" field.
func (u *CopilotQuotaSnapshotUpsertOne) AddPremiumOverage(v int) *CopilotQuotaSnapshotUpsertOne {
	return u.Update(func(s *CopilotQuotaSnapshotUpsert) {
		s.AddPremiumOverage(v)
	})
}

// UpdatePremiumOverage sets the "premium_overage" field to the value that was provided on create.
func (u *CopilotQuotaSnapshotUpsertOne) UpdatePremiumOverage() *CopilotQuotaSnapshotUpsertOne {
	return u.Update(func(s *CopilotQuotaSnapshotUpsert) {
		s.UpdatePremiumOverage()
	})
}

// SetUnlimited sets the "unlimited" field.
func (u *CopilotQuotaSnapshotUpsertOne) SetUnlimited(v bool) *CopilotQuotaSnapshotUpsertOne {
	return u.Update(func(s *CopilotQuotaSnapshotUpsert) {
		s.SetUnlimited(v)
	})
}

// UpdateUnlimited sets the "unlimited" field to the value that was provided on create.
func (u *CopilotQuotaSnapshotUpsertOne) UpdateUnlimited() *CopilotQuotaSnapshotUpsertOne {
	return u.Update(func(s *CopilotQuotaSnapshotUpsert) {
		s.UpdateUnlimited()
	})
}

// Exec executes the query.
func (u *CopilotQuotaSnapshotUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for CopilotQuotaSnapshotCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *CopilotQuotaSnapshotUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *CopilotQuotaSnapshotUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *CopilotQuotaSnapshotUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// CopilotQuotaSnapshotCreateBulk is the builder for creating many CopilotQuotaSnapshot entities in bulk.
type CopilotQuotaSnapshotCreateBulk struct {
	config
	err      error
	builders []*CopilotQuotaSnapshotCreate
	conflict []sql.ConflictOption
}

// Save creates the CopilotQuotaSnapshot entities in the database.
func (_c *CopilotQuotaSnapshotCreateBulk) Save(ctx context.Context) ([]*CopilotQuotaSnapshot, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*CopilotQuotaSnapshot, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*CopilotQuotaSnapshotMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *CopilotQuotaSnapshotCreateBulk) SaveX(ctx context.Context) []*CopilotQuotaSnapshot {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *CopilotQuotaSnapshotCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *CopilotQuotaSnapshotCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.CopilotQuotaSnapshot.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.CopilotQuotaSnapshotUpsert) {
//			SetAccountID(v+v).
//		}).
//		Exec(ctx)
func (_c *CopilotQuotaSnapshotCreateBulk) OnConflict(opts ...sql.ConflictOption) *CopilotQuotaSnapshotUpsertBulk {
	_c.conflict = opts
	return &CopilotQuotaSnapshotUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.CopilotQuotaSnapshot.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *CopilotQuotaSnapshotCreateBulk) OnConflictColumns(columns ...string) *CopilotQuotaSnapshotUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &CopilotQuotaSnapshotUpsertBulk{
		create: _c,
	}
}

// CopilotQuotaSnapshotUpsertBulk is the builder for "upsert"-ing
// a bulk of CopilotQuotaSnapshot nodes.
type CopilotQuotaSnapshotUpsertBulk struct {
	create *CopilotQuotaSnapshotCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.CopilotQuotaSnapshot.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *CopilotQuotaSnapshotUpsertBulk) UpdateNewValues() *CopilotQuotaSnapshotUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(copilotquotasnapshot.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.CopilotQuotaSnapshot.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *CopilotQuotaSnapshotUpsertBulk) Ignore() *CopilotQuotaSnapshotUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *CopilotQuotaSnapshotUpsertBulk) DoNothing() *CopilotQuotaSnapshotUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the CopilotQuotaSnapshotCreateBulk.OnConflict
// documentation for more info.
func (u *CopilotQuotaSnapshotUpsertBulk) Update(set func(*CopilotQuotaSnapshotUpsert)) *CopilotQuotaSnapshotUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&CopilotQuotaSnapshotUpsert{UpdateSet: update})
	}))
	return u
}

// SetAccountID sets the "account_id" field.
func (u *CopilotQuotaSnapshotUpsertBulk) SetAccountID(v int64) *CopilotQuotaSnapshotUpsertBulk {
	return u.Update(func(s *CopilotQuotaSnapshotUpsert) {
		s.SetAccountID(v)
	})
}

// AddAccountID adds v to the "account_id" field.
func (u *CopilotQuotaSnapshotUpsertBulk) AddAccountID(v int64) *CopilotQuotaSnapshotUpsertBulk {
	return u.Update(func(s *CopilotQuotaSnapshotUpsert) {
		s.AddAccountID(v)
	})
}

// UpdateAccountID sets the "account_id" field to the value that was provided on create.
func (u *CopilotQuotaSnapshotUpsertBulk) UpdateAccountID() *CopilotQuotaSnapshotUpsertBulk {
	return u.Update(func(s *CopilotQuotaSnapshotUpsert) {
		s.UpdateAccountID()
	})
}

// SetSnapshotDate sets the "snapshot_date" field.
func (u *CopilotQuotaSnapshotUpsertBulk) SetSnapshotDate(v time.Time) *CopilotQuotaSnapshotUpsertBulk {
	return u.Update(func(s *CopilotQuotaSnapshotUpsert) {
		s.SetSnapshotDate(v)
	})
}

// UpdateSnapshotDate sets the "snapshot_date" field to the value that was provided on create.
func (u *CopilotQuotaSnapshotUpsertBulk) UpdateSnapshotDate() *CopilotQuotaSnapshotUpsertBulk {
	return u.Update(func(s *CopilotQuotaSnapshotUpsert) {
		s.UpdateSnapshotDate()
	})
}

// SetPlanType sets the "plan_type" field.
func (u *CopilotQuotaSnapshotUpsertBulk) SetPlanType(v string) *CopilotQuotaSnapshotUpsertBulk {
	return u.Update(func(s *CopilotQuotaSnapshotUpsert) {
		s.SetPlanType(v)
	})
}

// UpdatePlanType sets the "plan_type" field to the value that was provided on create.
func (u *CopilotQuotaSnapshotUpsertBulk) UpdatePlanType() *CopilotQuotaSnapshotUpsertBulk {
	return u.Update(func(s *CopilotQuotaSnapshotUpsert) {
		s.UpdatePlanType()
	})
}

// ClearPlanType clears the value of the "plan_type" field.
func (u *CopilotQuotaSnapshotUpsertBulk) ClearPlanType() *CopilotQuotaSnapshotUpsertBulk {
	return u.Update(func(s *CopilotQuotaSnapshotUpsert) {
		s.ClearPlanType()
	})
}

// SetPremiumEntitlement sets the "premium_entitlement" field.
func (u *CopilotQuotaSnapshotUpsertBulk) SetPremiumEntitlement(v int) *CopilotQuotaSnapshotUpsertBulk {
	return u.Update(func(s *CopilotQuotaSnapshotUpsert) {
		s.SetPremiumEntitlement(v)
	})
}

// AddPremiumEntitlement adds v to the "premium_entitlement" field.
func (u *CopilotQuotaSnapshotUpsertBulk) AddPremiumEntitlement(v int) *CopilotQuotaSnapshotUpsertBulk {
	return u.Update(func(s *CopilotQuotaSnapshotUpsert) {
		s.AddPremiumEntitlement(v)
	})
}

// UpdatePremiumEntitlement sets the "premium_entitlement" field to the value that was provided on create.
func (u *CopilotQuotaSnapshotUpsertBulk) UpdatePremiumEntitlement() *CopilotQuotaSnapshotUpsertBulk {
	return u.Update(func(s *CopilotQuotaSnapshotUpsert) {
		s.UpdatePremiumEntitlement()
	})
}

// SetPremiumRemaining sets the "premium_remaining" field.
func (u *CopilotQuotaSnapshotUpsertBulk) SetPremiumRemaining(v int) *CopilotQuotaSnapshotUpsertBulk {
	return u.Update(func(s *CopilotQuotaSnapshotUpsert) {
		s.SetPremiumRemaining(v)
	})
}

// AddPremiumRemaining adds v to the "premium_remaining" field.
func (u *CopilotQuotaSnapshotUpsertBulk) AddPremiumRemaining(v int) *CopilotQuotaSnapshotUpsertBulk {
	return u.Update(func(s *CopilotQuotaSnapshotUpsert) {
		s.AddPremiumRemaining(v)
	})
}

// UpdatePremiumRemaining sets the "premium_remaining" field to the value that was provided on create.
func (u *CopilotQuotaSnapshotUpsertBulk) UpdatePremiumRemaining() *CopilotQuotaSnapshotUpsertBulk {
	return u.Update(func(s *CopilotQuotaSnapshotUpsert) {
		s.UpdatePremiumRemaining()
	})
}

// SetPremiumUsed sets the "premium_used" field.
func (u *CopilotQuotaSnapshotUpsertBulk) SetPremiumUsed(v int) *CopilotQuotaSnapshotUpsertBulk {
	return u.Update(func(s *CopilotQuotaSnapshotUpsert) {
		s.SetPremiumUsed(v)
	})
}

// AddPremiumUsed adds v to the "premium_used" field.
func (u *CopilotQuotaSnapshotUpsertBulk) AddPremiumUsed(v int) *CopilotQuotaSnapshotUpsertBulk {
	return u.Update(func(s *CopilotQuotaSnapshotUpsert) {
		s.AddPremiumUsed(v)
	})
}

// UpdatePremiumUsed sets the "premium_used" field to the value that was provided on create.
func (u *CopilotQuotaSnapshotUpsertBulk) UpdatePremiumUsed() *CopilotQuotaSnapshotUpsertBulk {
	return u.Update(func(s *CopilotQuotaSnapshotUpsert) {
		s.UpdatePremiumUsed()
	})
}

// SetPremiumOverage sets the "premium_overage" field.
func (u *CopilotQuotaSnapshotUpsertBulk) SetPremiumOverage(v int) *CopilotQuotaSnapshotUpsertBulk {
	return u.Update(func(s *CopilotQuotaSnapshotUpsert) {
		s.SetPremiumOverage(v)
	})
}

// AddPremiumOverage adds v to the "premium_overage" field.
func (u *CopilotQuotaSnapshotUpsertBulk) AddPremiumOverage(v int) *CopilotQuotaSnapshotUpsertBulk {
	return u.Update(func(s *CopilotQuotaSnapshotUpsert) {
		s.AddPremiumOverage(v)
	})
}

// UpdatePremiumOverage sets the "premium_overage" field to the value that was provided on create.
func (u *CopilotQuotaSnapshotUpsertBulk) UpdatePremiumOverage() *CopilotQuotaSnapshotUpsertBulk {
	return u.Update(func(s *CopilotQuotaSnapshotUpsert) {
		s.UpdatePremiumOverage()
	})
}

// SetUnlimited sets the "unlimited" field.
func (u *CopilotQuotaSnapshotUpsertBulk) SetUnlimited(v bool) *CopilotQuotaSnapshotUpsertBulk {
	return u.Update(func(s *CopilotQuotaSnapshotUpsert) {
		s.SetUnlimited(v)
	})
}

// UpdateUnlimited sets the "unlimited" field to the value that was provided on create.
func (u *CopilotQuotaSnapshotUpsertBulk) UpdateUnlimited() *CopilotQuotaSnapshotUpsertBulk {
	return u.Update(func(s *CopilotQuotaSnapshotUpsert) {
		s.UpdateUnlimited()
	})
}

// Exec executes the query.
func (u *CopilotQuotaSnapshotUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the CopilotQuotaSnapshotCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for CopilotQuotaSnapshotCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *CopilotQuotaSnapshotUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
