// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/copilotquotasnapshot"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// CopilotQuotaSnapshotDelete is the builder for deleting a CopilotQuotaSnapshot entity.
type CopilotQuotaSnapshotDelete struct {
	config
	hooks    []Hook
	mutation *CopilotQuotaSnapshotMutation
}

// Where appends a list predicates to the CopilotQuotaSnapshotDelete builder.
func (_d *CopilotQuotaSnapshotDelete) Where(ps ...predicate.CopilotQuotaSnapshot) *CopilotQuotaSnapshotDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *CopilotQuotaSnapshotDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *CopilotQuotaSnapshotDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *CopilotQuotaSnapshotDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(copilotquotasnapshot.Table, sqlgraph.NewFieldSpec(copilotquotasnapshot.FieldID, field.TypeInt64))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// CopilotQuotaSnapshotDeleteOne is the builder for deleting a single CopilotQuotaSnapshot entity.
type CopilotQuotaSnapshotDeleteOne struct {
	_d *CopilotQuotaSnapshotDelete
}

// Where appends a list predicates to the CopilotQuotaSnapshotDelete builder.
func (_d *CopilotQuotaSnapshotDeleteOne) Where(ps ...predicate.CopilotQuotaSnapshot) *CopilotQuotaSnapshotDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *CopilotQuotaSnapshotDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{copilotquotasnapshot.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *CopilotQuotaSnapshotDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
