// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/copilotbudgetalert"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// CopilotBudgetAlertDelete is the builder for deleting a CopilotBudgetAlert entity.
type CopilotBudgetAlertDelete struct {
	config
	hooks    []Hook
	mutation *CopilotBudgetAlertMutation
}

// Where appends a list predicates to the CopilotBudgetAlertDelete builder.
func (_d *CopilotBudgetAlertDelete) Where(ps ...predicate.CopilotBudgetAlert) *CopilotBudgetAlertDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *CopilotBudgetAlertDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *CopilotBudgetAlertDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *CopilotBudgetAlertDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(copilotbudgetalert.Table, sqlgraph.NewFieldSpec(copilotbudgetalert.FieldID, field.TypeInt64))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// CopilotBudgetAlertDeleteOne is the builder for deleting a single CopilotBudgetAlert entity.
type CopilotBudgetAlertDeleteOne struct {
	_d *CopilotBudgetAlertDelete
}

// Where appends a list predicates to the CopilotBudgetAlertDelete builder.
func (_d *CopilotBudgetAlertDeleteOne) Where(ps ...predicate.CopilotBudgetAlert) *CopilotBudgetAlertDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *CopilotBudgetAlertDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{copilotbudgetalert.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *CopilotBudgetAlertDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
