// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/copilotbudgetalert"
)

// CopilotBudgetAlertCreate is the builder for creating a CopilotBudgetAlert entity.
type CopilotBudgetAlertCreate struct {
	config
	mutation *CopilotBudgetAlertMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreatedAt sets the "created_at" field.
func (_c *CopilotBudgetAlertCreate) SetCreatedAt(v time.Time) *CopilotBudgetAlertCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *CopilotBudgetAlertCreate) SetNillableCreatedAt(v *time.Time) *CopilotBudgetAlertCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *CopilotBudgetAlertCreate) SetUpdatedAt(v time.Time) *CopilotBudgetAlertCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *CopilotBudgetAlertCreate) SetNillableUpdatedAt(v *time.Time) *CopilotBudgetAlertCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetAccountID sets the "account_id" field.
func (_c *CopilotBudgetAlertCreate) SetAccountID(v int64) *CopilotBudgetAlertCreate {
	_c.mutation.SetAccountID(v)
	return _c
}

// SetMonthlyBudget sets the "monthly_budget" field.
func (_c *CopilotBudgetAlertCreate) SetMonthlyBudget(v float64) *CopilotBudgetAlertCreate {
	_c.mutation.SetMonthlyBudget(v)
	return _c
}

// SetNillableMonthlyBudget sets the "monthly_budget" field if the given value is not nil.
func (_c *CopilotBudgetAlertCreate) SetNillableMonthlyBudget(v *float64) *CopilotBudgetAlertCreate {
	if v != nil {
		_c.SetMonthlyBudget(*v)
	}
	return _c
}

// SetAlertThreshold sets the "alert_threshold" field.
func (_c *CopilotBudgetAlertCreate) SetAlertThreshold(v int) *CopilotBudgetAlertCreate {
	_c.mutation.SetAlertThreshold(v)
	return _c
}

// SetNillableAlertThreshold sets the "alert_threshold" field if the given value is not nil.
func (_c *CopilotBudgetAlertCreate) SetNillableAlertThreshold(v *int) *CopilotBudgetAlertCreate {
	if v != nil {
		_c.SetAlertThreshold(*v)
	}
	return _c
}

// SetEnabled sets the "enabled" field.
func (_c *CopilotBudgetAlertCreate) SetEnabled(v bool) *CopilotBudgetAlertCreate {
	_c.mutation.SetEnabled(v)
	return _c
}

// SetNillableEnabled sets the "enabled" field if the given value is not nil.
func (_c *CopilotBudgetAlertCreate) SetNillableEnabled(v *bool) *CopilotBudgetAlertCreate {
	if v != nil {
		_c.SetEnabled(*v)
	}
	return _c
}

// SetLastAlertedAt sets the "last_alerted_at" field.
func (_c *CopilotBudgetAlertCreate) SetLastAlertedAt(v time.Time) *CopilotBudgetAlertCreate {
	_c.mutation.SetLastAlertedAt(v)
	return _c
}

// SetNillableLastAlertedAt sets the "last_alerted_at" field if the given value is not nil.
func (_c *CopilotBudgetAlertCreate) SetNillableLastAlertedAt(v *time.Time) *CopilotBudgetAlertCreate {
	if v != nil {
		_c.SetLastAlertedAt(*v)
	}
	return _c
}

// Mutation returns the CopilotBudgetAlertMutation object of the builder.
func (_c *CopilotBudgetAlertCreate) Mutation() *CopilotBudgetAlertMutation {
	return _c.mutation
}

// Save creates the CopilotBudgetAlert in the database.
func (_c *CopilotBudgetAlertCreate) Save(ctx context.Context) (*CopilotBudgetAlert, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *CopilotBudgetAlertCreate) SaveX(ctx context.Context) *CopilotBudgetAlert {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *CopilotBudgetAlertCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *CopilotBudgetAlertCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *CopilotBudgetAlertCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := copilotbudgetalert.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := copilotbudgetalert.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.MonthlyBudget(); !ok {
		v := copilotbudgetalert.DefaultMonthlyBudget
		_c.mutation.SetMonthlyBudget(v)
	}
	if _, ok := _c.mutation.AlertThreshold(); !ok {
		v := copilotbudgetalert.DefaultAlertThreshold
		_c.mutation.SetAlertThreshold(v)
	}
	if _, ok := _c.mutation.Enabled(); !ok {
		v := copilotbudgetalert.DefaultEnabled
		_c.mutation.SetEnabled(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *CopilotBudgetAlertCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "CopilotBudgetAlert.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "CopilotBudgetAlert.updated_at"`)}
	}
	if _, ok := _c.mutation.AccountID(); !ok {
		return &ValidationError{Name: "account_id", err: errors.New(`ent: missing required field "CopilotBudgetAlert.account_id"`)}
	}
	if _, ok := _c.mutation.MonthlyBudget(); !ok {
		return &ValidationError{Name: "monthly_budget", err: errors.New(`ent: missing required field "CopilotBudgetAlert.monthly_budget"`)}
	}
	if _, ok := _c.mutation.AlertThreshold(); !ok {
		return &ValidationError{Name: "alert_threshold", err: errors.New(`ent: missing required field "CopilotBudgetAlert.alert_threshold"`)}
	}
	if _, ok := _c.mutation.Enabled(); !ok {
		return &ValidationError{Name: "enabled", err: errors.New(`ent: missing required field "CopilotBudgetAlert.enabled"`)}
	}
	return nil
}

func (_c *CopilotBudgetAlertCreate) sqlSave(ctx context.Context) (*CopilotBudgetAlert, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *CopilotBudgetAlertCreate) createSpec() (*CopilotBudgetAlert, *sqlgraph.CreateSpec) {
	var (
		_node = &CopilotBudgetAlert{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(copilotbudgetalert.Table, sqlgraph.NewFieldSpec(copilotbudgetalert.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(copilotbudgetalert.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(copilotbudgetalert.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.AccountID(); ok {
		_spec.SetField(copilotbudgetalert.FieldAccountID, field.TypeInt64, value)
		_node.AccountID = value
	}
	if value, ok := _c.mutation.MonthlyBudget(); ok {
		_spec.SetField(copilotbudgetalert.FieldMonthlyBudget, field.TypeFloat64, value)
		_node.MonthlyBudget = value
	}
	if value, ok := _c.mutation.AlertThreshold(); ok {
		_spec.SetField(copilotbudgetalert.FieldAlertThreshold, field.TypeInt, value)
		_node.AlertThreshold = value
	}
	if value, ok := _c.mutation.Enabled(); ok {
		_spec.SetField(copilotbudgetalert.FieldEnabled, field.TypeBool, value)
		_node.Enabled = value
	}
	if value, ok := _c.mutation.LastAlertedAt(); ok {
		_spec.SetField(copilotbudgetalert.FieldLastAlertedAt, field.TypeTime, value)
		_node.LastAlertedAt = &value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.CopilotBudgetAlert.Create().
//		SetCreatedAt(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.CopilotBudgetAlertUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *CopilotBudgetAlertCreate) OnConflict(opts ...sql.ConflictOption) *CopilotBudgetAlertUpsertOne {
	_c.conflict = opts
	return &CopilotBudgetAlertUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.CopilotBudgetAlert.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *CopilotBudgetAlertCreate) OnConflictColumns(columns ...string) *CopilotBudgetAlertUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &CopilotBudgetAlertUpsertOne{
		create: _c,
	}
}

type (
	// CopilotBudgetAlertUpsertOne is the builder for "upsert"-ing
	//  one CopilotBudgetAlert node.
	CopilotBudgetAlertUpsertOne struct {
		create *CopilotBudgetAlertCreate
	}

	// CopilotBudgetAlertUpsert is the "OnConflict" setter.
	CopilotBudgetAlertUpsert struct {
		*sql.UpdateSet
	}
)

// SetUpdatedAt sets the "updated_at" field.
func (u *CopilotBudgetAlertUpsert) SetUpdatedAt(v time.Time) *CopilotBudgetAlertUpsert {
	u.Set(copilotbudgetalert.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *CopilotBudgetAlertUpsert) UpdateUpdatedAt() *CopilotBudgetAlertUpsert {
	u.SetExcluded(copilotbudgetalert.FieldUpdatedAt)
	return u
}

// SetAccountID sets the "account_id" field.
func (u *CopilotBudgetAlertUpsert) SetAccountID(v int64) *CopilotBudgetAlertUpsert {
	u.Set(copilotbudgetalert.FieldAccountID, v)
	return u
}

// UpdateAccountID sets the "account_id" field to the value that was provided on create.
func (u *CopilotBudgetAlertUpsert) UpdateAccountID() *CopilotBudgetAlertUpsert {
	u.SetExcluded(copilotbudgetalert.FieldAccountID)
	return u
}

// AddAccountID adds v to the "account_id" field.
func (u *CopilotBudgetAlertUpsert) AddAccountID(v int64) *CopilotBudgetAlertUpsert {
	u.Add(copilotbudgetalert.FieldAccountID, v)
	return u
}

// SetMonthlyBudget sets the "monthly_budget" field.
func (u *CopilotBudgetAlertUpsert) SetMonthlyBudget(v float64) *CopilotBudgetAlertUpsert {
	u.Set(copilotbudgetalert.FieldMonthlyBudget, v)
	return u
}

// UpdateMonthlyBudget sets the "monthly_budget" field to the value that was provided on create.
func (u *CopilotBudgetAlertUpsert) UpdateMonthlyBudget() *CopilotBudgetAlertUpsert {
	u.SetExcluded(copilotbudgetalert.FieldMonthlyBudget)
	return u
}

// AddMonthlyBudget adds v to the "monthly_budget" field.
func (u *CopilotBudgetAlertUpsert) AddMonthlyBudget(v float64) *CopilotBudgetAlertUpsert {
	u.Add(copilotbudgetalert.FieldMonthlyBudget, v)
	return u
}

// SetAlertThreshold sets the "alert_threshold" field.
func (u *CopilotBudgetAlertUpsert) SetAlertThreshold(v int) *CopilotBudgetAlertUpsert {
	u.Set(copilotbudgetalert.FieldAlertThreshold, v)
	return u
}

// UpdateAlertThreshold sets the "alert_threshold" field to the value that was provided on create.
func (u *CopilotBudgetAlertUpsert) UpdateAlertThreshold() *CopilotBudgetAlertUpsert {
	u.SetExcluded(copilotbudgetalert.FieldAlertThreshold)
	return u
}

// AddAlertThreshold adds v to the "alert_threshold" field.
func (u *CopilotBudgetAlertUpsert) AddAlertThreshold(v int) *CopilotBudgetAlertUpsert {
	u.Add(copilotbudgetalert.FieldAlertThreshold, v)
	return u
}

// SetEnabled sets the "enabled" field.
func (u *CopilotBudgetAlertUpsert) SetEnabled(v bool) *CopilotBudgetAlertUpsert {
	u.Set(copilotbudgetalert.FieldEnabled, v)
	return u
}

// UpdateEnabled sets the "enabled" field to the value that was provided on create.
func (u *CopilotBudgetAlertUpsert) UpdateEnabled() *CopilotBudgetAlertUpsert {
	u.SetExcluded(copilotbudgetalert.FieldEnabled)
	return u
}

// SetLastAlertedAt sets the "last_alerted_at" field.
func (u *CopilotBudgetAlertUpsert) SetLastAlertedAt(v time.Time) *CopilotBudgetAlertUpsert {
	u.Set(copilotbudgetalert.FieldLastAlertedAt, v)
	return u
}

// UpdateLastAlertedAt sets the "last_alerted_at" field to the value that was provided on create.
func (u *CopilotBudgetAlertUpsert) UpdateLastAlertedAt() *CopilotBudgetAlertUpsert {
	u.SetExcluded(copilotbudgetalert.FieldLastAlertedAt)
	return u
}

// ClearLastAlertedAt clears the value of the "last_alerted_at" field.
func (u *CopilotBudgetAlertUpsert) ClearLastAlertedAt() *CopilotBudgetAlertUpsert {
	u.SetNull(copilotbudgetalert.FieldLastAlertedAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.CopilotBudgetAlert.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *CopilotBudgetAlertUpsertOne) UpdateNewValues() *CopilotBudgetAlertUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(copilotbudgetalert.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.CopilotBudgetAlert.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *CopilotBudgetAlertUpsertOne) Ignore() *CopilotBudgetAlertUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *CopilotBudgetAlertUpsertOne) DoNothing() *CopilotBudgetAlertUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the CopilotBudgetAlertCreate.OnConflict
// documentation for more info.
func (u *CopilotBudgetAlertUpsertOne) Update(set func(*CopilotBudgetAlertUpsert)) *CopilotBudgetAlertUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&CopilotBudgetAlertUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *CopilotBudgetAlertUpsertOne) SetUpdatedAt(v time.Time) *CopilotBudgetAlertUpsertOne {
	return u.Update(func(s *CopilotBudgetAlertUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *CopilotBudgetAlertUpsertOne) UpdateUpdatedAt() *CopilotBudgetAlertUpsertOne {
	return u.Update(func(s *CopilotBudgetAlertUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetAccountID sets the "account_id" field.
func (u *CopilotBudgetAlertUpsertOne) SetAccountID(v int64) *CopilotBudgetAlertUpsertOne {
	return u.Update(func(s *CopilotBudgetAlertUpsert) {
		s.SetAccountID(v)
	})
}

// AddAccountID adds v to the "account_id" field.
func (u *CopilotBudgetAlertUpsertOne) AddAccountID(v int64) *CopilotBudgetAlertUpsertOne {
	return u.Update(func(s *CopilotBudgetAlertUpsert) {
		s.AddAccountID(v)
	})
}

// UpdateAccountID sets the "account_id" field to the value that was provided on create.
func (u *CopilotBudgetAlertUpsertOne) UpdateAccountID() *CopilotBudgetAlertUpsertOne {
	return u.Update(func(s *CopilotBudgetAlertUpsert) {
		s.UpdateAccountID()
	})
}

// SetMonthlyBudget sets the "monthly_budget" field.
func (u *CopilotBudgetAlertUpsertOne) SetMonthlyBudget(v float64) *CopilotBudgetAlertUpsertOne {
	return u.Update(func(s *CopilotBudgetAlertUpsert) {
		s.SetMonthlyBudget(v)
	})
}

// AddMonthlyBudget adds v to the "monthly_budget" field.
func (u *CopilotBudgetAlertUpsertOne) AddMonthlyBudget(v float64) *CopilotBudgetAlertUpsertOne {
	return u.Update(func(s *CopilotBudgetAlertUpsert) {
		s.AddMonthlyBudget(v)
	})
}

// UpdateMonthlyBudget sets the "monthly_budget" field to the value that was provided on create.
func (u *CopilotBudgetAlertUpsertOne) UpdateMonthlyBudget() *CopilotBudgetAlertUpsertOne {
	return u.Update(func(s *CopilotBudgetAlertUpsert) {
		s.UpdateMonthlyBudget()
	})
}

// SetAlertThreshold sets the "alert_threshold" field.
func (u *CopilotBudgetAlertUpsertOne) SetAlertThreshold(v int) *CopilotBudgetAlertUpsertOne {
	return u.Update(func(s *CopilotBudgetAlertUpsert) {
		s.SetAlertThreshold(v)
	})
}

// AddAlertThreshold adds v to the "alert_threshold" field.
func (u *CopilotBudgetAlertUpsertOne) AddAlertThreshold(v int) *CopilotBudgetAlertUpsertOne {
	return u.Update(func(s *CopilotBudgetAlertUpsert) {
		s.AddAlertThreshold(v)
	})
}

// UpdateAlertThreshold sets the "alert_threshold" field to the value that was provided on create.
func (u *CopilotBudgetAlertUpsertOne) UpdateAlertThreshold() *CopilotBudgetAlertUpsertOne {
	return u.Update(func(s *CopilotBudgetAlertUpsert) {
		s.UpdateAlertThreshold()
	})
}

// SetEnabled sets the "enabled" field.
func (u *CopilotBudgetAlertUpsertOne) SetEnabled(v bool) *CopilotBudgetAlertUpsertOne {
	return u.Update(func(s *CopilotBudgetAlertUpsert) {
		s.SetEnabled(v)
	})
}

// UpdateEnabled sets the "enabled" field to the value that was provided on create.
func (u *CopilotBudgetAlertUpsertOne) UpdateEnabled() *CopilotBudgetAlertUpsertOne {
	return u.Update(func(s *CopilotBudgetAlertUpsert) {
		s.UpdateEnabled()
	})
}

// SetLastAlertedAt sets the "last_alerted_at" field.
func (u *CopilotBudgetAlertUpsertOne) SetLastAlertedAt(v time.Time) *CopilotBudgetAlertUpsertOne {
	return u.Update(func(s *CopilotBudgetAlertUpsert) {
		s.SetLastAlertedAt(v)
	})
}

// UpdateLastAlertedAt sets the "last_alerted_at" field to the value that was provided on create.
func (u *CopilotBudgetAlertUpsertOne) UpdateLastAlertedAt() *CopilotBudgetAlertUpsertOne {
	return u.Update(func(s *CopilotBudgetAlertUpsert) {
		s.UpdateLastAlertedAt()
	})
}

// ClearLastAlertedAt clears the value of the "last_alerted_at" field.
func (u *CopilotBudgetAlertUpsertOne) ClearLastAlertedAt() *CopilotBudgetAlertUpsertOne {
	return u.Update(func(s *CopilotBudgetAlertUpsert) {
		s.ClearLastAlertedAt()
	})
}

// Exec executes the query.
func (u *CopilotBudgetAlertUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for CopilotBudgetAlertCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *CopilotBudgetAlertUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *CopilotBudgetAlertUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *CopilotBudgetAlertUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// CopilotBudgetAlertCreateBulk is the builder for creating many CopilotBudgetAlert entities in bulk.
type CopilotBudgetAlertCreateBulk struct {
	config
	err      error
	builders []*CopilotBudgetAlertCreate
	conflict []sql.ConflictOption
}

// Save creates the CopilotBudgetAlert entities in the database.
func (_c *CopilotBudgetAlertCreateBulk) Save(ctx context.Context) ([]*CopilotBudgetAlert, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*CopilotBudgetAlert, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*CopilotBudgetAlertMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *CopilotBudgetAlertCreateBulk) SaveX(ctx context.Context) []*CopilotBudgetAlert {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *CopilotBudgetAlertCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *CopilotBudgetAlertCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.CopilotBudgetAlert.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.CopilotBudgetAlertUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *CopilotBudgetAlertCreateBulk) OnConflict(opts ...sql.ConflictOption) *CopilotBudgetAlertUpsertBulk {
	_c.conflict = opts
	return &CopilotBudgetAlertUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.CopilotBudgetAlert.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *CopilotBudgetAlertCreateBulk) OnConflictColumns(columns ...string) *CopilotBudgetAlertUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &CopilotBudgetAlertUpsertBulk{
		create: _c,
	}
}

// CopilotBudgetAlertUpsertBulk is the builder for "upsert"-ing
// a bulk of CopilotBudgetAlert nodes.
type CopilotBudgetAlertUpsertBulk struct {
	create *CopilotBudgetAlertCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.CopilotBudgetAlert.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *CopilotBudgetAlertUpsertBulk) UpdateNewValues() *CopilotBudgetAlertUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(copilotbudgetalert.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.CopilotBudgetAlert.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *CopilotBudgetAlertUpsertBulk) Ignore() *CopilotBudgetAlertUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *CopilotBudgetAlertUpsertBulk) DoNothing() *CopilotBudgetAlertUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the CopilotBudgetAlertCreateBulk.OnConflict
// documentation for more info.
func (u *CopilotBudgetAlertUpsertBulk) Update(set func(*CopilotBudgetAlertUpsert)) *CopilotBudgetAlertUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&CopilotBudgetAlertUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *CopilotBudgetAlertUpsertBulk) SetUpdatedAt(v time.Time) *CopilotBudgetAlertUpsertBulk {
	return u.Update(func(s *CopilotBudgetAlertUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *CopilotBudgetAlertUpsertBulk) UpdateUpdatedAt() *CopilotBudgetAlertUpsertBulk {
	return u.Update(func(s *CopilotBudgetAlertUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetAccountID sets the "account_id" field.
func (u *CopilotBudgetAlertUpsertBulk) SetAccountID(v int64) *CopilotBudgetAlertUpsertBulk {
	return u.Update(func(s *CopilotBudgetAlertUpsert) {
		s.SetAccountID(v)
	})
}

// AddAccountID adds v to the "account_id" field.
func (u *CopilotBudgetAlertUpsertBulk) AddAccountID(v int64) *CopilotBudgetAlertUpsertBulk {
	return u.Update(func(s *CopilotBudgetAlertUpsert) {
		s.AddAccountID(v)
	})
}

// UpdateAccountID sets the "account_id" field to the value that was provided on create.
func (u *CopilotBudgetAlertUpsertBulk) UpdateAccountID() *CopilotBudgetAlertUpsertBulk {
	return u.Update(func(s *CopilotBudgetAlertUpsert) {
		s.UpdateAccountID()
	})
}

// SetMonthlyBudget sets the "monthly_budget" field.
func (u *CopilotBudgetAlertUpsertBulk) SetMonthlyBudget(v float64) *CopilotBudgetAlertUpsertBulk {
	return u.Update(func(s *CopilotBudgetAlertUpsert) {
		s.SetMonthlyBudget(v)
	})
}

// AddMonthlyBudget adds v to the "monthly_budget" field.
func (u *CopilotBudgetAlertUpsertBulk) AddMonthlyBudget(v float64) *CopilotBudgetAlertUpsertBulk {
	return u.Update(func(s *CopilotBudgetAlertUpsert) {
		s.AddMonthlyBudget(v)
	})
}

// UpdateMonthlyBudget sets the "monthly_budget" field to the value that was provided on create.
func (u *CopilotBudgetAlertUpsertBulk) UpdateMonthlyBudget() *CopilotBudgetAlertUpsertBulk {
	return u.Update(func(s *CopilotBudgetAlertUpsert) {
		s.UpdateMonthlyBudget()
	})
}

// SetAlertThreshold sets the "alert_threshold" field.
func (u *CopilotBudgetAlertUpsertBulk) SetAlertThreshold(v int) *CopilotBudgetAlertUpsertBulk {
	return u.Update(func(s *CopilotBudgetAlertUpsert) {
		s.SetAlertThreshold(v)
	})
}

// AddAlertThreshold adds v to the "alert_threshold" field.
func (u *CopilotBudgetAlertUpsertBulk) AddAlertThreshold(v int) *CopilotBudgetAlertUpsertBulk {
	return u.Update(func(s *CopilotBudgetAlertUpsert) {
		s.AddAlertThreshold(v)
	})
}

// UpdateAlertThreshold sets the "alert_threshold" field to the value that was provided on create.
func (u *CopilotBudgetAlertUpsertBulk) UpdateAlertThreshold() *CopilotBudgetAlertUpsertBulk {
	return u.Update(func(s *CopilotBudgetAlertUpsert) {
		s.UpdateAlertThreshold()
	})
}

// SetEnabled sets the "enabled" field.
func (u *CopilotBudgetAlertUpsertBulk) SetEnabled(v bool) *CopilotBudgetAlertUpsertBulk {
	return u.Update(func(s *CopilotBudgetAlertUpsert) {
		s.SetEnabled(v)
	})
}

// UpdateEnabled sets the "enabled" field to the value that was provided on create.
func (u *CopilotBudgetAlertUpsertBulk) UpdateEnabled() *CopilotBudgetAlertUpsertBulk {
	return u.Update(func(s *CopilotBudgetAlertUpsert) {
		s.UpdateEnabled()
	})
}

// SetLastAlertedAt sets the "last_alerted_at" field.
func (u *CopilotBudgetAlertUpsertBulk) SetLastAlertedAt(v time.Time) *CopilotBudgetAlertUpsertBulk {
	return u.Update(func(s *CopilotBudgetAlertUpsert) {
		s.SetLastAlertedAt(v)
	})
}

// UpdateLastAlertedAt sets the "last_alerted_at" field to the value that was provided on create.
func (u *CopilotBudgetAlertUpsertBulk) UpdateLastAlertedAt() *CopilotBudgetAlertUpsertBulk {
	return u.Update(func(s *CopilotBudgetAlertUpsert) {
		s.UpdateLastAlertedAt()
	})
}

// ClearLastAlertedAt clears the value of the "last_alerted_at" field.
func (u *CopilotBudgetAlertUpsertBulk) ClearLastAlertedAt() *CopilotBudgetAlertUpsertBulk {
	return u.Update(func(s *CopilotBudgetAlertUpsert) {
		s.ClearLastAlertedAt()
	})
}

// Exec executes the query.
func (u *CopilotBudgetAlertUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the CopilotBudgetAlertCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for CopilotBudgetAlertCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *CopilotBudgetAlertUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
