// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/copilotquotasnapshot"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// CopilotQuotaSnapshotUpdate is the builder for updating CopilotQuotaSnapshot entities.
type CopilotQuotaSnapshotUpdate struct {
	config
	hooks    []Hook
	mutation *CopilotQuotaSnapshotMutation
}

// Where appends a list predicates to the CopilotQuotaSnapshotUpdate builder.
func (_u *CopilotQuotaSnapshotUpdate) Where(ps ...predicate.CopilotQuotaSnapshot) *CopilotQuotaSnapshotUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetAccountID sets the "account_id" field.
func (_u *CopilotQuotaSnapshotUpdate) SetAccountID(v int64) *CopilotQuotaSnapshotUpdate {
	_u.mutation.ResetAccountID()
	_u.mutation.SetAccountID(v)
	return _u
}

// SetNillableAccountID sets the "account_id" field if the given value is not nil.
func (_u *CopilotQuotaSnapshotUpdate) SetNillableAccountID(v *int64) *CopilotQuotaSnapshotUpdate {
	if v != nil {
		_u.SetAccountID(*v)
	}
	return _u
}

// AddAccountID adds value to the "account_id" field.
func (_u *CopilotQuotaSnapshotUpdate) AddAccountID(v int64) *CopilotQuotaSnapshotUpdate {
	_u.mutation.AddAccountID(v)
	return _u
}

// SetSnapshotDate sets the "snapshot_date" field.
func (_u *CopilotQuotaSnapshotUpdate) SetSnapshotDate(v time.Time) *CopilotQuotaSnapshotUpdate {
	_u.mutation.SetSnapshotDate(v)
	return _u
}

// SetNillableSnapshotDate sets the "snapshot_date" field if the given value is not nil.
func (_u *CopilotQuotaSnapshotUpdate) SetNillableSnapshotDate(v *time.Time) *CopilotQuotaSnapshotUpdate {
	if v != nil {
		_u.SetSnapshotDate(*v)
	}
	return _u
}

// SetPlanType sets the "plan_type" field.
func (_u *CopilotQuotaSnapshotUpdate) SetPlanType(v string) *CopilotQuotaSnapshotUpdate {
	_u.mutation.SetPlanType(v)
	return _u
}

// SetNillablePlanType sets the "plan_type" field if the given value is not nil.
func (_u *CopilotQuotaSnapshotUpdate) SetNillablePlanType(v *string) *CopilotQuotaSnapshotUpdate {
	if v != nil {
		_u.SetPlanType(*v)
	}
	return _u
}

// ClearPlanType clears the value of the "plan_type" field.
func (_u *CopilotQuotaSnapshotUpdate) ClearPlanType() *CopilotQuotaSnapshotUpdate {
	_u.mutation.ClearPlanType()
	return _u
}

// SetPremiumEntitlement sets the "premium_entitlement" field.
func (_u *CopilotQuotaSnapshotUpdate) SetPremiumEntitlement(v int) *CopilotQuotaSnapshotUpdate {
	_u.mutation.ResetPremiumEntitlement()
	_u.mutation.SetPremiumEntitlement(v)
	return _u
}

// SetNillablePremiumEntitlement sets the "premium_entitlement" field if the given value is not nil.
func (_u *CopilotQuotaSnapshotUpdate) SetNillablePremiumEntitlement(v *int) *CopilotQuotaSnapshotUpdate {
	if v != nil {
		_u.SetPremiumEntitlement(*v)
	}
	return _u
}

// AddPremiumEntitlement adds value to the "premium_entitlement" field.
func (_u *CopilotQuotaSnapshotUpdate) AddPremiumEntitlement(v int) *CopilotQuotaSnapshotUpdate {
	_u.mutation.AddPremiumEntitlement(v)
	return _u
}

// SetPremiumRemaining sets the "premium_remaining" field.
func (_u *CopilotQuotaSnapshotUpdate) SetPremiumRemaining(v int) *CopilotQuotaSnapshotUpdate {
	_u.mutation.ResetPremiumRemaining()
	_u.mutation.SetPremiumRemaining(v)
	return _u
}

// SetNillablePremiumRemaining sets the "premium_remaining" field if the given value is not nil.
func (_u *CopilotQuotaSnapshotUpdate) SetNillablePremiumRemaining(v *int) *CopilotQuotaSnapshotUpdate {
	if v != nil {
		_u.SetPremiumRemaining(*v)
	}
	return _u
}

// AddPremiumRemaining adds value to the "premium_remaining" field.
func (_u *CopilotQuotaSnapshotUpdate) AddPremiumRemaining(v int) *CopilotQuotaSnapshotUpdate {
	_u.mutation.AddPremiumRemaining(v)
	return _u
}

// SetPremiumUsed sets the "premium_used" field.
func (_u *CopilotQuotaSnapshotUpdate) SetPremiumUsed(v int) *CopilotQuotaSnapshotUpdate {
	_u.mutation.ResetPremiumUsed()
	_u.mutation.SetPremiumUsed(v)
	return _u
}

// SetNillablePremiumUsed sets the "premium_used" field if the given value is not nil.
func (_u *CopilotQuotaSnapshotUpdate) SetNillablePremiumUsed(v *int) *CopilotQuotaSnapshotUpdate {
	if v != nil {
		_u.SetPremiumUsed(*v)
	}
	return _u
}

// AddPremiumUsed adds value to the "premium_used" field.
func (_u *CopilotQuotaSnapshotUpdate) AddPremiumUsed(v int) *CopilotQuotaSnapshotUpdate {
	_u.mutation.AddPremiumUsed(v)
	return _u
}

// SetPremiumOverage sets the "premium_overage" field.
func (_u *CopilotQuotaSnapshotUpdate) SetPremiumOverage(v int) *CopilotQuotaSnapshotUpdate {
	_u.mutation.ResetPremiumOverage()
	_u.mutation.SetPremiumOverage(v)
	return _u
}

// SetNillablePremiumOverage sets the "premium_overage" field if the given value is not nil.
func (_u *CopilotQuotaSnapshotUpdate) SetNillablePremiumOverage(v *int) *CopilotQuotaSnapshotUpdate {
	if v != nil {
		_u.SetPremiumOverage(*v)
	}
	return _u
}

// AddPremiumOverage adds value to the "premium_overage" field.
func (_u *CopilotQuotaSnapshotUpdate) AddPremiumOverage(v int) *CopilotQuotaSnapshotUpdate {
	_u.mutation.AddPremiumOverage(v)
	return _u
}

// SetUnlimited sets the "unlimited" field.
func (_u *CopilotQuotaSnapshotUpdate) SetUnlimited(v bool) *CopilotQuotaSnapshotUpdate {
	_u.mutation.SetUnlimited(v)
	return _u
}

// SetNillableUnlimited sets the "unlimited" field if the given value is not nil.
func (_u *CopilotQuotaSnapshotUpdate) SetNillableUnlimited(v *bool) *CopilotQuotaSnapshotUpdate {
	if v != nil {
		_u.SetUnlimited(*v)
	}
	return _u
}

// Mutation returns the CopilotQuotaSnapshotMutation object of the builder.
func (_u *CopilotQuotaSnapshotUpdate) Mutation() *CopilotQuotaSnapshotMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *CopilotQuotaSnapshotUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *CopilotQuotaSnapshotUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *CopilotQuotaSnapshotUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *CopilotQuotaSnapshotUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *CopilotQuotaSnapshotUpdate) check() error {
	if v, ok := _u.mutation.PlanType(); ok {
		if err := copilotquotasnapshot.PlanTypeValidator(v); err != nil {
			return &ValidationError{Name: "plan_type", err: fmt.Errorf(`ent: validator failed for field "CopilotQuotaSnapshot.plan_type": %w`, err)}
		}
	}
	return nil
}

func (_u *CopilotQuotaSnapshotUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(copilotquotasnapshot.Table, copilotquotasnapshot.Columns, sqlgraph.NewFieldSpec(copilotquotasnapshot.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.AccountID(); ok {
		_spec.SetField(copilotquotasnapshot.FieldAccountID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedAccountID(); ok {
		_spec.AddField(copilotquotasnapshot.FieldAccountID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.SnapshotDate(); ok {
		_spec.SetField(copilotquotasnapshot.FieldSnapshotDate, field.TypeTime, value)
	}
	if value, ok := _u.mutation.PlanType(); ok {
		_spec.SetField(copilotquotasnapshot.FieldPlanType, field.TypeString, value)
	}
	if _u.mutation.PlanTypeCleared() {
		_spec.ClearField(copilotquotasnapshot.FieldPlanType, field.TypeString)
	}
	if value, ok := _u.mutation.PremiumEntitlement(); ok {
		_spec.SetField(copilotquotasnapshot.FieldPremiumEntitlement, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedPremiumEntitlement(); ok {
		_spec.AddField(copilotquotasnapshot.FieldPremiumEntitlement, field.TypeInt, value)
	}
	if value, ok := _u.mutation.PremiumRemaining(); ok {
		_spec.SetField(copilotquotasnapshot.FieldPremiumRemaining, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedPremiumRemaining(); ok {
		_spec.AddField(copilotquotasnapshot.FieldPremiumRemaining, field.TypeInt, value)
	}
	if value, ok := _u.mutation.PremiumUsed(); ok {
		_spec.SetField(copilotquotasnapshot.FieldPremiumUsed, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedPremiumUsed(); ok {
		_spec.AddField(copilotquotasnapshot.FieldPremiumUsed, field.TypeInt, value)
	}
	if value, ok := _u.mutation.PremiumOverage(); ok {
		_spec.SetField(copilotquotasnapshot.FieldPremiumOverage, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedPremiumOverage(); ok {
		_spec.AddField(copilotquotasnapshot.FieldPremiumOverage, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Unlimited(); ok {
		_spec.SetField(copilotquotasnapshot.FieldUnlimited, field.TypeBool, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{copilotquotasnapshot.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// CopilotQuotaSnapshotUpdateOne is the builder for updating a single CopilotQuotaSnapshot entity.
type CopilotQuotaSnapshotUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *CopilotQuotaSnapshotMutation
}

// SetAccountID sets the "account_id" field.
func (_u *CopilotQuotaSnapshotUpdateOne) SetAccountID(v int64) *CopilotQuotaSnapshotUpdateOne {
	_u.mutation.ResetAccountID()
	_u.mutation.SetAccountID(v)
	return _u
}

// SetNillableAccountID sets the "account_id" field if the given value is not nil.
func (_u *CopilotQuotaSnapshotUpdateOne) SetNillableAccountID(v *int64) *CopilotQuotaSnapshotUpdateOne {
	if v != nil {
		_u.SetAccountID(*v)
	}
	return _u
}

// AddAccountID adds value to the "account_id" field.
func (_u *CopilotQuotaSnapshotUpdateOne) AddAccountID(v int64) *CopilotQuotaSnapshotUpdateOne {
	_u.mutation.AddAccountID(v)
	return _u
}

// SetSnapshotDate sets the "snapshot_date" field.
func (_u *CopilotQuotaSnapshotUpdateOne) SetSnapshotDate(v time.Time) *CopilotQuotaSnapshotUpdateOne {
	_u.mutation.SetSnapshotDate(v)
	return _u
}

// SetNillableSnapshotDate sets the "snapshot_date" field if the given value is not nil.
func (_u *CopilotQuotaSnapshotUpdateOne) SetNillableSnapshotDate(v *time.Time) *CopilotQuotaSnapshotUpdateOne {
	if v != nil {
		_u.SetSnapshotDate(*v)
	}
	return _u
}

// SetPlanType sets the "plan_type" field.
func (_u *CopilotQuotaSnapshotUpdateOne) SetPlanType(v string) *CopilotQuotaSnapshotUpdateOne {
	_u.mutation.SetPlanType(v)
	return _u
}

// SetNillablePlanType sets the "plan_type" field if the given value is not nil.
func (_u *CopilotQuotaSnapshotUpdateOne) SetNillablePlanType(v *string) *CopilotQuotaSnapshotUpdateOne {
	if v != nil {
		_u.SetPlanType(*v)
	}
	return _u
}

// ClearPlanType clears the value of the "plan_type" field.
func (_u *CopilotQuotaSnapshotUpdateOne) ClearPlanType() *CopilotQuotaSnapshotUpdateOne {
	_u.mutation.ClearPlanType()
	return _u
}

// SetPremiumEntitlement sets the "premium_entitlement" field.
func (_u *CopilotQuotaSnapshotUpdateOne) SetPremiumEntitlement(v int) *CopilotQuotaSnapshotUpdateOne {
	_u.mutation.ResetPremiumEntitlement()
	_u.mutation.SetPremiumEntitlement(v)
	return _u
}

// SetNillablePremiumEntitlement sets the "premium_entitlement" field if the given value is not nil.
func (_u *CopilotQuotaSnapshotUpdateOne) SetNillablePremiumEntitlement(v *int) *CopilotQuotaSnapshotUpdateOne {
	if v != nil {
		_u.SetPremiumEntitlement(*v)
	}
	return _u
}

// AddPremiumEntitlement adds value to the "premium_entitlement" field.
func (_u *CopilotQuotaSnapshotUpdateOne) AddPremiumEntitlement(v int) *CopilotQuotaSnapshotUpdateOne {
	_u.mutation.AddPremiumEntitlement(v)
	return _u
}

// SetPremiumRemaining sets the "premium_remaining" field.
func (_u *CopilotQuotaSnapshotUpdateOne) SetPremiumRemaining(v int) *CopilotQuotaSnapshotUpdateOne {
	_u.mutation.ResetPremiumRemaining()
	_u.mutation.SetPremiumRemaining(v)
	return _u
}

// SetNillablePremiumRemaining sets the "premium_remaining" field if the given value is not nil.
func (_u *CopilotQuotaSnapshotUpdateOne) SetNillablePremiumRemaining(v *int) *CopilotQuotaSnapshotUpdateOne {
	if v != nil {
		_u.SetPremiumRemaining(*v)
	}
	return _u
}

// AddPremiumRemaining adds value to the "premium_remaining" field.
func (_u *CopilotQuotaSnapshotUpdateOne) AddPremiumRemaining(v int) *CopilotQuotaSnapshotUpdateOne {
	_u.mutation.AddPremiumRemaining(v)
	return _u
}

// SetPremiumUsed sets the "premium_used" field.
func (_u *CopilotQuotaSnapshotUpdateOne) SetPremiumUsed(v int) *CopilotQuotaSnapshotUpdateOne {
	_u.mutation.ResetPremiumUsed()
	_u.mutation.SetPremiumUsed(v)
	return _u
}

// SetNillablePremiumUsed sets the "premium_used" field if the given value is not nil.
func (_u *CopilotQuotaSnapshotUpdateOne) SetNillablePremiumUsed(v *int) *CopilotQuotaSnapshotUpdateOne {
	if v != nil {
		_u.SetPremiumUsed(*v)
	}
	return _u
}

// AddPremiumUsed adds value to the "premium_used" field.
func (_u *CopilotQuotaSnapshotUpdateOne) AddPremiumUsed(v int) *CopilotQuotaSnapshotUpdateOne {
	_u.mutation.AddPremiumUsed(v)
	return _u
}

// SetPremiumOverage sets the "premium_overage" field.
func (_u *CopilotQuotaSnapshotUpdateOne) SetPremiumOverage(v int) *CopilotQuotaSnapshotUpdateOne {
	_u.mutation.ResetPremiumOverage()
	_u.mutation.SetPremiumOverage(v)
	return _u
}

// SetNillablePremiumOverage sets the "premium_overage" field if the given value is not nil.
func (_u *CopilotQuotaSnapshotUpdateOne) SetNillablePremiumOverage(v *int) *CopilotQuotaSnapshotUpdateOne {
	if v != nil {
		_u.SetPremiumOverage(*v)
	}
	return _u
}

// AddPremiumOverage adds value to the "premium_overage" field.
func (_u *CopilotQuotaSnapshotUpdateOne) AddPremiumOverage(v int) *CopilotQuotaSnapshotUpdateOne {
	_u.mutation.AddPremiumOverage(v)
	return _u
}

// SetUnlimited sets the "unlimited" field.
func (_u *CopilotQuotaSnapshotUpdateOne) SetUnlimited(v bool) *CopilotQuotaSnapshotUpdateOne {
	_u.mutation.SetUnlimited(v)
	return _u
}

// SetNillableUnlimited sets the "unlimited" field if the given value is not nil.
func (_u *CopilotQuotaSnapshotUpdateOne) SetNillableUnlimited(v *bool) *CopilotQuotaSnapshotUpdateOne {
	if v != nil {
		_u.SetUnlimited(*v)
	}
	return _u
}

// Mutation returns the CopilotQuotaSnapshotMutation object of the builder.
func (_u *CopilotQuotaSnapshotUpdateOne) Mutation() *CopilotQuotaSnapshotMutation {
	return _u.mutation
}

// Where appends a list predicates to the CopilotQuotaSnapshotUpdate builder.
func (_u *CopilotQuotaSnapshotUpdateOne) Where(ps ...predicate.CopilotQuotaSnapshot) *CopilotQuotaSnapshotUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *CopilotQuotaSnapshotUpdateOne) Select(field string, fields ...string) *CopilotQuotaSnapshotUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated CopilotQuotaSnapshot entity.
func (_u *CopilotQuotaSnapshotUpdateOne) Save(ctx context.Context) (*CopilotQuotaSnapshot, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *CopilotQuotaSnapshotUpdateOne) SaveX(ctx context.Context) *CopilotQuotaSnapshot {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *CopilotQuotaSnapshotUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *CopilotQuotaSnapshotUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *CopilotQuotaSnapshotUpdateOne) check() error {
	if v, ok := _u.mutation.PlanType(); ok {
		if err := copilotquotasnapshot.PlanTypeValidator(v); err != nil {
			return &ValidationError{Name: "plan_type", err: fmt.Errorf(`ent: validator failed for field "CopilotQuotaSnapshot.plan_type": %w`, err)}
		}
	}
	return nil
}

func (_u *CopilotQuotaSnapshotUpdateOne) sqlSave(ctx context.Context) (_node *CopilotQuotaSnapshot, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(copilotquotasnapshot.Table, copilotquotasnapshot.Columns, sqlgraph.NewFieldSpec(copilotquotasnapshot.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "CopilotQuotaSnapshot.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, copilotquotasnapshot.FieldID)
		for _, f := range fields {
			if !copilotquotasnapshot.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != copilotquotasnapshot.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.AccountID(); ok {
		_spec.SetField(copilotquotasnapshot.FieldAccountID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedAccountID(); ok {
		_spec.AddField(copilotquotasnapshot.FieldAccountID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.SnapshotDate(); ok {
		_spec.SetField(copilotquotasnapshot.FieldSnapshotDate, field.TypeTime, value)
	}
	if value, ok := _u.mutation.PlanType(); ok {
		_spec.SetField(copilotquotasnapshot.FieldPlanType, field.TypeString, value)
	}
	if _u.mutation.PlanTypeCleared() {
		_spec.ClearField(copilotquotasnapshot.FieldPlanType, field.TypeString)
	}
	if value, ok := _u.mutation.PremiumEntitlement(); ok {
		_spec.SetField(copilotquotasnapshot.FieldPremiumEntitlement, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedPremiumEntitlement(); ok {
		_spec.AddField(copilotquotasnapshot.FieldPremiumEntitlement, field.TypeInt, value)
	}
	if value, ok := _u.mutation.PremiumRemaining(); ok {
		_spec.SetField(copilotquotasnapshot.FieldPremiumRemaining, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedPremiumRemaining(); ok {
		_spec.AddField(copilotquotasnapshot.FieldPremiumRemaining, field.TypeInt, value)
	}
	if value, ok := _u.mutation.PremiumUsed(); ok {
		_spec.SetField(copilotquotasnapshot.FieldPremiumUsed, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedPremiumUsed(); ok {
		_spec.AddField(copilotquotasnapshot.FieldPremiumUsed, field.TypeInt, value)
	}
	if value, ok := _u.mutation.PremiumOverage(); ok {
		_spec.SetField(copilotquotasnapshot.FieldPremiumOverage, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedPremiumOverage(); ok {
		_spec.AddField(copilotquotasnapshot.FieldPremiumOverage, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Unlimited(); ok {
		_spec.SetField(copilotquotasnapshot.FieldUnlimited, field.TypeBool, value)
	}
	_node = &CopilotQuotaSnapshot{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{copilotquotasnapshot.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
