// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/passkeycredential"
	"github.com/Wei-Shaw/sub2api/ent/user"
)

// PasskeyCredentialCreate is the builder for creating a PasskeyCredential entity.
type PasskeyCredentialCreate struct {
	config
	mutation *PasskeyCredentialMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreatedAt sets the "created_at" field.
func (_c *PasskeyCredentialCreate) SetCreatedAt(v time.Time) *PasskeyCredentialCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *PasskeyCredentialCreate) SetNillableCreatedAt(v *time.Time) *PasskeyCredentialCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *PasskeyCredentialCreate) SetUpdatedAt(v time.Time) *PasskeyCredentialCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *PasskeyCredentialCreate) SetNillableUpdatedAt(v *time.Time) *PasskeyCredentialCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetUserID sets the "user_id" field.
func (_c *PasskeyCredentialCreate) SetUserID(v int64) *PasskeyCredentialCreate {
	_c.mutation.SetUserID(v)
	return _c
}

// SetCredentialID sets the "credential_id" field.
func (_c *PasskeyCredentialCreate) SetCredentialID(v string) *PasskeyCredentialCreate {
	_c.mutation.SetCredentialID(v)
	return _c
}

// SetPublicKey sets the "public_key" field.
func (_c *PasskeyCredentialCreate) SetPublicKey(v string) *PasskeyCredentialCreate {
	_c.mutation.SetPublicKey(v)
	return _c
}

// SetSignCount sets the "sign_count" field.
func (_c *PasskeyCredentialCreate) SetSignCount(v int64) *PasskeyCredentialCreate {
	_c.mutation.SetSignCount(v)
	return _c
}

// SetNillableSignCount sets the "sign_count" field if the given value is not nil.
func (_c *PasskeyCredentialCreate) SetNillableSignCount(v *int64) *PasskeyCredentialCreate {
	if v != nil {
		_c.SetSignCount(*v)
	}
	return _c
}

// SetTransports sets the "transports" field.
func (_c *PasskeyCredentialCreate) SetTransports(v []string) *PasskeyCredentialCreate {
	_c.mutation.SetTransports(v)
	return _c
}

// SetAaguid sets the "aaguid" field.
func (_c *PasskeyCredentialCreate) SetAaguid(v string) *PasskeyCredentialCreate {
	_c.mutation.SetAaguid(v)
	return _c
}

// SetNillableAaguid sets the "aaguid" field if the given value is not nil.
func (_c *PasskeyCredentialCreate) SetNillableAaguid(v *string) *PasskeyCredentialCreate {
	if v != nil {
		_c.SetAaguid(*v)
	}
	return _c
}

// SetBackupEligible sets the "backup_eligible" field.
func (_c *PasskeyCredentialCreate) SetBackupEligible(v bool) *PasskeyCredentialCreate {
	_c.mutation.SetBackupEligible(v)
	return _c
}

// SetNillableBackupEligible sets the "backup_eligible" field if the given value is not nil.
func (_c *PasskeyCredentialCreate) SetNillableBackupEligible(v *bool) *PasskeyCredentialCreate {
	if v != nil {
		_c.SetBackupEligible(*v)
	}
	return _c
}

// SetBackupState sets the "backup_state" field.
func (_c *PasskeyCredentialCreate) SetBackupState(v bool) *PasskeyCredentialCreate {
	_c.mutation.SetBackupState(v)
	return _c
}

// SetNillableBackupState sets the "backup_state" field if the given value is not nil.
func (_c *PasskeyCredentialCreate) SetNillableBackupState(v *bool) *PasskeyCredentialCreate {
	if v != nil {
		_c.SetBackupState(*v)
	}
	return _c
}

// SetFriendlyName sets the "friendly_name" field.
func (_c *PasskeyCredentialCreate) SetFriendlyName(v string) *PasskeyCredentialCreate {
	_c.mutation.SetFriendlyName(v)
	return _c
}

// SetNillableFriendlyName sets the "friendly_name" field if the given value is not nil.
func (_c *PasskeyCredentialCreate) SetNillableFriendlyName(v *string) *PasskeyCredentialCreate {
	if v != nil {
		_c.SetFriendlyName(*v)
	}
	return _c
}

// SetLastUsedAt sets the "last_used_at" field.
func (_c *PasskeyCredentialCreate) SetLastUsedAt(v time.Time) *PasskeyCredentialCreate {
	_c.mutation.SetLastUsedAt(v)
	return _c
}

// SetNillableLastUsedAt sets the "last_used_at" field if the given value is not nil.
func (_c *PasskeyCredentialCreate) SetNillableLastUsedAt(v *time.Time) *PasskeyCredentialCreate {
	if v != nil {
		_c.SetLastUsedAt(*v)
	}
	return _c
}

// SetRevokedAt sets the "revoked_at" field.
func (_c *PasskeyCredentialCreate) SetRevokedAt(v time.Time) *PasskeyCredentialCreate {
	_c.mutation.SetRevokedAt(v)
	return _c
}

// SetNillableRevokedAt sets the "revoked_at" field if the given value is not nil.
func (_c *PasskeyCredentialCreate) SetNillableRevokedAt(v *time.Time) *PasskeyCredentialCreate {
	if v != nil {
		_c.SetRevokedAt(*v)
	}
	return _c
}

// SetUser sets the "user" edge to the User entity.
func (_c *PasskeyCredentialCreate) SetUser(v *User) *PasskeyCredentialCreate {
	return _c.SetUserID(v.ID)
}

// Mutation returns the PasskeyCredentialMutation object of the builder.
func (_c *PasskeyCredentialCreate) Mutation() *PasskeyCredentialMutation {
	return _c.mutation
}

// Save creates the PasskeyCredential in the database.
func (_c *PasskeyCredentialCreate) Save(ctx context.Context) (*PasskeyCredential, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *PasskeyCredentialCreate) SaveX(ctx context.Context) *PasskeyCredential {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *PasskeyCredentialCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *PasskeyCredentialCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *PasskeyCredentialCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := passkeycredential.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := passkeycredential.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.SignCount(); !ok {
		v := passkeycredential.DefaultSignCount
		_c.mutation.SetSignCount(v)
	}
	if _, ok := _c.mutation.Aaguid(); !ok {
		v := passkeycredential.DefaultAaguid
		_c.mutation.SetAaguid(v)
	}
	if _, ok := _c.mutation.BackupEligible(); !ok {
		v := passkeycredential.DefaultBackupEligible
		_c.mutation.SetBackupEligible(v)
	}
	if _, ok := _c.mutation.BackupState(); !ok {
		v := passkeycredential.DefaultBackupState
		_c.mutation.SetBackupState(v)
	}
	if _, ok := _c.mutation.FriendlyName(); !ok {
		v := passkeycredential.DefaultFriendlyName
		_c.mutation.SetFriendlyName(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *PasskeyCredentialCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "PasskeyCredential.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "PasskeyCredential.updated_at"`)}
	}
	if _, ok := _c.mutation.UserID(); !ok {
		return &ValidationError{Name: "user_id", err: errors.New(`ent: missing required field "PasskeyCredential.user_id"`)}
	}
	if _, ok := _c.mutation.CredentialID(); !ok {
		return &ValidationError{Name: "credential_id", err: errors.New(`ent: missing required field "PasskeyCredential.credential_id"`)}
	}
	if v, ok := _c.mutation.CredentialID(); ok {
		if err := passkeycredential.CredentialIDValidator(v); err != nil {
			return &ValidationError{Name: "credential_id", err: fmt.Errorf(`ent: validator failed for field "PasskeyCredential.credential_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.PublicKey(); !ok {
		return &ValidationError{Name: "public_key", err: errors.New(`ent: missing required field "PasskeyCredential.public_key"`)}
	}
	if v, ok := _c.mutation.PublicKey(); ok {
		if err := passkeycredential.PublicKeyValidator(v); err != nil {
			return &ValidationError{Name: "public_key", err: fmt.Errorf(`ent: validator failed for field "PasskeyCredential.public_key": %w`, err)}
		}
	}
	if _, ok := _c.mutation.SignCount(); !ok {
		return &ValidationError{Name: "sign_count", err: errors.New(`ent: missing required field "PasskeyCredential.sign_count"`)}
	}
	if _, ok := _c.mutation.Aaguid(); !ok {
		return &ValidationError{Name: "aaguid", err: errors.New(`ent: missing required field "PasskeyCredential.aaguid"`)}
	}
	if v, ok := _c.mutation.Aaguid(); ok {
		if err := passkeycredential.AaguidValidator(v); err != nil {
			return &ValidationError{Name: "aaguid", err: fmt.Errorf(`ent: validator failed for field "PasskeyCredential.aaguid": %w`, err)}
		}
	}
	if _, ok := _c.mutation.BackupEligible(); !ok {
		return &ValidationError{Name: "backup_eligible", err: errors.New(`ent: missing required field "PasskeyCredential.backup_eligible"`)}
	}
	if _, ok := _c.mutation.BackupState(); !ok {
		return &ValidationError{Name: "backup_state", err: errors.New(`ent: missing required field "PasskeyCredential.backup_state"`)}
	}
	if _, ok := _c.mutation.FriendlyName(); !ok {
		return &ValidationError{Name: "friendly_name", err: errors.New(`ent: missing required field "PasskeyCredential.friendly_name"`)}
	}
	if v, ok := _c.mutation.FriendlyName(); ok {
		if err := passkeycredential.FriendlyNameValidator(v); err != nil {
			return &ValidationError{Name: "friendly_name", err: fmt.Errorf(`ent: validator failed for field "PasskeyCredential.friendly_name": %w`, err)}
		}
	}
	if len(_c.mutation.UserIDs()) == 0 {
		return &ValidationError{Name: "user", err: errors.New(`ent: missing required edge "PasskeyCredential.user"`)}
	}
	return nil
}

func (_c *PasskeyCredentialCreate) sqlSave(ctx context.Context) (*PasskeyCredential, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *PasskeyCredentialCreate) createSpec() (*PasskeyCredential, *sqlgraph.CreateSpec) {
	var (
		_node = &PasskeyCredential{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(passkeycredential.Table, sqlgraph.NewFieldSpec(passkeycredential.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(passkeycredential.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(passkeycredential.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.CredentialID(); ok {
		_spec.SetField(passkeycredential.FieldCredentialID, field.TypeString, value)
		_node.CredentialID = value
	}
	if value, ok := _c.mutation.PublicKey(); ok {
		_spec.SetField(passkeycredential.FieldPublicKey, field.TypeString, value)
		_node.PublicKey = value
	}
	if value, ok := _c.mutation.SignCount(); ok {
		_spec.SetField(passkeycredential.FieldSignCount, field.TypeInt64, value)
		_node.SignCount = value
	}
	if value, ok := _c.mutation.Transports(); ok {
		_spec.SetField(passkeycredential.FieldTransports, field.TypeJSON, value)
		_node.Transports = value
	}
	if value, ok := _c.mutation.Aaguid(); ok {
		_spec.SetField(passkeycredential.FieldAaguid, field.TypeString, value)
		_node.Aaguid = value
	}
	if value, ok := _c.mutation.BackupEligible(); ok {
		_spec.SetField(passkeycredential.FieldBackupEligible, field.TypeBool, value)
		_node.BackupEligible = value
	}
	if value, ok := _c.mutation.BackupState(); ok {
		_spec.SetField(passkeycredential.FieldBackupState, field.TypeBool, value)
		_node.BackupState = value
	}
	if value, ok := _c.mutation.FriendlyName(); ok {
		_spec.SetField(passkeycredential.FieldFriendlyName, field.TypeString, value)
		_node.FriendlyName = value
	}
	if value, ok := _c.mutation.LastUsedAt(); ok {
		_spec.SetField(passkeycredential.FieldLastUsedAt, field.TypeTime, value)
		_node.LastUsedAt = &value
	}
	if value, ok := _c.mutation.RevokedAt(); ok {
		_spec.SetField(passkeycredential.FieldRevokedAt, field.TypeTime, value)
		_node.RevokedAt = &value
	}
	if nodes := _c.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   passkeycredential.UserTable,
			Columns: []string{passkeycredential.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.UserID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.PasskeyCredential.Create().
//		SetCreatedAt(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.PasskeyCredentialUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *PasskeyCredentialCreate) OnConflict(opts ...sql.ConflictOption) *PasskeyCredentialUpsertOne {
	_c.conflict = opts
	return &PasskeyCredentialUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.PasskeyCredential.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *PasskeyCredentialCreate) OnConflictColumns(columns ...string) *PasskeyCredentialUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &PasskeyCredentialUpsertOne{
		create: _c,
	}
}

type (
	// PasskeyCredentialUpsertOne is the builder for "upsert"-ing
	//  one PasskeyCredential node.
	PasskeyCredentialUpsertOne struct {
		create *PasskeyCredentialCreate
	}

	// PasskeyCredentialUpsert is the "OnConflict" setter.
	PasskeyCredentialUpsert struct {
		*sql.UpdateSet
	}
)

// SetUpdatedAt sets the "updated_at" field.
func (u *PasskeyCredentialUpsert) SetUpdatedAt(v time.Time) *PasskeyCredentialUpsert {
	u.Set(passkeycredential.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *PasskeyCredentialUpsert) UpdateUpdatedAt() *PasskeyCredentialUpsert {
	u.SetExcluded(passkeycredential.FieldUpdatedAt)
	return u
}

// SetUserID sets the "user_id" field.
func (u *PasskeyCredentialUpsert) SetUserID(v int64) *PasskeyCredentialUpsert {
	u.Set(passkeycredential.FieldUserID, v)
	return u
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *PasskeyCredentialUpsert) UpdateUserID() *PasskeyCredentialUpsert {
	u.SetExcluded(passkeycredential.FieldUserID)
	return u
}

// SetCredentialID sets the "credential_id" field.
func (u *PasskeyCredentialUpsert) SetCredentialID(v string) *PasskeyCredentialUpsert {
	u.Set(passkeycredential.FieldCredentialID, v)
	return u
}

// UpdateCredentialID sets the "credential_id" field to the value that was provided on create.
func (u *PasskeyCredentialUpsert) UpdateCredentialID() *PasskeyCredentialUpsert {
	u.SetExcluded(passkeycredential.FieldCredentialID)
	return u
}

// SetPublicKey sets the "public_key" field.
func (u *PasskeyCredentialUpsert) SetPublicKey(v string) *PasskeyCredentialUpsert {
	u.Set(passkeycredential.FieldPublicKey, v)
	return u
}

// UpdatePublicKey sets the "public_key" field to the value that was provided on create.
func (u *PasskeyCredentialUpsert) UpdatePublicKey() *PasskeyCredentialUpsert {
	u.SetExcluded(passkeycredential.FieldPublicKey)
	return u
}

// SetSignCount sets the "sign_count" field.
func (u *PasskeyCredentialUpsert) SetSignCount(v int64) *PasskeyCredentialUpsert {
	u.Set(passkeycredential.FieldSignCount, v)
	return u
}

// UpdateSignCount sets the "sign_count" field to the value that was provided on create.
func (u *PasskeyCredentialUpsert) UpdateSignCount() *PasskeyCredentialUpsert {
	u.SetExcluded(passkeycredential.FieldSignCount)
	return u
}

// AddSignCount adds v to the "sign_count" field.
func (u *PasskeyCredentialUpsert) AddSignCount(v int64) *PasskeyCredentialUpsert {
	u.Add(passkeycredential.FieldSignCount, v)
	return u
}

// SetTransports sets the "transports" field.
func (u *PasskeyCredentialUpsert) SetTransports(v []string) *PasskeyCredentialUpsert {
	u.Set(passkeycredential.FieldTransports, v)
	return u
}

// UpdateTransports sets the "transports" field to the value that was provided on create.
func (u *PasskeyCredentialUpsert) UpdateTransports() *PasskeyCredentialUpsert {
	u.SetExcluded(passkeycredential.FieldTransports)
	return u
}

// ClearTransports clears the value of the "transports" field.
func (u *PasskeyCredentialUpsert) ClearTransports() *PasskeyCredentialUpsert {
	u.SetNull(passkeycredential.FieldTransports)
	return u
}

// SetAaguid sets the "aaguid" field.
func (u *PasskeyCredentialUpsert) SetAaguid(v string) *PasskeyCredentialUpsert {
	u.Set(passkeycredential.FieldAaguid, v)
	return u
}

// UpdateAaguid sets the "aaguid" field to the value that was provided on create.
func (u *PasskeyCredentialUpsert) UpdateAaguid() *PasskeyCredentialUpsert {
	u.SetExcluded(passkeycredential.FieldAaguid)
	return u
}

// SetBackupEligible sets the "backup_eligible" field.
func (u *PasskeyCredentialUpsert) SetBackupEligible(v bool) *PasskeyCredentialUpsert {
	u.Set(passkeycredential.FieldBackupEligible, v)
	return u
}

// UpdateBackupEligible sets the "backup_eligible" field to the value that was provided on create.
func (u *PasskeyCredentialUpsert) UpdateBackupEligible() *PasskeyCredentialUpsert {
	u.SetExcluded(passkeycredential.FieldBackupEligible)
	return u
}

// SetBackupState sets the "backup_state" field.
func (u *PasskeyCredentialUpsert) SetBackupState(v bool) *PasskeyCredentialUpsert {
	u.Set(passkeycredential.FieldBackupState, v)
	return u
}

// UpdateBackupState sets the "backup_state" field to the value that was provided on create.
func (u *PasskeyCredentialUpsert) UpdateBackupState() *PasskeyCredentialUpsert {
	u.SetExcluded(passkeycredential.FieldBackupState)
	return u
}

// SetFriendlyName sets the "friendly_name" field.
func (u *PasskeyCredentialUpsert) SetFriendlyName(v string) *PasskeyCredentialUpsert {
	u.Set(passkeycredential.FieldFriendlyName, v)
	return u
}

// UpdateFriendlyName sets the "friendly_name" field to the value that was provided on create.
func (u *PasskeyCredentialUpsert) UpdateFriendlyName() *PasskeyCredentialUpsert {
	u.SetExcluded(passkeycredential.FieldFriendlyName)
	return u
}

// SetLastUsedAt sets the "last_used_at" field.
func (u *PasskeyCredentialUpsert) SetLastUsedAt(v time.Time) *PasskeyCredentialUpsert {
	u.Set(passkeycredential.FieldLastUsedAt, v)
	return u
}

// UpdateLastUsedAt sets the "last_used_at" field to the value that was provided on create.
func (u *PasskeyCredentialUpsert) UpdateLastUsedAt() *PasskeyCredentialUpsert {
	u.SetExcluded(passkeycredential.FieldLastUsedAt)
	return u
}

// ClearLastUsedAt clears the value of the "last_used_at" field.
func (u *PasskeyCredentialUpsert) ClearLastUsedAt() *PasskeyCredentialUpsert {
	u.SetNull(passkeycredential.FieldLastUsedAt)
	return u
}

// SetRevokedAt sets the "revoked_at" field.
func (u *PasskeyCredentialUpsert) SetRevokedAt(v time.Time) *PasskeyCredentialUpsert {
	u.Set(passkeycredential.FieldRevokedAt, v)
	return u
}

// UpdateRevokedAt sets the "revoked_at" field to the value that was provided on create.
func (u *PasskeyCredentialUpsert) UpdateRevokedAt() *PasskeyCredentialUpsert {
	u.SetExcluded(passkeycredential.FieldRevokedAt)
	return u
}

// ClearRevokedAt clears the value of the "revoked_at" field.
func (u *PasskeyCredentialUpsert) ClearRevokedAt() *PasskeyCredentialUpsert {
	u.SetNull(passkeycredential.FieldRevokedAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.PasskeyCredential.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *PasskeyCredentialUpsertOne) UpdateNewValues() *PasskeyCredentialUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(passkeycredential.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.PasskeyCredential.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *PasskeyCredentialUpsertOne) Ignore() *PasskeyCredentialUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *PasskeyCredentialUpsertOne) DoNothing() *PasskeyCredentialUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the PasskeyCredentialCreate.OnConflict
// documentation for more info.
func (u *PasskeyCredentialUpsertOne) Update(set func(*PasskeyCredentialUpsert)) *PasskeyCredentialUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&PasskeyCredentialUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *PasskeyCredentialUpsertOne) SetUpdatedAt(v time.Time) *PasskeyCredentialUpsertOne {
	return u.Update(func(s *PasskeyCredentialUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *PasskeyCredentialUpsertOne) UpdateUpdatedAt() *PasskeyCredentialUpsertOne {
	return u.Update(func(s *PasskeyCredentialUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetUserID sets the "user_id" field.
func (u *PasskeyCredentialUpsertOne) SetUserID(v int64) *PasskeyCredentialUpsertOne {
	return u.Update(func(s *PasskeyCredentialUpsert) {
		s.SetUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *PasskeyCredentialUpsertOne) UpdateUserID() *PasskeyCredentialUpsertOne {
	return u.Update(func(s *PasskeyCredentialUpsert) {
		s.UpdateUserID()
	})
}

// SetCredentialID sets the "credential_id" field.
func (u *PasskeyCredentialUpsertOne) SetCredentialID(v string) *PasskeyCredentialUpsertOne {
	return u.Update(func(s *PasskeyCredentialUpsert) {
		s.SetCredentialID(v)
	})
}

// UpdateCredentialID sets the "credential_id" field to the value that was provided on create.
func (u *PasskeyCredentialUpsertOne) UpdateCredentialID() *PasskeyCredentialUpsertOne {
	return u.Update(func(s *PasskeyCredentialUpsert) {
		s.UpdateCredentialID()
	})
}

// SetPublicKey sets the "public_key" field.
func (u *PasskeyCredentialUpsertOne) SetPublicKey(v string) *PasskeyCredentialUpsertOne {
	return u.Update(func(s *PasskeyCredentialUpsert) {
		s.SetPublicKey(v)
	})
}

// UpdatePublicKey sets the "public_key" field to the value that was provided on create.
func (u *PasskeyCredentialUpsertOne) UpdatePublicKey() *PasskeyCredentialUpsertOne {
	return u.Update(func(s *PasskeyCredentialUpsert) {
		s.UpdatePublicKey()
	})
}

// SetSignCount sets the "sign_count" field.
func (u *PasskeyCredentialUpsertOne) SetSignCount(v int64) *PasskeyCredentialUpsertOne {
	return u.Update(func(s *PasskeyCredentialUpsert) {
		s.SetSignCount(v)
	})
}

// AddSignCount adds v to the "sign_count" field.
func (u *PasskeyCredentialUpsertOne) AddSignCount(v int64) *PasskeyCredentialUpsertOne {
	return u.Update(func(s *PasskeyCredentialUpsert) {
		s.AddSignCount(v)
	})
}

// UpdateSignCount sets the "sign_count" field to the value that was provided on create.
func (u *PasskeyCredentialUpsertOne) UpdateSignCount() *PasskeyCredentialUpsertOne {
	return u.Update(func(s *PasskeyCredentialUpsert) {
		s.UpdateSignCount()
	})
}

// SetTransports sets the "transports" field.
func (u *PasskeyCredentialUpsertOne) SetTransports(v []string) *PasskeyCredentialUpsertOne {
	return u.Update(func(s *PasskeyCredentialUpsert) {
		s.SetTransports(v)
	})
}

// UpdateTransports sets the "transports" field to the value that was provided on create.
func (u *PasskeyCredentialUpsertOne) UpdateTransports() *PasskeyCredentialUpsertOne {
	return u.Update(func(s *PasskeyCredentialUpsert) {
		s.UpdateTransports()
	})
}

// ClearTransports clears the value of the "transports" field.
func (u *PasskeyCredentialUpsertOne) ClearTransports() *PasskeyCredentialUpsertOne {
	return u.Update(func(s *PasskeyCredentialUpsert) {
		s.ClearTransports()
	})
}

// SetAaguid sets the "aaguid" field.
func (u *PasskeyCredentialUpsertOne) SetAaguid(v string) *PasskeyCredentialUpsertOne {
	return u.Update(func(s *PasskeyCredentialUpsert) {
		s.SetAaguid(v)
	})
}

// UpdateAaguid sets the "aaguid" field to the value that was provided on create.
func (u *PasskeyCredentialUpsertOne) UpdateAaguid() *PasskeyCredentialUpsertOne {
	return u.Update(func(s *PasskeyCredentialUpsert) {
		s.UpdateAaguid()
	})
}

// SetBackupEligible sets the "backup_eligible" field.
func (u *PasskeyCredentialUpsertOne) SetBackupEligible(v bool) *PasskeyCredentialUpsertOne {
	return u.Update(func(s *PasskeyCredentialUpsert) {
		s.SetBackupEligible(v)
	})
}

// UpdateBackupEligible sets the "backup_eligible" field to the value that was provided on create.
func (u *PasskeyCredentialUpsertOne) UpdateBackupEligible() *PasskeyCredentialUpsertOne {
	return u.Update(func(s *PasskeyCredentialUpsert) {
		s.UpdateBackupEligible()
	})
}

// SetBackupState sets the "backup_state" field.
func (u *PasskeyCredentialUpsertOne) SetBackupState(v bool) *PasskeyCredentialUpsertOne {
	return u.Update(func(s *PasskeyCredentialUpsert) {
		s.SetBackupState(v)
	})
}

// UpdateBackupState sets the "backup_state" field to the value that was provided on create.
func (u *PasskeyCredentialUpsertOne) UpdateBackupState() *PasskeyCredentialUpsertOne {
	return u.Update(func(s *PasskeyCredentialUpsert) {
		s.UpdateBackupState()
	})
}

// SetFriendlyName sets the "friendly_name" field.
func (u *PasskeyCredentialUpsertOne) SetFriendlyName(v string) *PasskeyCredentialUpsertOne {
	return u.Update(func(s *PasskeyCredentialUpsert) {
		s.SetFriendlyName(v)
	})
}

// UpdateFriendlyName sets the "friendly_name" field to the value that was provided on create.
func (u *PasskeyCredentialUpsertOne) UpdateFriendlyName() *PasskeyCredentialUpsertOne {
	return u.Update(func(s *PasskeyCredentialUpsert) {
		s.UpdateFriendlyName()
	})
}

// SetLastUsedAt sets the "last_used_at" field.
func (u *PasskeyCredentialUpsertOne) SetLastUsedAt(v time.Time) *PasskeyCredentialUpsertOne {
	return u.Update(func(s *PasskeyCredentialUpsert) {
		s.SetLastUsedAt(v)
	})
}

// UpdateLastUsedAt sets the "last_used_at" field to the value that was provided on create.
func (u *PasskeyCredentialUpsertOne) UpdateLastUsedAt() *PasskeyCredentialUpsertOne {
	return u.Update(func(s *PasskeyCredentialUpsert) {
		s.UpdateLastUsedAt()
	})
}

// ClearLastUsedAt clears the value of the "last_used_at" field.
func (u *PasskeyCredentialUpsertOne) ClearLastUsedAt() *PasskeyCredentialUpsertOne {
	return u.Update(func(s *PasskeyCredentialUpsert) {
		s.ClearLastUsedAt()
	})
}

// SetRevokedAt sets the "revoked_at" field.
func (u *PasskeyCredentialUpsertOne) SetRevokedAt(v time.Time) *PasskeyCredentialUpsertOne {
	return u.Update(func(s *PasskeyCredentialUpsert) {
		s.SetRevokedAt(v)
	})
}

// UpdateRevokedAt sets the "revoked_at" field to the value that was provided on create.
func (u *PasskeyCredentialUpsertOne) UpdateRevokedAt() *PasskeyCredentialUpsertOne {
	return u.Update(func(s *PasskeyCredentialUpsert) {
		s.UpdateRevokedAt()
	})
}

// ClearRevokedAt clears the value of the "revoked_at" field.
func (u *PasskeyCredentialUpsertOne) ClearRevokedAt() *PasskeyCredentialUpsertOne {
	return u.Update(func(s *PasskeyCredentialUpsert) {
		s.ClearRevokedAt()
	})
}

// Exec executes the query.
func (u *PasskeyCredentialUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for PasskeyCredentialCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *PasskeyCredentialUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *PasskeyCredentialUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *PasskeyCredentialUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// PasskeyCredentialCreateBulk is the builder for creating many PasskeyCredential entities in bulk.
type PasskeyCredentialCreateBulk struct {
	config
	err      error
	builders []*PasskeyCredentialCreate
	conflict []sql.ConflictOption
}

// Save creates the PasskeyCredential entities in the database.
func (_c *PasskeyCredentialCreateBulk) Save(ctx context.Context) ([]*PasskeyCredential, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*PasskeyCredential, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*PasskeyCredentialMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *PasskeyCredentialCreateBulk) SaveX(ctx context.Context) []*PasskeyCredential {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *PasskeyCredentialCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *PasskeyCredentialCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.PasskeyCredential.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.PasskeyCredentialUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *PasskeyCredentialCreateBulk) OnConflict(opts ...sql.ConflictOption) *PasskeyCredentialUpsertBulk {
	_c.conflict = opts
	return &PasskeyCredentialUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.PasskeyCredential.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *PasskeyCredentialCreateBulk) OnConflictColumns(columns ...string) *PasskeyCredentialUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &PasskeyCredentialUpsertBulk{
		create: _c,
	}
}

// PasskeyCredentialUpsertBulk is the builder for "upsert"-ing
// a bulk of PasskeyCredential nodes.
type PasskeyCredentialUpsertBulk struct {
	create *PasskeyCredentialCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.PasskeyCredential.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *PasskeyCredentialUpsertBulk) UpdateNewValues() *PasskeyCredentialUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(passkeycredential.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.PasskeyCredential.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *PasskeyCredentialUpsertBulk) Ignore() *PasskeyCredentialUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *PasskeyCredentialUpsertBulk) DoNothing() *PasskeyCredentialUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the PasskeyCredentialCreateBulk.OnConflict
// documentation for more info.
func (u *PasskeyCredentialUpsertBulk) Update(set func(*PasskeyCredentialUpsert)) *PasskeyCredentialUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&PasskeyCredentialUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *PasskeyCredentialUpsertBulk) SetUpdatedAt(v time.Time) *PasskeyCredentialUpsertBulk {
	return u.Update(func(s *PasskeyCredentialUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *PasskeyCredentialUpsertBulk) UpdateUpdatedAt() *PasskeyCredentialUpsertBulk {
	return u.Update(func(s *PasskeyCredentialUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetUserID sets the "user_id" field.
func (u *PasskeyCredentialUpsertBulk) SetUserID(v int64) *PasskeyCredentialUpsertBulk {
	return u.Update(func(s *PasskeyCredentialUpsert) {
		s.SetUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *PasskeyCredentialUpsertBulk) UpdateUserID() *PasskeyCredentialUpsertBulk {
	return u.Update(func(s *PasskeyCredentialUpsert) {
		s.UpdateUserID()
	})
}

// SetCredentialID sets the "credential_id" field.
func (u *PasskeyCredentialUpsertBulk) SetCredentialID(v string) *PasskeyCredentialUpsertBulk {
	return u.Update(func(s *PasskeyCredentialUpsert) {
		s.SetCredentialID(v)
	})
}

// UpdateCredentialID sets the "credential_id" field to the value that was provided on create.
func (u *PasskeyCredentialUpsertBulk) UpdateCredentialID() *PasskeyCredentialUpsertBulk {
	return u.Update(func(s *PasskeyCredentialUpsert) {
		s.UpdateCredentialID()
	})
}

// SetPublicKey sets the "public_key" field.
func (u *PasskeyCredentialUpsertBulk) SetPublicKey(v string) *PasskeyCredentialUpsertBulk {
	return u.Update(func(s *PasskeyCredentialUpsert) {
		s.SetPublicKey(v)
	})
}

// UpdatePublicKey sets the "public_key" field to the value that was provided on create.
func (u *PasskeyCredentialUpsertBulk) UpdatePublicKey() *PasskeyCredentialUpsertBulk {
	return u.Update(func(s *PasskeyCredentialUpsert) {
		s.UpdatePublicKey()
	})
}

// SetSignCount sets the "sign_count" field.
func (u *PasskeyCredentialUpsertBulk) SetSignCount(v int64) *PasskeyCredentialUpsertBulk {
	return u.Update(func(s *PasskeyCredentialUpsert) {
		s.SetSignCount(v)
	})
}

// AddSignCount adds v to the "sign_count" field.
func (u *PasskeyCredentialUpsertBulk) AddSignCount(v int64) *PasskeyCredentialUpsertBulk {
	return u.Update(func(s *PasskeyCredentialUpsert) {
		s.AddSignCount(v)
	})
}

// UpdateSignCount sets the "sign_count" field to the value that was provided on create.
func (u *PasskeyCredentialUpsertBulk) UpdateSignCount() *PasskeyCredentialUpsertBulk {
	return u.Update(func(s *PasskeyCredentialUpsert) {
		s.UpdateSignCount()
	})
}

// SetTransports sets the "transports" field.
func (u *PasskeyCredentialUpsertBulk) SetTransports(v []string) *PasskeyCredentialUpsertBulk {
	return u.Update(func(s *PasskeyCredentialUpsert) {
		s.SetTransports(v)
	})
}

// UpdateTransports sets the "transports" field to the value that was provided on create.
func (u *PasskeyCredentialUpsertBulk) UpdateTransports() *PasskeyCredentialUpsertBulk {
	return u.Update(func(s *PasskeyCredentialUpsert) {
		s.UpdateTransports()
	})
}

// ClearTransports clears the value of the "transports" field.
func (u *PasskeyCredentialUpsertBulk) ClearTransports() *PasskeyCredentialUpsertBulk {
	return u.Update(func(s *PasskeyCredentialUpsert) {
		s.ClearTransports()
	})
}

// SetAaguid sets the "aaguid" field.
func (u *PasskeyCredentialUpsertBulk) SetAaguid(v string) *PasskeyCredentialUpsertBulk {
	return u.Update(func(s *PasskeyCredentialUpsert) {
		s.SetAaguid(v)
	})
}

// UpdateAaguid sets the "aaguid" field to the value that was provided on create.
func (u *PasskeyCredentialUpsertBulk) UpdateAaguid() *PasskeyCredentialUpsertBulk {
	return u.Update(func(s *PasskeyCredentialUpsert) {
		s.UpdateAaguid()
	})
}

// SetBackupEligible sets the "backup_eligible" field.
func (u *PasskeyCredentialUpsertBulk) SetBackupEligible(v bool) *PasskeyCredentialUpsertBulk {
	return u.Update(func(s *PasskeyCredentialUpsert) {
		s.SetBackupEligible(v)
	})
}

// UpdateBackupEligible sets the "backup_eligible" field to the value that was provided on create.
func (u *PasskeyCredentialUpsertBulk) UpdateBackupEligible() *PasskeyCredentialUpsertBulk {
	return u.Update(func(s *PasskeyCredentialUpsert) {
		s.UpdateBackupEligible()
	})
}

// SetBackupState sets the "backup_state" field.
func (u *PasskeyCredentialUpsertBulk) SetBackupState(v bool) *PasskeyCredentialUpsertBulk {
	return u.Update(func(s *PasskeyCredentialUpsert) {
		s.SetBackupState(v)
	})
}

// UpdateBackupState sets the "backup_state" field to the value that was provided on create.
func (u *PasskeyCredentialUpsertBulk) UpdateBackupState() *PasskeyCredentialUpsertBulk {
	return u.Update(func(s *PasskeyCredentialUpsert) {
		s.UpdateBackupState()
	})
}

// SetFriendlyName sets the "friendly_name" field.
func (u *PasskeyCredentialUpsertBulk) SetFriendlyName(v string) *PasskeyCredentialUpsertBulk {
	return u.Update(func(s *PasskeyCredentialUpsert) {
		s.SetFriendlyName(v)
	})
}

// UpdateFriendlyName sets the "friendly_name" field to the value that was provided on create.
func (u *PasskeyCredentialUpsertBulk) UpdateFriendlyName() *PasskeyCredentialUpsertBulk {
	return u.Update(func(s *PasskeyCredentialUpsert) {
		s.UpdateFriendlyName()
	})
}

// SetLastUsedAt sets the "last_used_at" field.
func (u *PasskeyCredentialUpsertBulk) SetLastUsedAt(v time.Time) *PasskeyCredentialUpsertBulk {
	return u.Update(func(s *PasskeyCredentialUpsert) {
		s.SetLastUsedAt(v)
	})
}

// UpdateLastUsedAt sets the "last_used_at" field to the value that was provided on create.
func (u *PasskeyCredentialUpsertBulk) UpdateLastUsedAt() *PasskeyCredentialUpsertBulk {
	return u.Update(func(s *PasskeyCredentialUpsert) {
		s.UpdateLastUsedAt()
	})
}

// ClearLastUsedAt clears the value of the "last_used_at" field.
func (u *PasskeyCredentialUpsertBulk) ClearLastUsedAt() *PasskeyCredentialUpsertBulk {
	return u.Update(func(s *PasskeyCredentialUpsert) {
		s.ClearLastUsedAt()
	})
}

// SetRevokedAt sets the "revoked_at" field.
func (u *PasskeyCredentialUpsertBulk) SetRevokedAt(v time.Time) *PasskeyCredentialUpsertBulk {
	return u.Update(func(s *PasskeyCredentialUpsert) {
		s.SetRevokedAt(v)
	})
}

// UpdateRevokedAt sets the "revoked_at" field to the value that was provided on create.
func (u *PasskeyCredentialUpsertBulk) UpdateRevokedAt() *PasskeyCredentialUpsertBulk {
	return u.Update(func(s *PasskeyCredentialUpsert) {
		s.UpdateRevokedAt()
	})
}

// ClearRevokedAt clears the value of the "revoked_at" field.
func (u *PasskeyCredentialUpsertBulk) ClearRevokedAt() *PasskeyCredentialUpsertBulk {
	return u.Update(func(s *PasskeyCredentialUpsert) {
		s.ClearRevokedAt()
	})
}

// Exec executes the query.
func (u *PasskeyCredentialUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the PasskeyCredentialCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for PasskeyCredentialCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *PasskeyCredentialUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
