// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/dialect/sql/sqljson"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/passkeycredential"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
	"github.com/Wei-Shaw/sub2api/ent/user"
)

// PasskeyCredentialUpdate is the builder for updating PasskeyCredential entities.
type PasskeyCredentialUpdate struct {
	config
	hooks    []Hook
	mutation *PasskeyCredentialMutation
}

// Where appends a list predicates to the PasskeyCredentialUpdate builder.
func (_u *PasskeyCredentialUpdate) Where(ps ...predicate.PasskeyCredential) *PasskeyCredentialUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *PasskeyCredentialUpdate) SetUpdatedAt(v time.Time) *PasskeyCredentialUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *PasskeyCredentialUpdate) SetUserID(v int64) *PasskeyCredentialUpdate {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *PasskeyCredentialUpdate) SetNillableUserID(v *int64) *PasskeyCredentialUpdate {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetCredentialID sets the "credential_id" field.
func (_u *PasskeyCredentialUpdate) SetCredentialID(v string) *PasskeyCredentialUpdate {
	_u.mutation.SetCredentialID(v)
	return _u
}

// SetNillableCredentialID sets the "credential_id" field if the given value is not nil.
func (_u *PasskeyCredentialUpdate) SetNillableCredentialID(v *string) *PasskeyCredentialUpdate {
	if v != nil {
		_u.SetCredentialID(*v)
	}
	return _u
}

// SetPublicKey sets the "public_key" field.
func (_u *PasskeyCredentialUpdate) SetPublicKey(v string) *PasskeyCredentialUpdate {
	_u.mutation.SetPublicKey(v)
	return _u
}

// SetNillablePublicKey sets the "public_key" field if the given value is not nil.
func (_u *PasskeyCredentialUpdate) SetNillablePublicKey(v *string) *PasskeyCredentialUpdate {
	if v != nil {
		_u.SetPublicKey(*v)
	}
	return _u
}

// SetSignCount sets the "sign_count" field.
func (_u *PasskeyCredentialUpdate) SetSignCount(v int64) *PasskeyCredentialUpdate {
	_u.mutation.ResetSignCount()
	_u.mutation.SetSignCount(v)
	return _u
}

// SetNillableSignCount sets the "sign_count" field if the given value is not nil.
func (_u *PasskeyCredentialUpdate) SetNillableSignCount(v *int64) *PasskeyCredentialUpdate {
	if v != nil {
		_u.SetSignCount(*v)
	}
	return _u
}

// AddSignCount adds value to the "sign_count" field.
func (_u *PasskeyCredentialUpdate) AddSignCount(v int64) *PasskeyCredentialUpdate {
	_u.mutation.AddSignCount(v)
	return _u
}

// SetTransports sets the "transports" field.
func (_u *PasskeyCredentialUpdate) SetTransports(v []string) *PasskeyCredentialUpdate {
	_u.mutation.SetTransports(v)
	return _u
}

// AppendTransports appends value to the "transports" field.
func (_u *PasskeyCredentialUpdate) AppendTransports(v []string) *PasskeyCredentialUpdate {
	_u.mutation.AppendTransports(v)
	return _u
}

// ClearTransports clears the value of the "transports" field.
func (_u *PasskeyCredentialUpdate) ClearTransports() *PasskeyCredentialUpdate {
	_u.mutation.ClearTransports()
	return _u
}

// SetAaguid sets the "aaguid" field.
func (_u *PasskeyCredentialUpdate) SetAaguid(v string) *PasskeyCredentialUpdate {
	_u.mutation.SetAaguid(v)
	return _u
}

// SetNillableAaguid sets the "aaguid" field if the given value is not nil.
func (_u *PasskeyCredentialUpdate) SetNillableAaguid(v *string) *PasskeyCredentialUpdate {
	if v != nil {
		_u.SetAaguid(*v)
	}
	return _u
}

// SetBackupEligible sets the "backup_eligible" field.
func (_u *PasskeyCredentialUpdate) SetBackupEligible(v bool) *PasskeyCredentialUpdate {
	_u.mutation.SetBackupEligible(v)
	return _u
}

// SetNillableBackupEligible sets the "backup_eligible" field if the given value is not nil.
func (_u *PasskeyCredentialUpdate) SetNillableBackupEligible(v *bool) *PasskeyCredentialUpdate {
	if v != nil {
		_u.SetBackupEligible(*v)
	}
	return _u
}

// SetBackupState sets the "backup_state" field.
func (_u *PasskeyCredentialUpdate) SetBackupState(v bool) *PasskeyCredentialUpdate {
	_u.mutation.SetBackupState(v)
	return _u
}

// SetNillableBackupState sets the "backup_state" field if the given value is not nil.
func (_u *PasskeyCredentialUpdate) SetNillableBackupState(v *bool) *PasskeyCredentialUpdate {
	if v != nil {
		_u.SetBackupState(*v)
	}
	return _u
}

// SetFriendlyName sets the "friendly_name" field.
func (_u *PasskeyCredentialUpdate) SetFriendlyName(v string) *PasskeyCredentialUpdate {
	_u.mutation.SetFriendlyName(v)
	return _u
}

// SetNillableFriendlyName sets the "friendly_name" field if the given value is not nil.
func (_u *PasskeyCredentialUpdate) SetNillableFriendlyName(v *string) *PasskeyCredentialUpdate {
	if v != nil {
		_u.SetFriendlyName(*v)
	}
	return _u
}

// SetLastUsedAt sets the "last_used_at" field.
func (_u *PasskeyCredentialUpdate) SetLastUsedAt(v time.Time) *PasskeyCredentialUpdate {
	_u.mutation.SetLastUsedAt(v)
	return _u
}

// SetNillableLastUsedAt sets the "last_used_at" field if the given value is not nil.
func (_u *PasskeyCredentialUpdate) SetNillableLastUsedAt(v *time.Time) *PasskeyCredentialUpdate {
	if v != nil {
		_u.SetLastUsedAt(*v)
	}
	return _u
}

// ClearLastUsedAt clears the value of the "last_used_at" field.
func (_u *PasskeyCredentialUpdate) ClearLastUsedAt() *PasskeyCredentialUpdate {
	_u.mutation.ClearLastUsedAt()
	return _u
}

// SetRevokedAt sets the "revoked_at" field.
func (_u *PasskeyCredentialUpdate) SetRevokedAt(v time.Time) *PasskeyCredentialUpdate {
	_u.mutation.SetRevokedAt(v)
	return _u
}

// SetNillableRevokedAt sets the "revoked_at" field if the given value is not nil.
func (_u *PasskeyCredentialUpdate) SetNillableRevokedAt(v *time.Time) *PasskeyCredentialUpdate {
	if v != nil {
		_u.SetRevokedAt(*v)
	}
	return _u
}

// ClearRevokedAt clears the value of the "revoked_at" field.
func (_u *PasskeyCredentialUpdate) ClearRevokedAt() *PasskeyCredentialUpdate {
	_u.mutation.ClearRevokedAt()
	return _u
}

// SetUser sets the "user" edge to the User entity.
func (_u *PasskeyCredentialUpdate) SetUser(v *User) *PasskeyCredentialUpdate {
	return _u.SetUserID(v.ID)
}

// Mutation returns the PasskeyCredentialMutation object of the builder.
func (_u *PasskeyCredentialUpdate) Mutation() *PasskeyCredentialMutation {
	return _u.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (_u *PasskeyCredentialUpdate) ClearUser() *PasskeyCredentialUpdate {
	_u.mutation.ClearUser()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *PasskeyCredentialUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *PasskeyCredentialUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *PasskeyCredentialUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *PasskeyCredentialUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *PasskeyCredentialUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := passkeycredential.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *PasskeyCredentialUpdate) check() error {
	if v, ok := _u.mutation.CredentialID(); ok {
		if err := passkeycredential.CredentialIDValidator(v); err != nil {
			return &ValidationError{Name: "credential_id", err: fmt.Errorf(`ent: validator failed for field "PasskeyCredential.credential_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.PublicKey(); ok {
		if err := passkeycredential.PublicKeyValidator(v); err != nil {
			return &ValidationError{Name: "public_key", err: fmt.Errorf(`ent: validator failed for field "PasskeyCredential.public_key": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Aaguid(); ok {
		if err := passkeycredential.AaguidValidator(v); err != nil {
			return &ValidationError{Name: "aaguid", err: fmt.Errorf(`ent: validator failed for field "PasskeyCredential.aaguid": %w`, err)}
		}
	}
	if v, ok := _u.mutation.FriendlyName(); ok {
		if err := passkeycredential.FriendlyNameValidator(v); err != nil {
			return &ValidationError{Name: "friendly_name", err: fmt.Errorf(`ent: validator failed for field "PasskeyCredential.friendly_name": %w`, err)}
		}
	}
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "PasskeyCredential.user"`)
	}
	return nil
}

func (_u *PasskeyCredentialUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(passkeycredential.Table, passkeycredential.Columns, sqlgraph.NewFieldSpec(passkeycredential.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(passkeycredential.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.CredentialID(); ok {
		_spec.SetField(passkeycredential.FieldCredentialID, field.TypeString, value)
	}
	if value, ok := _u.mutation.PublicKey(); ok {
		_spec.SetField(passkeycredential.FieldPublicKey, field.TypeString, value)
	}
	if value, ok := _u.mutation.SignCount(); ok {
		_spec.SetField(passkeycredential.FieldSignCount, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedSignCount(); ok {
		_spec.AddField(passkeycredential.FieldSignCount, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.Transports(); ok {
		_spec.SetField(passkeycredential.FieldTransports, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedTransports(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, passkeycredential.FieldTransports, value)
		})
	}
	if _u.mutation.TransportsCleared() {
		_spec.ClearField(passkeycredential.FieldTransports, field.TypeJSON)
	}
	if value, ok := _u.mutation.Aaguid(); ok {
		_spec.SetField(passkeycredential.FieldAaguid, field.TypeString, value)
	}
	if value, ok := _u.mutation.BackupEligible(); ok {
		_spec.SetField(passkeycredential.FieldBackupEligible, field.TypeBool, value)
	}
	if value, ok := _u.mutation.BackupState(); ok {
		_spec.SetField(passkeycredential.FieldBackupState, field.TypeBool, value)
	}
	if value, ok := _u.mutation.FriendlyName(); ok {
		_spec.SetField(passkeycredential.FieldFriendlyName, field.TypeString, value)
	}
	if value, ok := _u.mutation.LastUsedAt(); ok {
		_spec.SetField(passkeycredential.FieldLastUsedAt, field.TypeTime, value)
	}
	if _u.mutation.LastUsedAtCleared() {
		_spec.ClearField(passkeycredential.FieldLastUsedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.RevokedAt(); ok {
		_spec.SetField(passkeycredential.FieldRevokedAt, field.TypeTime, value)
	}
	if _u.mutation.RevokedAtCleared() {
		_spec.ClearField(passkeycredential.FieldRevokedAt, field.TypeTime)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   passkeycredential.UserTable,
			Columns: []string{passkeycredential.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   passkeycredential.UserTable,
			Columns: []string{passkeycredential.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{passkeycredential.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// PasskeyCredentialUpdateOne is the builder for updating a single PasskeyCredential entity.
type PasskeyCredentialUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *PasskeyCredentialMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *PasskeyCredentialUpdateOne) SetUpdatedAt(v time.Time) *PasskeyCredentialUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *PasskeyCredentialUpdateOne) SetUserID(v int64) *PasskeyCredentialUpdateOne {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *PasskeyCredentialUpdateOne) SetNillableUserID(v *int64) *PasskeyCredentialUpdateOne {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetCredentialID sets the "credential_id" field.
func (_u *PasskeyCredentialUpdateOne) SetCredentialID(v string) *PasskeyCredentialUpdateOne {
	_u.mutation.SetCredentialID(v)
	return _u
}

// SetNillableCredentialID sets the "credential_id" field if the given value is not nil.
func (_u *PasskeyCredentialUpdateOne) SetNillableCredentialID(v *string) *PasskeyCredentialUpdateOne {
	if v != nil {
		_u.SetCredentialID(*v)
	}
	return _u
}

// SetPublicKey sets the "public_key" field.
func (_u *PasskeyCredentialUpdateOne) SetPublicKey(v string) *PasskeyCredentialUpdateOne {
	_u.mutation.SetPublicKey(v)
	return _u
}

// SetNillablePublicKey sets the "public_key" field if the given value is not nil.
func (_u *PasskeyCredentialUpdateOne) SetNillablePublicKey(v *string) *PasskeyCredentialUpdateOne {
	if v != nil {
		_u.SetPublicKey(*v)
	}
	return _u
}

// SetSignCount sets the "sign_count" field.
func (_u *PasskeyCredentialUpdateOne) SetSignCount(v int64) *PasskeyCredentialUpdateOne {
	_u.mutation.ResetSignCount()
	_u.mutation.SetSignCount(v)
	return _u
}

// SetNillableSignCount sets the "sign_count" field if the given value is not nil.
func (_u *PasskeyCredentialUpdateOne) SetNillableSignCount(v *int64) *PasskeyCredentialUpdateOne {
	if v != nil {
		_u.SetSignCount(*v)
	}
	return _u
}

// AddSignCount adds value to the "sign_count" field.
func (_u *PasskeyCredentialUpdateOne) AddSignCount(v int64) *PasskeyCredentialUpdateOne {
	_u.mutation.AddSignCount(v)
	return _u
}

// SetTransports sets the "transports" field.
func (_u *PasskeyCredentialUpdateOne) SetTransports(v []string) *PasskeyCredentialUpdateOne {
	_u.mutation.SetTransports(v)
	return _u
}

// AppendTransports appends value to the "transports" field.
func (_u *PasskeyCredentialUpdateOne) AppendTransports(v []string) *PasskeyCredentialUpdateOne {
	_u.mutation.AppendTransports(v)
	return _u
}

// ClearTransports clears the value of the "transports" field.
func (_u *PasskeyCredentialUpdateOne) ClearTransports() *PasskeyCredentialUpdateOne {
	_u.mutation.ClearTransports()
	return _u
}

// SetAaguid sets the "aaguid" field.
func (_u *PasskeyCredentialUpdateOne) SetAaguid(v string) *PasskeyCredentialUpdateOne {
	_u.mutation.SetAaguid(v)
	return _u
}

// SetNillableAaguid sets the "aaguid" field if the given value is not nil.
func (_u *PasskeyCredentialUpdateOne) SetNillableAaguid(v *string) *PasskeyCredentialUpdateOne {
	if v != nil {
		_u.SetAaguid(*v)
	}
	return _u
}

// SetBackupEligible sets the "backup_eligible" field.
func (_u *PasskeyCredentialUpdateOne) SetBackupEligible(v bool) *PasskeyCredentialUpdateOne {
	_u.mutation.SetBackupEligible(v)
	return _u
}

// SetNillableBackupEligible sets the "backup_eligible" field if the given value is not nil.
func (_u *PasskeyCredentialUpdateOne) SetNillableBackupEligible(v *bool) *PasskeyCredentialUpdateOne {
	if v != nil {
		_u.SetBackupEligible(*v)
	}
	return _u
}

// SetBackupState sets the "backup_state" field.
func (_u *PasskeyCredentialUpdateOne) SetBackupState(v bool) *PasskeyCredentialUpdateOne {
	_u.mutation.SetBackupState(v)
	return _u
}

// SetNillableBackupState sets the "backup_state" field if the given value is not nil.
func (_u *PasskeyCredentialUpdateOne) SetNillableBackupState(v *bool) *PasskeyCredentialUpdateOne {
	if v != nil {
		_u.SetBackupState(*v)
	}
	return _u
}

// SetFriendlyName sets the "friendly_name" field.
func (_u *PasskeyCredentialUpdateOne) SetFriendlyName(v string) *PasskeyCredentialUpdateOne {
	_u.mutation.SetFriendlyName(v)
	return _u
}

// SetNillableFriendlyName sets the "friendly_name" field if the given value is not nil.
func (_u *PasskeyCredentialUpdateOne) SetNillableFriendlyName(v *string) *PasskeyCredentialUpdateOne {
	if v != nil {
		_u.SetFriendlyName(*v)
	}
	return _u
}

// SetLastUsedAt sets the "last_used_at" field.
func (_u *PasskeyCredentialUpdateOne) SetLastUsedAt(v time.Time) *PasskeyCredentialUpdateOne {
	_u.mutation.SetLastUsedAt(v)
	return _u
}

// SetNillableLastUsedAt sets the "last_used_at" field if the given value is not nil.
func (_u *PasskeyCredentialUpdateOne) SetNillableLastUsedAt(v *time.Time) *PasskeyCredentialUpdateOne {
	if v != nil {
		_u.SetLastUsedAt(*v)
	}
	return _u
}

// ClearLastUsedAt clears the value of the "last_used_at" field.
func (_u *PasskeyCredentialUpdateOne) ClearLastUsedAt() *PasskeyCredentialUpdateOne {
	_u.mutation.ClearLastUsedAt()
	return _u
}

// SetRevokedAt sets the "revoked_at" field.
func (_u *PasskeyCredentialUpdateOne) SetRevokedAt(v time.Time) *PasskeyCredentialUpdateOne {
	_u.mutation.SetRevokedAt(v)
	return _u
}

// SetNillableRevokedAt sets the "revoked_at" field if the given value is not nil.
func (_u *PasskeyCredentialUpdateOne) SetNillableRevokedAt(v *time.Time) *PasskeyCredentialUpdateOne {
	if v != nil {
		_u.SetRevokedAt(*v)
	}
	return _u
}

// ClearRevokedAt clears the value of the "revoked_at" field.
func (_u *PasskeyCredentialUpdateOne) ClearRevokedAt() *PasskeyCredentialUpdateOne {
	_u.mutation.ClearRevokedAt()
	return _u
}

// SetUser sets the "user" edge to the User entity.
func (_u *PasskeyCredentialUpdateOne) SetUser(v *User) *PasskeyCredentialUpdateOne {
	return _u.SetUserID(v.ID)
}

// Mutation returns the PasskeyCredentialMutation object of the builder.
func (_u *PasskeyCredentialUpdateOne) Mutation() *PasskeyCredentialMutation {
	return _u.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (_u *PasskeyCredentialUpdateOne) ClearUser() *PasskeyCredentialUpdateOne {
	_u.mutation.ClearUser()
	return _u
}

// Where appends a list predicates to the PasskeyCredentialUpdate builder.
func (_u *PasskeyCredentialUpdateOne) Where(ps ...predicate.PasskeyCredential) *PasskeyCredentialUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *PasskeyCredentialUpdateOne) Select(field string, fields ...string) *PasskeyCredentialUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated PasskeyCredential entity.
func (_u *PasskeyCredentialUpdateOne) Save(ctx context.Context) (*PasskeyCredential, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *PasskeyCredentialUpdateOne) SaveX(ctx context.Context) *PasskeyCredential {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *PasskeyCredentialUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *PasskeyCredentialUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *PasskeyCredentialUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := passkeycredential.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *PasskeyCredentialUpdateOne) check() error {
	if v, ok := _u.mutation.CredentialID(); ok {
		if err := passkeycredential.CredentialIDValidator(v); err != nil {
			return &ValidationError{Name: "credential_id", err: fmt.Errorf(`ent: validator failed for field "PasskeyCredential.credential_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.PublicKey(); ok {
		if err := passkeycredential.PublicKeyValidator(v); err != nil {
			return &ValidationError{Name: "public_key", err: fmt.Errorf(`ent: validator failed for field "PasskeyCredential.public_key": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Aaguid(); ok {
		if err := passkeycredential.AaguidValidator(v); err != nil {
			return &ValidationError{Name: "aaguid", err: fmt.Errorf(`ent: validator failed for field "PasskeyCredential.aaguid": %w`, err)}
		}
	}
	if v, ok := _u.mutation.FriendlyName(); ok {
		if err := passkeycredential.FriendlyNameValidator(v); err != nil {
			return &ValidationError{Name: "friendly_name", err: fmt.Errorf(`ent: validator failed for field "PasskeyCredential.friendly_name": %w`, err)}
		}
	}
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "PasskeyCredential.user"`)
	}
	return nil
}

func (_u *PasskeyCredentialUpdateOne) sqlSave(ctx context.Context) (_node *PasskeyCredential, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(passkeycredential.Table, passkeycredential.Columns, sqlgraph.NewFieldSpec(passkeycredential.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "PasskeyCredential.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, passkeycredential.FieldID)
		for _, f := range fields {
			if !passkeycredential.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != passkeycredential.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(passkeycredential.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.CredentialID(); ok {
		_spec.SetField(passkeycredential.FieldCredentialID, field.TypeString, value)
	}
	if value, ok := _u.mutation.PublicKey(); ok {
		_spec.SetField(passkeycredential.FieldPublicKey, field.TypeString, value)
	}
	if value, ok := _u.mutation.SignCount(); ok {
		_spec.SetField(passkeycredential.FieldSignCount, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedSignCount(); ok {
		_spec.AddField(passkeycredential.FieldSignCount, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.Transports(); ok {
		_spec.SetField(passkeycredential.FieldTransports, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedTransports(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, passkeycredential.FieldTransports, value)
		})
	}
	if _u.mutation.TransportsCleared() {
		_spec.ClearField(passkeycredential.FieldTransports, field.TypeJSON)
	}
	if value, ok := _u.mutation.Aaguid(); ok {
		_spec.SetField(passkeycredential.FieldAaguid, field.TypeString, value)
	}
	if value, ok := _u.mutation.BackupEligible(); ok {
		_spec.SetField(passkeycredential.FieldBackupEligible, field.TypeBool, value)
	}
	if value, ok := _u.mutation.BackupState(); ok {
		_spec.SetField(passkeycredential.FieldBackupState, field.TypeBool, value)
	}
	if value, ok := _u.mutation.FriendlyName(); ok {
		_spec.SetField(passkeycredential.FieldFriendlyName, field.TypeString, value)
	}
	if value, ok := _u.mutation.LastUsedAt(); ok {
		_spec.SetField(passkeycredential.FieldLastUsedAt, field.TypeTime, value)
	}
	if _u.mutation.LastUsedAtCleared() {
		_spec.ClearField(passkeycredential.FieldLastUsedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.RevokedAt(); ok {
		_spec.SetField(passkeycredential.FieldRevokedAt, field.TypeTime, value)
	}
	if _u.mutation.RevokedAtCleared() {
		_spec.ClearField(passkeycredential.FieldRevokedAt, field.TypeTime)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   passkeycredential.UserTable,
			Columns: []string{passkeycredential.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   passkeycredential.UserTable,
			Columns: []string{passkeycredential.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &PasskeyCredential{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{passkeycredential.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
