// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/user"
	"github.com/Wei-Shaw/sub2api/ent/usercheckin"
)

// UserCheckIn is the model entity for the UserCheckIn schema.
type UserCheckIn struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// 签到用户 ID
	UserID int64 `json:"user_id,omitempty"`
	// 业务签到日期
	CheckinDate time.Time `json:"checkin_date,omitempty"`
	// 签到奖励快照
	RewardAmount float64 `json:"reward_amount,omitempty"`
	// 签到时间
	CreatedAt time.Time `json:"created_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the UserCheckInQuery when eager-loading is set.
	Edges        UserCheckInEdges `json:"edges"`
	selectValues sql.SelectValues
}

// UserCheckInEdges holds the relations/edges for other nodes in the graph.
type UserCheckInEdges struct {
	// User holds the value of the user edge.
	User *User `json:"user,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// UserOrErr returns the User value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e UserCheckInEdges) UserOrErr() (*User, error) {
	if e.User != nil {
		return e.User, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: user.Label}
	}
	return nil, &NotLoadedError{edge: "user"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*UserCheckIn) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case usercheckin.FieldRewardAmount:
			values[i] = new(sql.NullFloat64)
		case usercheckin.FieldID, usercheckin.FieldUserID:
			values[i] = new(sql.NullInt64)
		case usercheckin.FieldCheckinDate, usercheckin.FieldCreatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the UserCheckIn fields.
func (_m *UserCheckIn) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case usercheckin.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case usercheckin.FieldUserID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field user_id", values[i])
			} else if value.Valid {
				_m.UserID = value.Int64
			}
		case usercheckin.FieldCheckinDate:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field checkin_date", values[i])
			} else if value.Valid {
				_m.CheckinDate = value.Time
			}
		case usercheckin.FieldRewardAmount:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field reward_amount", values[i])
			} else if value.Valid {
				_m.RewardAmount = value.Float64
			}
		case usercheckin.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the UserCheckIn.
// This includes values selected through modifiers, order, etc.
func (_m *UserCheckIn) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryUser queries the "user" edge of the UserCheckIn entity.
func (_m *UserCheckIn) QueryUser() *UserQuery {
	return NewUserCheckInClient(_m.config).QueryUser(_m)
}

// Update returns a builder for updating this UserCheckIn.
// Note that you need to call UserCheckIn.Unwrap() before calling this method if this UserCheckIn
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *UserCheckIn) Update() *UserCheckInUpdateOne {
	return NewUserCheckInClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the UserCheckIn entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *UserCheckIn) Unwrap() *UserCheckIn {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: UserCheckIn is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *UserCheckIn) String() string {
	var builder strings.Builder
	builder.WriteString("UserCheckIn(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("user_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.UserID))
	builder.WriteString(", ")
	builder.WriteString("checkin_date=")
	builder.WriteString(_m.CheckinDate.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("reward_amount=")
	builder.WriteString(fmt.Sprintf("%v", _m.RewardAmount))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// UserCheckIns is a parsable slice of UserCheckIn.
type UserCheckIns []*UserCheckIn
