// Code generated by ent, DO NOT EDIT.

package useraccountbinding

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.UserAccountBinding {
	return predicate.UserAccountBinding(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.UserAccountBinding {
	return predicate.UserAccountBinding(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.UserAccountBinding {
	return predicate.UserAccountBinding(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.UserAccountBinding {
	return predicate.UserAccountBinding(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.UserAccountBinding {
	return predicate.UserAccountBinding(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.UserAccountBinding {
	return predicate.UserAccountBinding(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.UserAccountBinding {
	return predicate.UserAccountBinding(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.UserAccountBinding {
	return predicate.UserAccountBinding(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.UserAccountBinding {
	return predicate.UserAccountBinding(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.UserAccountBinding {
	return predicate.UserAccountBinding(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.UserAccountBinding {
	return predicate.UserAccountBinding(sql.FieldEQ(FieldUpdatedAt, v))
}

// ProjectFp applies equality check predicate on the "project_fp" field. It's identical to ProjectFpEQ.
func ProjectFp(v string) predicate.UserAccountBinding {
	return predicate.UserAccountBinding(sql.FieldEQ(FieldProjectFp, v))
}

// AccountID applies equality check predicate on the "account_id" field. It's identical to AccountIDEQ.
func AccountID(v int64) predicate.UserAccountBinding {
	return predicate.UserAccountBinding(sql.FieldEQ(FieldAccountID, v))
}

// GroupID applies equality check predicate on the "group_id" field. It's identical to GroupIDEQ.
func GroupID(v int64) predicate.UserAccountBinding {
	return predicate.UserAccountBinding(sql.FieldEQ(FieldGroupID, v))
}

// ExpiresAt applies equality check predicate on the "expires_at" field. It's identical to ExpiresAtEQ.
func ExpiresAt(v time.Time) predicate.UserAccountBinding {
	return predicate.UserAccountBinding(sql.FieldEQ(FieldExpiresAt, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.UserAccountBinding {
	return predicate.UserAccountBinding(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.UserAccountBinding {
	return predicate.UserAccountBinding(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.UserAccountBinding {
	return predicate.UserAccountBinding(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.UserAccountBinding {
	return predicate.UserAccountBinding(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.UserAccountBinding {
	return predicate.UserAccountBinding(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.UserAccountBinding {
	return predicate.UserAccountBinding(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.UserAccountBinding {
	return predicate.UserAccountBinding(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.UserAccountBinding {
	return predicate.UserAccountBinding(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.UserAccountBinding {
	return predicate.UserAccountBinding(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.UserAccountBinding {
	return predicate.UserAccountBinding(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.UserAccountBinding {
	return predicate.UserAccountBinding(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.UserAccountBinding {
	return predicate.UserAccountBinding(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.UserAccountBinding {
	return predicate.UserAccountBinding(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.UserAccountBinding {
	return predicate.UserAccountBinding(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.UserAccountBinding {
	return predicate.UserAccountBinding(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.UserAccountBinding {
	return predicate.UserAccountBinding(sql.FieldLTE(FieldUpdatedAt, v))
}

// ProjectFpEQ applies the EQ predicate on the "project_fp" field.
func ProjectFpEQ(v string) predicate.UserAccountBinding {
	return predicate.UserAccountBinding(sql.FieldEQ(FieldProjectFp, v))
}

// ProjectFpNEQ applies the NEQ predicate on the "project_fp" field.
func ProjectFpNEQ(v string) predicate.UserAccountBinding {
	return predicate.UserAccountBinding(sql.FieldNEQ(FieldProjectFp, v))
}

// ProjectFpIn applies the In predicate on the "project_fp" field.
func ProjectFpIn(vs ...string) predicate.UserAccountBinding {
	return predicate.UserAccountBinding(sql.FieldIn(FieldProjectFp, vs...))
}

// ProjectFpNotIn applies the NotIn predicate on the "project_fp" field.
func ProjectFpNotIn(vs ...string) predicate.UserAccountBinding {
	return predicate.UserAccountBinding(sql.FieldNotIn(FieldProjectFp, vs...))
}

// ProjectFpGT applies the GT predicate on the "project_fp" field.
func ProjectFpGT(v string) predicate.UserAccountBinding {
	return predicate.UserAccountBinding(sql.FieldGT(FieldProjectFp, v))
}

// ProjectFpGTE applies the GTE predicate on the "project_fp" field.
func ProjectFpGTE(v string) predicate.UserAccountBinding {
	return predicate.UserAccountBinding(sql.FieldGTE(FieldProjectFp, v))
}

// ProjectFpLT applies the LT predicate on the "project_fp" field.
func ProjectFpLT(v string) predicate.UserAccountBinding {
	return predicate.UserAccountBinding(sql.FieldLT(FieldProjectFp, v))
}

// ProjectFpLTE applies the LTE predicate on the "project_fp" field.
func ProjectFpLTE(v string) predicate.UserAccountBinding {
	return predicate.UserAccountBinding(sql.FieldLTE(FieldProjectFp, v))
}

// ProjectFpContains applies the Contains predicate on the "project_fp" field.
func ProjectFpContains(v string) predicate.UserAccountBinding {
	return predicate.UserAccountBinding(sql.FieldContains(FieldProjectFp, v))
}

// ProjectFpHasPrefix applies the HasPrefix predicate on the "project_fp" field.
func ProjectFpHasPrefix(v string) predicate.UserAccountBinding {
	return predicate.UserAccountBinding(sql.FieldHasPrefix(FieldProjectFp, v))
}

// ProjectFpHasSuffix applies the HasSuffix predicate on the "project_fp" field.
func ProjectFpHasSuffix(v string) predicate.UserAccountBinding {
	return predicate.UserAccountBinding(sql.FieldHasSuffix(FieldProjectFp, v))
}

// ProjectFpEqualFold applies the EqualFold predicate on the "project_fp" field.
func ProjectFpEqualFold(v string) predicate.UserAccountBinding {
	return predicate.UserAccountBinding(sql.FieldEqualFold(FieldProjectFp, v))
}

// ProjectFpContainsFold applies the ContainsFold predicate on the "project_fp" field.
func ProjectFpContainsFold(v string) predicate.UserAccountBinding {
	return predicate.UserAccountBinding(sql.FieldContainsFold(FieldProjectFp, v))
}

// AccountIDEQ applies the EQ predicate on the "account_id" field.
func AccountIDEQ(v int64) predicate.UserAccountBinding {
	return predicate.UserAccountBinding(sql.FieldEQ(FieldAccountID, v))
}

// AccountIDNEQ applies the NEQ predicate on the "account_id" field.
func AccountIDNEQ(v int64) predicate.UserAccountBinding {
	return predicate.UserAccountBinding(sql.FieldNEQ(FieldAccountID, v))
}

// AccountIDIn applies the In predicate on the "account_id" field.
func AccountIDIn(vs ...int64) predicate.UserAccountBinding {
	return predicate.UserAccountBinding(sql.FieldIn(FieldAccountID, vs...))
}

// AccountIDNotIn applies the NotIn predicate on the "account_id" field.
func AccountIDNotIn(vs ...int64) predicate.UserAccountBinding {
	return predicate.UserAccountBinding(sql.FieldNotIn(FieldAccountID, vs...))
}

// AccountIDGT applies the GT predicate on the "account_id" field.
func AccountIDGT(v int64) predicate.UserAccountBinding {
	return predicate.UserAccountBinding(sql.FieldGT(FieldAccountID, v))
}

// AccountIDGTE applies the GTE predicate on the "account_id" field.
func AccountIDGTE(v int64) predicate.UserAccountBinding {
	return predicate.UserAccountBinding(sql.FieldGTE(FieldAccountID, v))
}

// AccountIDLT applies the LT predicate on the "account_id" field.
func AccountIDLT(v int64) predicate.UserAccountBinding {
	return predicate.UserAccountBinding(sql.FieldLT(FieldAccountID, v))
}

// AccountIDLTE applies the LTE predicate on the "account_id" field.
func AccountIDLTE(v int64) predicate.UserAccountBinding {
	return predicate.UserAccountBinding(sql.FieldLTE(FieldAccountID, v))
}

// GroupIDEQ applies the EQ predicate on the "group_id" field.
func GroupIDEQ(v int64) predicate.UserAccountBinding {
	return predicate.UserAccountBinding(sql.FieldEQ(FieldGroupID, v))
}

// GroupIDNEQ applies the NEQ predicate on the "group_id" field.
func GroupIDNEQ(v int64) predicate.UserAccountBinding {
	return predicate.UserAccountBinding(sql.FieldNEQ(FieldGroupID, v))
}

// GroupIDIn applies the In predicate on the "group_id" field.
func GroupIDIn(vs ...int64) predicate.UserAccountBinding {
	return predicate.UserAccountBinding(sql.FieldIn(FieldGroupID, vs...))
}

// GroupIDNotIn applies the NotIn predicate on the "group_id" field.
func GroupIDNotIn(vs ...int64) predicate.UserAccountBinding {
	return predicate.UserAccountBinding(sql.FieldNotIn(FieldGroupID, vs...))
}

// GroupIDGT applies the GT predicate on the "group_id" field.
func GroupIDGT(v int64) predicate.UserAccountBinding {
	return predicate.UserAccountBinding(sql.FieldGT(FieldGroupID, v))
}

// GroupIDGTE applies the GTE predicate on the "group_id" field.
func GroupIDGTE(v int64) predicate.UserAccountBinding {
	return predicate.UserAccountBinding(sql.FieldGTE(FieldGroupID, v))
}

// GroupIDLT applies the LT predicate on the "group_id" field.
func GroupIDLT(v int64) predicate.UserAccountBinding {
	return predicate.UserAccountBinding(sql.FieldLT(FieldGroupID, v))
}

// GroupIDLTE applies the LTE predicate on the "group_id" field.
func GroupIDLTE(v int64) predicate.UserAccountBinding {
	return predicate.UserAccountBinding(sql.FieldLTE(FieldGroupID, v))
}

// ExpiresAtEQ applies the EQ predicate on the "expires_at" field.
func ExpiresAtEQ(v time.Time) predicate.UserAccountBinding {
	return predicate.UserAccountBinding(sql.FieldEQ(FieldExpiresAt, v))
}

// ExpiresAtNEQ applies the NEQ predicate on the "expires_at" field.
func ExpiresAtNEQ(v time.Time) predicate.UserAccountBinding {
	return predicate.UserAccountBinding(sql.FieldNEQ(FieldExpiresAt, v))
}

// ExpiresAtIn applies the In predicate on the "expires_at" field.
func ExpiresAtIn(vs ...time.Time) predicate.UserAccountBinding {
	return predicate.UserAccountBinding(sql.FieldIn(FieldExpiresAt, vs...))
}

// ExpiresAtNotIn applies the NotIn predicate on the "expires_at" field.
func ExpiresAtNotIn(vs ...time.Time) predicate.UserAccountBinding {
	return predicate.UserAccountBinding(sql.FieldNotIn(FieldExpiresAt, vs...))
}

// ExpiresAtGT applies the GT predicate on the "expires_at" field.
func ExpiresAtGT(v time.Time) predicate.UserAccountBinding {
	return predicate.UserAccountBinding(sql.FieldGT(FieldExpiresAt, v))
}

// ExpiresAtGTE applies the GTE predicate on the "expires_at" field.
func ExpiresAtGTE(v time.Time) predicate.UserAccountBinding {
	return predicate.UserAccountBinding(sql.FieldGTE(FieldExpiresAt, v))
}

// ExpiresAtLT applies the LT predicate on the "expires_at" field.
func ExpiresAtLT(v time.Time) predicate.UserAccountBinding {
	return predicate.UserAccountBinding(sql.FieldLT(FieldExpiresAt, v))
}

// ExpiresAtLTE applies the LTE predicate on the "expires_at" field.
func ExpiresAtLTE(v time.Time) predicate.UserAccountBinding {
	return predicate.UserAccountBinding(sql.FieldLTE(FieldExpiresAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.UserAccountBinding) predicate.UserAccountBinding {
	return predicate.UserAccountBinding(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.UserAccountBinding) predicate.UserAccountBinding {
	return predicate.UserAccountBinding(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.UserAccountBinding) predicate.UserAccountBinding {
	return predicate.UserAccountBinding(sql.NotPredicates(p))
}
