// Code generated by ent, DO NOT EDIT.

package balancelog

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.BalanceLog {
	return predicate.BalanceLog(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.BalanceLog {
	return predicate.BalanceLog(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.BalanceLog {
	return predicate.BalanceLog(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.BalanceLog {
	return predicate.BalanceLog(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.BalanceLog {
	return predicate.BalanceLog(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.BalanceLog {
	return predicate.BalanceLog(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.BalanceLog {
	return predicate.BalanceLog(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.BalanceLog {
	return predicate.BalanceLog(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.BalanceLog {
	return predicate.BalanceLog(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.BalanceLog {
	return predicate.BalanceLog(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.BalanceLog {
	return predicate.BalanceLog(sql.FieldEQ(FieldUpdatedAt, v))
}

// UserID applies equality check predicate on the "user_id" field. It's identical to UserIDEQ.
func UserID(v int64) predicate.BalanceLog {
	return predicate.BalanceLog(sql.FieldEQ(FieldUserID, v))
}

// ChangeType applies equality check predicate on the "change_type" field. It's identical to ChangeTypeEQ.
func ChangeType(v string) predicate.BalanceLog {
	return predicate.BalanceLog(sql.FieldEQ(FieldChangeType, v))
}

// Amount applies equality check predicate on the "amount" field. It's identical to AmountEQ.
func Amount(v float64) predicate.BalanceLog {
	return predicate.BalanceLog(sql.FieldEQ(FieldAmount, v))
}

// BalanceBefore applies equality check predicate on the "balance_before" field. It's identical to BalanceBeforeEQ.
func BalanceBefore(v float64) predicate.BalanceLog {
	return predicate.BalanceLog(sql.FieldEQ(FieldBalanceBefore, v))
}

// BalanceAfter applies equality check predicate on the "balance_after" field. It's identical to BalanceAfterEQ.
func BalanceAfter(v float64) predicate.BalanceLog {
	return predicate.BalanceLog(sql.FieldEQ(FieldBalanceAfter, v))
}

// RelatedOrderNo applies equality check predicate on the "related_order_no" field. It's identical to RelatedOrderNoEQ.
func RelatedOrderNo(v string) predicate.BalanceLog {
	return predicate.BalanceLog(sql.FieldEQ(FieldRelatedOrderNo, v))
}

// Description applies equality check predicate on the "description" field. It's identical to DescriptionEQ.
func Description(v string) predicate.BalanceLog {
	return predicate.BalanceLog(sql.FieldEQ(FieldDescription, v))
}

// OperatorID applies equality check predicate on the "operator_id" field. It's identical to OperatorIDEQ.
func OperatorID(v int64) predicate.BalanceLog {
	return predicate.BalanceLog(sql.FieldEQ(FieldOperatorID, v))
}

// OperatorType applies equality check predicate on the "operator_type" field. It's identical to OperatorTypeEQ.
func OperatorType(v string) predicate.BalanceLog {
	return predicate.BalanceLog(sql.FieldEQ(FieldOperatorType, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.BalanceLog {
	return predicate.BalanceLog(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.BalanceLog {
	return predicate.BalanceLog(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.BalanceLog {
	return predicate.BalanceLog(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.BalanceLog {
	return predicate.BalanceLog(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.BalanceLog {
	return predicate.BalanceLog(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.BalanceLog {
	return predicate.BalanceLog(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.BalanceLog {
	return predicate.BalanceLog(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.BalanceLog {
	return predicate.BalanceLog(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.BalanceLog {
	return predicate.BalanceLog(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.BalanceLog {
	return predicate.BalanceLog(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.BalanceLog {
	return predicate.BalanceLog(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.BalanceLog {
	return predicate.BalanceLog(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.BalanceLog {
	return predicate.BalanceLog(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.BalanceLog {
	return predicate.BalanceLog(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.BalanceLog {
	return predicate.BalanceLog(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.BalanceLog {
	return predicate.BalanceLog(sql.FieldLTE(FieldUpdatedAt, v))
}

// UserIDEQ applies the EQ predicate on the "user_id" field.
func UserIDEQ(v int64) predicate.BalanceLog {
	return predicate.BalanceLog(sql.FieldEQ(FieldUserID, v))
}

// UserIDNEQ applies the NEQ predicate on the "user_id" field.
func UserIDNEQ(v int64) predicate.BalanceLog {
	return predicate.BalanceLog(sql.FieldNEQ(FieldUserID, v))
}

// UserIDIn applies the In predicate on the "user_id" field.
func UserIDIn(vs ...int64) predicate.BalanceLog {
	return predicate.BalanceLog(sql.FieldIn(FieldUserID, vs...))
}

// UserIDNotIn applies the NotIn predicate on the "user_id" field.
func UserIDNotIn(vs ...int64) predicate.BalanceLog {
	return predicate.BalanceLog(sql.FieldNotIn(FieldUserID, vs...))
}

// ChangeTypeEQ applies the EQ predicate on the "change_type" field.
func ChangeTypeEQ(v string) predicate.BalanceLog {
	return predicate.BalanceLog(sql.FieldEQ(FieldChangeType, v))
}

// ChangeTypeNEQ applies the NEQ predicate on the "change_type" field.
func ChangeTypeNEQ(v string) predicate.BalanceLog {
	return predicate.BalanceLog(sql.FieldNEQ(FieldChangeType, v))
}

// ChangeTypeIn applies the In predicate on the "change_type" field.
func ChangeTypeIn(vs ...string) predicate.BalanceLog {
	return predicate.BalanceLog(sql.FieldIn(FieldChangeType, vs...))
}

// ChangeTypeNotIn applies the NotIn predicate on the "change_type" field.
func ChangeTypeNotIn(vs ...string) predicate.BalanceLog {
	return predicate.BalanceLog(sql.FieldNotIn(FieldChangeType, vs...))
}

// ChangeTypeGT applies the GT predicate on the "change_type" field.
func ChangeTypeGT(v string) predicate.BalanceLog {
	return predicate.BalanceLog(sql.FieldGT(FieldChangeType, v))
}

// ChangeTypeGTE applies the GTE predicate on the "change_type" field.
func ChangeTypeGTE(v string) predicate.BalanceLog {
	return predicate.BalanceLog(sql.FieldGTE(FieldChangeType, v))
}

// ChangeTypeLT applies the LT predicate on the "change_type" field.
func ChangeTypeLT(v string) predicate.BalanceLog {
	return predicate.BalanceLog(sql.FieldLT(FieldChangeType, v))
}

// ChangeTypeLTE applies the LTE predicate on the "change_type" field.
func ChangeTypeLTE(v string) predicate.BalanceLog {
	return predicate.BalanceLog(sql.FieldLTE(FieldChangeType, v))
}

// ChangeTypeContains applies the Contains predicate on the "change_type" field.
func ChangeTypeContains(v string) predicate.BalanceLog {
	return predicate.BalanceLog(sql.FieldContains(FieldChangeType, v))
}

// ChangeTypeHasPrefix applies the HasPrefix predicate on the "change_type" field.
func ChangeTypeHasPrefix(v string) predicate.BalanceLog {
	return predicate.BalanceLog(sql.FieldHasPrefix(FieldChangeType, v))
}

// ChangeTypeHasSuffix applies the HasSuffix predicate on the "change_type" field.
func ChangeTypeHasSuffix(v string) predicate.BalanceLog {
	return predicate.BalanceLog(sql.FieldHasSuffix(FieldChangeType, v))
}

// ChangeTypeEqualFold applies the EqualFold predicate on the "change_type" field.
func ChangeTypeEqualFold(v string) predicate.BalanceLog {
	return predicate.BalanceLog(sql.FieldEqualFold(FieldChangeType, v))
}

// ChangeTypeContainsFold applies the ContainsFold predicate on the "change_type" field.
func ChangeTypeContainsFold(v string) predicate.BalanceLog {
	return predicate.BalanceLog(sql.FieldContainsFold(FieldChangeType, v))
}

// AmountEQ applies the EQ predicate on the "amount" field.
func AmountEQ(v float64) predicate.BalanceLog {
	return predicate.BalanceLog(sql.FieldEQ(FieldAmount, v))
}

// AmountNEQ applies the NEQ predicate on the "amount" field.
func AmountNEQ(v float64) predicate.BalanceLog {
	return predicate.BalanceLog(sql.FieldNEQ(FieldAmount, v))
}

// AmountIn applies the In predicate on the "amount" field.
func AmountIn(vs ...float64) predicate.BalanceLog {
	return predicate.BalanceLog(sql.FieldIn(FieldAmount, vs...))
}

// AmountNotIn applies the NotIn predicate on the "amount" field.
func AmountNotIn(vs ...float64) predicate.BalanceLog {
	return predicate.BalanceLog(sql.FieldNotIn(FieldAmount, vs...))
}

// AmountGT applies the GT predicate on the "amount" field.
func AmountGT(v float64) predicate.BalanceLog {
	return predicate.BalanceLog(sql.FieldGT(FieldAmount, v))
}

// AmountGTE applies the GTE predicate on the "amount" field.
func AmountGTE(v float64) predicate.BalanceLog {
	return predicate.BalanceLog(sql.FieldGTE(FieldAmount, v))
}

// AmountLT applies the LT predicate on the "amount" field.
func AmountLT(v float64) predicate.BalanceLog {
	return predicate.BalanceLog(sql.FieldLT(FieldAmount, v))
}

// AmountLTE applies the LTE predicate on the "amount" field.
func AmountLTE(v float64) predicate.BalanceLog {
	return predicate.BalanceLog(sql.FieldLTE(FieldAmount, v))
}

// BalanceBeforeEQ applies the EQ predicate on the "balance_before" field.
func BalanceBeforeEQ(v float64) predicate.BalanceLog {
	return predicate.BalanceLog(sql.FieldEQ(FieldBalanceBefore, v))
}

// BalanceBeforeNEQ applies the NEQ predicate on the "balance_before" field.
func BalanceBeforeNEQ(v float64) predicate.BalanceLog {
	return predicate.BalanceLog(sql.FieldNEQ(FieldBalanceBefore, v))
}

// BalanceBeforeIn applies the In predicate on the "balance_before" field.
func BalanceBeforeIn(vs ...float64) predicate.BalanceLog {
	return predicate.BalanceLog(sql.FieldIn(FieldBalanceBefore, vs...))
}

// BalanceBeforeNotIn applies the NotIn predicate on the "balance_before" field.
func BalanceBeforeNotIn(vs ...float64) predicate.BalanceLog {
	return predicate.BalanceLog(sql.FieldNotIn(FieldBalanceBefore, vs...))
}

// BalanceBeforeGT applies the GT predicate on the "balance_before" field.
func BalanceBeforeGT(v float64) predicate.BalanceLog {
	return predicate.BalanceLog(sql.FieldGT(FieldBalanceBefore, v))
}

// BalanceBeforeGTE applies the GTE predicate on the "balance_before" field.
func BalanceBeforeGTE(v float64) predicate.BalanceLog {
	return predicate.BalanceLog(sql.FieldGTE(FieldBalanceBefore, v))
}

// BalanceBeforeLT applies the LT predicate on the "balance_before" field.
func BalanceBeforeLT(v float64) predicate.BalanceLog {
	return predicate.BalanceLog(sql.FieldLT(FieldBalanceBefore, v))
}

// BalanceBeforeLTE applies the LTE predicate on the "balance_before" field.
func BalanceBeforeLTE(v float64) predicate.BalanceLog {
	return predicate.BalanceLog(sql.FieldLTE(FieldBalanceBefore, v))
}

// BalanceAfterEQ applies the EQ predicate on the "balance_after" field.
func BalanceAfterEQ(v float64) predicate.BalanceLog {
	return predicate.BalanceLog(sql.FieldEQ(FieldBalanceAfter, v))
}

// BalanceAfterNEQ applies the NEQ predicate on the "balance_after" field.
func BalanceAfterNEQ(v float64) predicate.BalanceLog {
	return predicate.BalanceLog(sql.FieldNEQ(FieldBalanceAfter, v))
}

// BalanceAfterIn applies the In predicate on the "balance_after" field.
func BalanceAfterIn(vs ...float64) predicate.BalanceLog {
	return predicate.BalanceLog(sql.FieldIn(FieldBalanceAfter, vs...))
}

// BalanceAfterNotIn applies the NotIn predicate on the "balance_after" field.
func BalanceAfterNotIn(vs ...float64) predicate.BalanceLog {
	return predicate.BalanceLog(sql.FieldNotIn(FieldBalanceAfter, vs...))
}

// BalanceAfterGT applies the GT predicate on the "balance_after" field.
func BalanceAfterGT(v float64) predicate.BalanceLog {
	return predicate.BalanceLog(sql.FieldGT(FieldBalanceAfter, v))
}

// BalanceAfterGTE applies the GTE predicate on the "balance_after" field.
func BalanceAfterGTE(v float64) predicate.BalanceLog {
	return predicate.BalanceLog(sql.FieldGTE(FieldBalanceAfter, v))
}

// BalanceAfterLT applies the LT predicate on the "balance_after" field.
func BalanceAfterLT(v float64) predicate.BalanceLog {
	return predicate.BalanceLog(sql.FieldLT(FieldBalanceAfter, v))
}

// BalanceAfterLTE applies the LTE predicate on the "balance_after" field.
func BalanceAfterLTE(v float64) predicate.BalanceLog {
	return predicate.BalanceLog(sql.FieldLTE(FieldBalanceAfter, v))
}

// RelatedOrderNoEQ applies the EQ predicate on the "related_order_no" field.
func RelatedOrderNoEQ(v string) predicate.BalanceLog {
	return predicate.BalanceLog(sql.FieldEQ(FieldRelatedOrderNo, v))
}

// RelatedOrderNoNEQ applies the NEQ predicate on the "related_order_no" field.
func RelatedOrderNoNEQ(v string) predicate.BalanceLog {
	return predicate.BalanceLog(sql.FieldNEQ(FieldRelatedOrderNo, v))
}

// RelatedOrderNoIn applies the In predicate on the "related_order_no" field.
func RelatedOrderNoIn(vs ...string) predicate.BalanceLog {
	return predicate.BalanceLog(sql.FieldIn(FieldRelatedOrderNo, vs...))
}

// RelatedOrderNoNotIn applies the NotIn predicate on the "related_order_no" field.
func RelatedOrderNoNotIn(vs ...string) predicate.BalanceLog {
	return predicate.BalanceLog(sql.FieldNotIn(FieldRelatedOrderNo, vs...))
}

// RelatedOrderNoGT applies the GT predicate on the "related_order_no" field.
func RelatedOrderNoGT(v string) predicate.BalanceLog {
	return predicate.BalanceLog(sql.FieldGT(FieldRelatedOrderNo, v))
}

// RelatedOrderNoGTE applies the GTE predicate on the "related_order_no" field.
func RelatedOrderNoGTE(v string) predicate.BalanceLog {
	return predicate.BalanceLog(sql.FieldGTE(FieldRelatedOrderNo, v))
}

// RelatedOrderNoLT applies the LT predicate on the "related_order_no" field.
func RelatedOrderNoLT(v string) predicate.BalanceLog {
	return predicate.BalanceLog(sql.FieldLT(FieldRelatedOrderNo, v))
}

// RelatedOrderNoLTE applies the LTE predicate on the "related_order_no" field.
func RelatedOrderNoLTE(v string) predicate.BalanceLog {
	return predicate.BalanceLog(sql.FieldLTE(FieldRelatedOrderNo, v))
}

// RelatedOrderNoContains applies the Contains predicate on the "related_order_no" field.
func RelatedOrderNoContains(v string) predicate.BalanceLog {
	return predicate.BalanceLog(sql.FieldContains(FieldRelatedOrderNo, v))
}

// RelatedOrderNoHasPrefix applies the HasPrefix predicate on the "related_order_no" field.
func RelatedOrderNoHasPrefix(v string) predicate.BalanceLog {
	return predicate.BalanceLog(sql.FieldHasPrefix(FieldRelatedOrderNo, v))
}

// RelatedOrderNoHasSuffix applies the HasSuffix predicate on the "related_order_no" field.
func RelatedOrderNoHasSuffix(v string) predicate.BalanceLog {
	return predicate.BalanceLog(sql.FieldHasSuffix(FieldRelatedOrderNo, v))
}

// RelatedOrderNoIsNil applies the IsNil predicate on the "related_order_no" field.
func RelatedOrderNoIsNil() predicate.BalanceLog {
	return predicate.BalanceLog(sql.FieldIsNull(FieldRelatedOrderNo))
}

// RelatedOrderNoNotNil applies the NotNil predicate on the "related_order_no" field.
func RelatedOrderNoNotNil() predicate.BalanceLog {
	return predicate.BalanceLog(sql.FieldNotNull(FieldRelatedOrderNo))
}

// RelatedOrderNoEqualFold applies the EqualFold predicate on the "related_order_no" field.
func RelatedOrderNoEqualFold(v string) predicate.BalanceLog {
	return predicate.BalanceLog(sql.FieldEqualFold(FieldRelatedOrderNo, v))
}

// RelatedOrderNoContainsFold applies the ContainsFold predicate on the "related_order_no" field.
func RelatedOrderNoContainsFold(v string) predicate.BalanceLog {
	return predicate.BalanceLog(sql.FieldContainsFold(FieldRelatedOrderNo, v))
}

// DescriptionEQ applies the EQ predicate on the "description" field.
func DescriptionEQ(v string) predicate.BalanceLog {
	return predicate.BalanceLog(sql.FieldEQ(FieldDescription, v))
}

// DescriptionNEQ applies the NEQ predicate on the "description" field.
func DescriptionNEQ(v string) predicate.BalanceLog {
	return predicate.BalanceLog(sql.FieldNEQ(FieldDescription, v))
}

// DescriptionIn applies the In predicate on the "description" field.
func DescriptionIn(vs ...string) predicate.BalanceLog {
	return predicate.BalanceLog(sql.FieldIn(FieldDescription, vs...))
}

// DescriptionNotIn applies the NotIn predicate on the "description" field.
func DescriptionNotIn(vs ...string) predicate.BalanceLog {
	return predicate.BalanceLog(sql.FieldNotIn(FieldDescription, vs...))
}

// DescriptionGT applies the GT predicate on the "description" field.
func DescriptionGT(v string) predicate.BalanceLog {
	return predicate.BalanceLog(sql.FieldGT(FieldDescription, v))
}

// DescriptionGTE applies the GTE predicate on the "description" field.
func DescriptionGTE(v string) predicate.BalanceLog {
	return predicate.BalanceLog(sql.FieldGTE(FieldDescription, v))
}

// DescriptionLT applies the LT predicate on the "description" field.
func DescriptionLT(v string) predicate.BalanceLog {
	return predicate.BalanceLog(sql.FieldLT(FieldDescription, v))
}

// DescriptionLTE applies the LTE predicate on the "description" field.
func DescriptionLTE(v string) predicate.BalanceLog {
	return predicate.BalanceLog(sql.FieldLTE(FieldDescription, v))
}

// DescriptionContains applies the Contains predicate on the "description" field.
func DescriptionContains(v string) predicate.BalanceLog {
	return predicate.BalanceLog(sql.FieldContains(FieldDescription, v))
}

// DescriptionHasPrefix applies the HasPrefix predicate on the "description" field.
func DescriptionHasPrefix(v string) predicate.BalanceLog {
	return predicate.BalanceLog(sql.FieldHasPrefix(FieldDescription, v))
}

// DescriptionHasSuffix applies the HasSuffix predicate on the "description" field.
func DescriptionHasSuffix(v string) predicate.BalanceLog {
	return predicate.BalanceLog(sql.FieldHasSuffix(FieldDescription, v))
}

// DescriptionEqualFold applies the EqualFold predicate on the "description" field.
func DescriptionEqualFold(v string) predicate.BalanceLog {
	return predicate.BalanceLog(sql.FieldEqualFold(FieldDescription, v))
}

// DescriptionContainsFold applies the ContainsFold predicate on the "description" field.
func DescriptionContainsFold(v string) predicate.BalanceLog {
	return predicate.BalanceLog(sql.FieldContainsFold(FieldDescription, v))
}

// OperatorIDEQ applies the EQ predicate on the "operator_id" field.
func OperatorIDEQ(v int64) predicate.BalanceLog {
	return predicate.BalanceLog(sql.FieldEQ(FieldOperatorID, v))
}

// OperatorIDNEQ applies the NEQ predicate on the "operator_id" field.
func OperatorIDNEQ(v int64) predicate.BalanceLog {
	return predicate.BalanceLog(sql.FieldNEQ(FieldOperatorID, v))
}

// OperatorIDIn applies the In predicate on the "operator_id" field.
func OperatorIDIn(vs ...int64) predicate.BalanceLog {
	return predicate.BalanceLog(sql.FieldIn(FieldOperatorID, vs...))
}

// OperatorIDNotIn applies the NotIn predicate on the "operator_id" field.
func OperatorIDNotIn(vs ...int64) predicate.BalanceLog {
	return predicate.BalanceLog(sql.FieldNotIn(FieldOperatorID, vs...))
}

// OperatorIDGT applies the GT predicate on the "operator_id" field.
func OperatorIDGT(v int64) predicate.BalanceLog {
	return predicate.BalanceLog(sql.FieldGT(FieldOperatorID, v))
}

// OperatorIDGTE applies the GTE predicate on the "operator_id" field.
func OperatorIDGTE(v int64) predicate.BalanceLog {
	return predicate.BalanceLog(sql.FieldGTE(FieldOperatorID, v))
}

// OperatorIDLT applies the LT predicate on the "operator_id" field.
func OperatorIDLT(v int64) predicate.BalanceLog {
	return predicate.BalanceLog(sql.FieldLT(FieldOperatorID, v))
}

// OperatorIDLTE applies the LTE predicate on the "operator_id" field.
func OperatorIDLTE(v int64) predicate.BalanceLog {
	return predicate.BalanceLog(sql.FieldLTE(FieldOperatorID, v))
}

// OperatorTypeEQ applies the EQ predicate on the "operator_type" field.
func OperatorTypeEQ(v string) predicate.BalanceLog {
	return predicate.BalanceLog(sql.FieldEQ(FieldOperatorType, v))
}

// OperatorTypeNEQ applies the NEQ predicate on the "operator_type" field.
func OperatorTypeNEQ(v string) predicate.BalanceLog {
	return predicate.BalanceLog(sql.FieldNEQ(FieldOperatorType, v))
}

// OperatorTypeIn applies the In predicate on the "operator_type" field.
func OperatorTypeIn(vs ...string) predicate.BalanceLog {
	return predicate.BalanceLog(sql.FieldIn(FieldOperatorType, vs...))
}

// OperatorTypeNotIn applies the NotIn predicate on the "operator_type" field.
func OperatorTypeNotIn(vs ...string) predicate.BalanceLog {
	return predicate.BalanceLog(sql.FieldNotIn(FieldOperatorType, vs...))
}

// OperatorTypeGT applies the GT predicate on the "operator_type" field.
func OperatorTypeGT(v string) predicate.BalanceLog {
	return predicate.BalanceLog(sql.FieldGT(FieldOperatorType, v))
}

// OperatorTypeGTE applies the GTE predicate on the "operator_type" field.
func OperatorTypeGTE(v string) predicate.BalanceLog {
	return predicate.BalanceLog(sql.FieldGTE(FieldOperatorType, v))
}

// OperatorTypeLT applies the LT predicate on the "operator_type" field.
func OperatorTypeLT(v string) predicate.BalanceLog {
	return predicate.BalanceLog(sql.FieldLT(FieldOperatorType, v))
}

// OperatorTypeLTE applies the LTE predicate on the "operator_type" field.
func OperatorTypeLTE(v string) predicate.BalanceLog {
	return predicate.BalanceLog(sql.FieldLTE(FieldOperatorType, v))
}

// OperatorTypeContains applies the Contains predicate on the "operator_type" field.
func OperatorTypeContains(v string) predicate.BalanceLog {
	return predicate.BalanceLog(sql.FieldContains(FieldOperatorType, v))
}

// OperatorTypeHasPrefix applies the HasPrefix predicate on the "operator_type" field.
func OperatorTypeHasPrefix(v string) predicate.BalanceLog {
	return predicate.BalanceLog(sql.FieldHasPrefix(FieldOperatorType, v))
}

// OperatorTypeHasSuffix applies the HasSuffix predicate on the "operator_type" field.
func OperatorTypeHasSuffix(v string) predicate.BalanceLog {
	return predicate.BalanceLog(sql.FieldHasSuffix(FieldOperatorType, v))
}

// OperatorTypeEqualFold applies the EqualFold predicate on the "operator_type" field.
func OperatorTypeEqualFold(v string) predicate.BalanceLog {
	return predicate.BalanceLog(sql.FieldEqualFold(FieldOperatorType, v))
}

// OperatorTypeContainsFold applies the ContainsFold predicate on the "operator_type" field.
func OperatorTypeContainsFold(v string) predicate.BalanceLog {
	return predicate.BalanceLog(sql.FieldContainsFold(FieldOperatorType, v))
}

// HasUser applies the HasEdge predicate on the "user" edge.
func HasUser() predicate.BalanceLog {
	return predicate.BalanceLog(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, UserTable, UserColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasUserWith applies the HasEdge predicate on the "user" edge with a given conditions (other predicates).
func HasUserWith(preds ...predicate.User) predicate.BalanceLog {
	return predicate.BalanceLog(func(s *sql.Selector) {
		step := newUserStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.BalanceLog) predicate.BalanceLog {
	return predicate.BalanceLog(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.BalanceLog) predicate.BalanceLog {
	return predicate.BalanceLog(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.BalanceLog) predicate.BalanceLog {
	return predicate.BalanceLog(sql.NotPredicates(p))
}
