// Code generated by ent, DO NOT EDIT.

package copilotquotasnapshot

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.CopilotQuotaSnapshot {
	return predicate.CopilotQuotaSnapshot(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.CopilotQuotaSnapshot {
	return predicate.CopilotQuotaSnapshot(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.CopilotQuotaSnapshot {
	return predicate.CopilotQuotaSnapshot(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.CopilotQuotaSnapshot {
	return predicate.CopilotQuotaSnapshot(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.CopilotQuotaSnapshot {
	return predicate.CopilotQuotaSnapshot(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.CopilotQuotaSnapshot {
	return predicate.CopilotQuotaSnapshot(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.CopilotQuotaSnapshot {
	return predicate.CopilotQuotaSnapshot(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.CopilotQuotaSnapshot {
	return predicate.CopilotQuotaSnapshot(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.CopilotQuotaSnapshot {
	return predicate.CopilotQuotaSnapshot(sql.FieldLTE(FieldID, id))
}

// AccountID applies equality check predicate on the "account_id" field. It's identical to AccountIDEQ.
func AccountID(v int64) predicate.CopilotQuotaSnapshot {
	return predicate.CopilotQuotaSnapshot(sql.FieldEQ(FieldAccountID, v))
}

// SnapshotDate applies equality check predicate on the "snapshot_date" field. It's identical to SnapshotDateEQ.
func SnapshotDate(v time.Time) predicate.CopilotQuotaSnapshot {
	return predicate.CopilotQuotaSnapshot(sql.FieldEQ(FieldSnapshotDate, v))
}

// PlanType applies equality check predicate on the "plan_type" field. It's identical to PlanTypeEQ.
func PlanType(v string) predicate.CopilotQuotaSnapshot {
	return predicate.CopilotQuotaSnapshot(sql.FieldEQ(FieldPlanType, v))
}

// PremiumEntitlement applies equality check predicate on the "premium_entitlement" field. It's identical to PremiumEntitlementEQ.
func PremiumEntitlement(v int) predicate.CopilotQuotaSnapshot {
	return predicate.CopilotQuotaSnapshot(sql.FieldEQ(FieldPremiumEntitlement, v))
}

// PremiumRemaining applies equality check predicate on the "premium_remaining" field. It's identical to PremiumRemainingEQ.
func PremiumRemaining(v int) predicate.CopilotQuotaSnapshot {
	return predicate.CopilotQuotaSnapshot(sql.FieldEQ(FieldPremiumRemaining, v))
}

// PremiumUsed applies equality check predicate on the "premium_used" field. It's identical to PremiumUsedEQ.
func PremiumUsed(v int) predicate.CopilotQuotaSnapshot {
	return predicate.CopilotQuotaSnapshot(sql.FieldEQ(FieldPremiumUsed, v))
}

// PremiumOverage applies equality check predicate on the "premium_overage" field. It's identical to PremiumOverageEQ.
func PremiumOverage(v int) predicate.CopilotQuotaSnapshot {
	return predicate.CopilotQuotaSnapshot(sql.FieldEQ(FieldPremiumOverage, v))
}

// Unlimited applies equality check predicate on the "unlimited" field. It's identical to UnlimitedEQ.
func Unlimited(v bool) predicate.CopilotQuotaSnapshot {
	return predicate.CopilotQuotaSnapshot(sql.FieldEQ(FieldUnlimited, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.CopilotQuotaSnapshot {
	return predicate.CopilotQuotaSnapshot(sql.FieldEQ(FieldCreatedAt, v))
}

// AccountIDEQ applies the EQ predicate on the "account_id" field.
func AccountIDEQ(v int64) predicate.CopilotQuotaSnapshot {
	return predicate.CopilotQuotaSnapshot(sql.FieldEQ(FieldAccountID, v))
}

// AccountIDNEQ applies the NEQ predicate on the "account_id" field.
func AccountIDNEQ(v int64) predicate.CopilotQuotaSnapshot {
	return predicate.CopilotQuotaSnapshot(sql.FieldNEQ(FieldAccountID, v))
}

// AccountIDIn applies the In predicate on the "account_id" field.
func AccountIDIn(vs ...int64) predicate.CopilotQuotaSnapshot {
	return predicate.CopilotQuotaSnapshot(sql.FieldIn(FieldAccountID, vs...))
}

// AccountIDNotIn applies the NotIn predicate on the "account_id" field.
func AccountIDNotIn(vs ...int64) predicate.CopilotQuotaSnapshot {
	return predicate.CopilotQuotaSnapshot(sql.FieldNotIn(FieldAccountID, vs...))
}

// AccountIDGT applies the GT predicate on the "account_id" field.
func AccountIDGT(v int64) predicate.CopilotQuotaSnapshot {
	return predicate.CopilotQuotaSnapshot(sql.FieldGT(FieldAccountID, v))
}

// AccountIDGTE applies the GTE predicate on the "account_id" field.
func AccountIDGTE(v int64) predicate.CopilotQuotaSnapshot {
	return predicate.CopilotQuotaSnapshot(sql.FieldGTE(FieldAccountID, v))
}

// AccountIDLT applies the LT predicate on the "account_id" field.
func AccountIDLT(v int64) predicate.CopilotQuotaSnapshot {
	return predicate.CopilotQuotaSnapshot(sql.FieldLT(FieldAccountID, v))
}

// AccountIDLTE applies the LTE predicate on the "account_id" field.
func AccountIDLTE(v int64) predicate.CopilotQuotaSnapshot {
	return predicate.CopilotQuotaSnapshot(sql.FieldLTE(FieldAccountID, v))
}

// SnapshotDateEQ applies the EQ predicate on the "snapshot_date" field.
func SnapshotDateEQ(v time.Time) predicate.CopilotQuotaSnapshot {
	return predicate.CopilotQuotaSnapshot(sql.FieldEQ(FieldSnapshotDate, v))
}

// SnapshotDateNEQ applies the NEQ predicate on the "snapshot_date" field.
func SnapshotDateNEQ(v time.Time) predicate.CopilotQuotaSnapshot {
	return predicate.CopilotQuotaSnapshot(sql.FieldNEQ(FieldSnapshotDate, v))
}

// SnapshotDateIn applies the In predicate on the "snapshot_date" field.
func SnapshotDateIn(vs ...time.Time) predicate.CopilotQuotaSnapshot {
	return predicate.CopilotQuotaSnapshot(sql.FieldIn(FieldSnapshotDate, vs...))
}

// SnapshotDateNotIn applies the NotIn predicate on the "snapshot_date" field.
func SnapshotDateNotIn(vs ...time.Time) predicate.CopilotQuotaSnapshot {
	return predicate.CopilotQuotaSnapshot(sql.FieldNotIn(FieldSnapshotDate, vs...))
}

// SnapshotDateGT applies the GT predicate on the "snapshot_date" field.
func SnapshotDateGT(v time.Time) predicate.CopilotQuotaSnapshot {
	return predicate.CopilotQuotaSnapshot(sql.FieldGT(FieldSnapshotDate, v))
}

// SnapshotDateGTE applies the GTE predicate on the "snapshot_date" field.
func SnapshotDateGTE(v time.Time) predicate.CopilotQuotaSnapshot {
	return predicate.CopilotQuotaSnapshot(sql.FieldGTE(FieldSnapshotDate, v))
}

// SnapshotDateLT applies the LT predicate on the "snapshot_date" field.
func SnapshotDateLT(v time.Time) predicate.CopilotQuotaSnapshot {
	return predicate.CopilotQuotaSnapshot(sql.FieldLT(FieldSnapshotDate, v))
}

// SnapshotDateLTE applies the LTE predicate on the "snapshot_date" field.
func SnapshotDateLTE(v time.Time) predicate.CopilotQuotaSnapshot {
	return predicate.CopilotQuotaSnapshot(sql.FieldLTE(FieldSnapshotDate, v))
}

// PlanTypeEQ applies the EQ predicate on the "plan_type" field.
func PlanTypeEQ(v string) predicate.CopilotQuotaSnapshot {
	return predicate.CopilotQuotaSnapshot(sql.FieldEQ(FieldPlanType, v))
}

// PlanTypeNEQ applies the NEQ predicate on the "plan_type" field.
func PlanTypeNEQ(v string) predicate.CopilotQuotaSnapshot {
	return predicate.CopilotQuotaSnapshot(sql.FieldNEQ(FieldPlanType, v))
}

// PlanTypeIn applies the In predicate on the "plan_type" field.
func PlanTypeIn(vs ...string) predicate.CopilotQuotaSnapshot {
	return predicate.CopilotQuotaSnapshot(sql.FieldIn(FieldPlanType, vs...))
}

// PlanTypeNotIn applies the NotIn predicate on the "plan_type" field.
func PlanTypeNotIn(vs ...string) predicate.CopilotQuotaSnapshot {
	return predicate.CopilotQuotaSnapshot(sql.FieldNotIn(FieldPlanType, vs...))
}

// PlanTypeGT applies the GT predicate on the "plan_type" field.
func PlanTypeGT(v string) predicate.CopilotQuotaSnapshot {
	return predicate.CopilotQuotaSnapshot(sql.FieldGT(FieldPlanType, v))
}

// PlanTypeGTE applies the GTE predicate on the "plan_type" field.
func PlanTypeGTE(v string) predicate.CopilotQuotaSnapshot {
	return predicate.CopilotQuotaSnapshot(sql.FieldGTE(FieldPlanType, v))
}

// PlanTypeLT applies the LT predicate on the "plan_type" field.
func PlanTypeLT(v string) predicate.CopilotQuotaSnapshot {
	return predicate.CopilotQuotaSnapshot(sql.FieldLT(FieldPlanType, v))
}

// PlanTypeLTE applies the LTE predicate on the "plan_type" field.
func PlanTypeLTE(v string) predicate.CopilotQuotaSnapshot {
	return predicate.CopilotQuotaSnapshot(sql.FieldLTE(FieldPlanType, v))
}

// PlanTypeContains applies the Contains predicate on the "plan_type" field.
func PlanTypeContains(v string) predicate.CopilotQuotaSnapshot {
	return predicate.CopilotQuotaSnapshot(sql.FieldContains(FieldPlanType, v))
}

// PlanTypeHasPrefix applies the HasPrefix predicate on the "plan_type" field.
func PlanTypeHasPrefix(v string) predicate.CopilotQuotaSnapshot {
	return predicate.CopilotQuotaSnapshot(sql.FieldHasPrefix(FieldPlanType, v))
}

// PlanTypeHasSuffix applies the HasSuffix predicate on the "plan_type" field.
func PlanTypeHasSuffix(v string) predicate.CopilotQuotaSnapshot {
	return predicate.CopilotQuotaSnapshot(sql.FieldHasSuffix(FieldPlanType, v))
}

// PlanTypeIsNil applies the IsNil predicate on the "plan_type" field.
func PlanTypeIsNil() predicate.CopilotQuotaSnapshot {
	return predicate.CopilotQuotaSnapshot(sql.FieldIsNull(FieldPlanType))
}

// PlanTypeNotNil applies the NotNil predicate on the "plan_type" field.
func PlanTypeNotNil() predicate.CopilotQuotaSnapshot {
	return predicate.CopilotQuotaSnapshot(sql.FieldNotNull(FieldPlanType))
}

// PlanTypeEqualFold applies the EqualFold predicate on the "plan_type" field.
func PlanTypeEqualFold(v string) predicate.CopilotQuotaSnapshot {
	return predicate.CopilotQuotaSnapshot(sql.FieldEqualFold(FieldPlanType, v))
}

// PlanTypeContainsFold applies the ContainsFold predicate on the "plan_type" field.
func PlanTypeContainsFold(v string) predicate.CopilotQuotaSnapshot {
	return predicate.CopilotQuotaSnapshot(sql.FieldContainsFold(FieldPlanType, v))
}

// PremiumEntitlementEQ applies the EQ predicate on the "premium_entitlement" field.
func PremiumEntitlementEQ(v int) predicate.CopilotQuotaSnapshot {
	return predicate.CopilotQuotaSnapshot(sql.FieldEQ(FieldPremiumEntitlement, v))
}

// PremiumEntitlementNEQ applies the NEQ predicate on the "premium_entitlement" field.
func PremiumEntitlementNEQ(v int) predicate.CopilotQuotaSnapshot {
	return predicate.CopilotQuotaSnapshot(sql.FieldNEQ(FieldPremiumEntitlement, v))
}

// PremiumEntitlementIn applies the In predicate on the "premium_entitlement" field.
func PremiumEntitlementIn(vs ...int) predicate.CopilotQuotaSnapshot {
	return predicate.CopilotQuotaSnapshot(sql.FieldIn(FieldPremiumEntitlement, vs...))
}

// PremiumEntitlementNotIn applies the NotIn predicate on the "premium_entitlement" field.
func PremiumEntitlementNotIn(vs ...int) predicate.CopilotQuotaSnapshot {
	return predicate.CopilotQuotaSnapshot(sql.FieldNotIn(FieldPremiumEntitlement, vs...))
}

// PremiumEntitlementGT applies the GT predicate on the "premium_entitlement" field.
func PremiumEntitlementGT(v int) predicate.CopilotQuotaSnapshot {
	return predicate.CopilotQuotaSnapshot(sql.FieldGT(FieldPremiumEntitlement, v))
}

// PremiumEntitlementGTE applies the GTE predicate on the "premium_entitlement" field.
func PremiumEntitlementGTE(v int) predicate.CopilotQuotaSnapshot {
	return predicate.CopilotQuotaSnapshot(sql.FieldGTE(FieldPremiumEntitlement, v))
}

// PremiumEntitlementLT applies the LT predicate on the "premium_entitlement" field.
func PremiumEntitlementLT(v int) predicate.CopilotQuotaSnapshot {
	return predicate.CopilotQuotaSnapshot(sql.FieldLT(FieldPremiumEntitlement, v))
}

// PremiumEntitlementLTE applies the LTE predicate on the "premium_entitlement" field.
func PremiumEntitlementLTE(v int) predicate.CopilotQuotaSnapshot {
	return predicate.CopilotQuotaSnapshot(sql.FieldLTE(FieldPremiumEntitlement, v))
}

// PremiumRemainingEQ applies the EQ predicate on the "premium_remaining" field.
func PremiumRemainingEQ(v int) predicate.CopilotQuotaSnapshot {
	return predicate.CopilotQuotaSnapshot(sql.FieldEQ(FieldPremiumRemaining, v))
}

// PremiumRemainingNEQ applies the NEQ predicate on the "premium_remaining" field.
func PremiumRemainingNEQ(v int) predicate.CopilotQuotaSnapshot {
	return predicate.CopilotQuotaSnapshot(sql.FieldNEQ(FieldPremiumRemaining, v))
}

// PremiumRemainingIn applies the In predicate on the "premium_remaining" field.
func PremiumRemainingIn(vs ...int) predicate.CopilotQuotaSnapshot {
	return predicate.CopilotQuotaSnapshot(sql.FieldIn(FieldPremiumRemaining, vs...))
}

// PremiumRemainingNotIn applies the NotIn predicate on the "premium_remaining" field.
func PremiumRemainingNotIn(vs ...int) predicate.CopilotQuotaSnapshot {
	return predicate.CopilotQuotaSnapshot(sql.FieldNotIn(FieldPremiumRemaining, vs...))
}

// PremiumRemainingGT applies the GT predicate on the "premium_remaining" field.
func PremiumRemainingGT(v int) predicate.CopilotQuotaSnapshot {
	return predicate.CopilotQuotaSnapshot(sql.FieldGT(FieldPremiumRemaining, v))
}

// PremiumRemainingGTE applies the GTE predicate on the "premium_remaining" field.
func PremiumRemainingGTE(v int) predicate.CopilotQuotaSnapshot {
	return predicate.CopilotQuotaSnapshot(sql.FieldGTE(FieldPremiumRemaining, v))
}

// PremiumRemainingLT applies the LT predicate on the "premium_remaining" field.
func PremiumRemainingLT(v int) predicate.CopilotQuotaSnapshot {
	return predicate.CopilotQuotaSnapshot(sql.FieldLT(FieldPremiumRemaining, v))
}

// PremiumRemainingLTE applies the LTE predicate on the "premium_remaining" field.
func PremiumRemainingLTE(v int) predicate.CopilotQuotaSnapshot {
	return predicate.CopilotQuotaSnapshot(sql.FieldLTE(FieldPremiumRemaining, v))
}

// PremiumUsedEQ applies the EQ predicate on the "premium_used" field.
func PremiumUsedEQ(v int) predicate.CopilotQuotaSnapshot {
	return predicate.CopilotQuotaSnapshot(sql.FieldEQ(FieldPremiumUsed, v))
}

// PremiumUsedNEQ applies the NEQ predicate on the "premium_used" field.
func PremiumUsedNEQ(v int) predicate.CopilotQuotaSnapshot {
	return predicate.CopilotQuotaSnapshot(sql.FieldNEQ(FieldPremiumUsed, v))
}

// PremiumUsedIn applies the In predicate on the "premium_used" field.
func PremiumUsedIn(vs ...int) predicate.CopilotQuotaSnapshot {
	return predicate.CopilotQuotaSnapshot(sql.FieldIn(FieldPremiumUsed, vs...))
}

// PremiumUsedNotIn applies the NotIn predicate on the "premium_used" field.
func PremiumUsedNotIn(vs ...int) predicate.CopilotQuotaSnapshot {
	return predicate.CopilotQuotaSnapshot(sql.FieldNotIn(FieldPremiumUsed, vs...))
}

// PremiumUsedGT applies the GT predicate on the "premium_used" field.
func PremiumUsedGT(v int) predicate.CopilotQuotaSnapshot {
	return predicate.CopilotQuotaSnapshot(sql.FieldGT(FieldPremiumUsed, v))
}

// PremiumUsedGTE applies the GTE predicate on the "premium_used" field.
func PremiumUsedGTE(v int) predicate.CopilotQuotaSnapshot {
	return predicate.CopilotQuotaSnapshot(sql.FieldGTE(FieldPremiumUsed, v))
}

// PremiumUsedLT applies the LT predicate on the "premium_used" field.
func PremiumUsedLT(v int) predicate.CopilotQuotaSnapshot {
	return predicate.CopilotQuotaSnapshot(sql.FieldLT(FieldPremiumUsed, v))
}

// PremiumUsedLTE applies the LTE predicate on the "premium_used" field.
func PremiumUsedLTE(v int) predicate.CopilotQuotaSnapshot {
	return predicate.CopilotQuotaSnapshot(sql.FieldLTE(FieldPremiumUsed, v))
}

// PremiumOverageEQ applies the EQ predicate on the "premium_overage" field.
func PremiumOverageEQ(v int) predicate.CopilotQuotaSnapshot {
	return predicate.CopilotQuotaSnapshot(sql.FieldEQ(FieldPremiumOverage, v))
}

// PremiumOverageNEQ applies the NEQ predicate on the "premium_overage" field.
func PremiumOverageNEQ(v int) predicate.CopilotQuotaSnapshot {
	return predicate.CopilotQuotaSnapshot(sql.FieldNEQ(FieldPremiumOverage, v))
}

// PremiumOverageIn applies the In predicate on the "premium_overage" field.
func PremiumOverageIn(vs ...int) predicate.CopilotQuotaSnapshot {
	return predicate.CopilotQuotaSnapshot(sql.FieldIn(FieldPremiumOverage, vs...))
}

// PremiumOverageNotIn applies the NotIn predicate on the "premium_overage" field.
func PremiumOverageNotIn(vs ...int) predicate.CopilotQuotaSnapshot {
	return predicate.CopilotQuotaSnapshot(sql.FieldNotIn(FieldPremiumOverage, vs...))
}

// PremiumOverageGT applies the GT predicate on the "premium_overage" field.
func PremiumOverageGT(v int) predicate.CopilotQuotaSnapshot {
	return predicate.CopilotQuotaSnapshot(sql.FieldGT(FieldPremiumOverage, v))
}

// PremiumOverageGTE applies the GTE predicate on the "premium_overage" field.
func PremiumOverageGTE(v int) predicate.CopilotQuotaSnapshot {
	return predicate.CopilotQuotaSnapshot(sql.FieldGTE(FieldPremiumOverage, v))
}

// PremiumOverageLT applies the LT predicate on the "premium_overage" field.
func PremiumOverageLT(v int) predicate.CopilotQuotaSnapshot {
	return predicate.CopilotQuotaSnapshot(sql.FieldLT(FieldPremiumOverage, v))
}

// PremiumOverageLTE applies the LTE predicate on the "premium_overage" field.
func PremiumOverageLTE(v int) predicate.CopilotQuotaSnapshot {
	return predicate.CopilotQuotaSnapshot(sql.FieldLTE(FieldPremiumOverage, v))
}

// UnlimitedEQ applies the EQ predicate on the "unlimited" field.
func UnlimitedEQ(v bool) predicate.CopilotQuotaSnapshot {
	return predicate.CopilotQuotaSnapshot(sql.FieldEQ(FieldUnlimited, v))
}

// UnlimitedNEQ applies the NEQ predicate on the "unlimited" field.
func UnlimitedNEQ(v bool) predicate.CopilotQuotaSnapshot {
	return predicate.CopilotQuotaSnapshot(sql.FieldNEQ(FieldUnlimited, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.CopilotQuotaSnapshot {
	return predicate.CopilotQuotaSnapshot(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.CopilotQuotaSnapshot {
	return predicate.CopilotQuotaSnapshot(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.CopilotQuotaSnapshot {
	return predicate.CopilotQuotaSnapshot(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.CopilotQuotaSnapshot {
	return predicate.CopilotQuotaSnapshot(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.CopilotQuotaSnapshot {
	return predicate.CopilotQuotaSnapshot(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.CopilotQuotaSnapshot {
	return predicate.CopilotQuotaSnapshot(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.CopilotQuotaSnapshot {
	return predicate.CopilotQuotaSnapshot(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.CopilotQuotaSnapshot {
	return predicate.CopilotQuotaSnapshot(sql.FieldLTE(FieldCreatedAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.CopilotQuotaSnapshot) predicate.CopilotQuotaSnapshot {
	return predicate.CopilotQuotaSnapshot(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.CopilotQuotaSnapshot) predicate.CopilotQuotaSnapshot {
	return predicate.CopilotQuotaSnapshot(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.CopilotQuotaSnapshot) predicate.CopilotQuotaSnapshot {
	return predicate.CopilotQuotaSnapshot(sql.NotPredicates(p))
}
